// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[derive(Clone, Copy, PartialEq)]
pub struct ActivityClass(pub u8);

impl ActivityClass {
    /// 0 to 100
    pub const LEVEL: ActivityClass = ActivityClass(0x7F);
    pub const LEVEL_MAX: ActivityClass = ActivityClass(100);
    pub const ATHLETE: ActivityClass = ActivityClass(0x80);
}

impl Default for ActivityClass {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for ActivityClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0x7F => write!(f, "level"),
            100 => write!(f, "level_max"),
            0x80 => write!(f, "athlete"),
            _ => write!(f, "ActivityClass({})", self.0),
        }
    }
}

impl fmt::Debug for ActivityClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0x7F => write!(f, "ActivityClass::LEVEL(0x7F)"),
            100 => write!(f, "ActivityClass::LEVEL_MAX(100)"),
            0x80 => write!(f, "ActivityClass::ATHLETE(0x80)"),
            _ => write!(f, "ActivityClass({})", self.0),
        }
    }
}
