// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct AntplusDeviceType(pub u8);

impl AntplusDeviceType {
    pub const ANTFS: AntplusDeviceType = AntplusDeviceType(1);
    pub const BIKE_POWER: AntplusDeviceType = AntplusDeviceType(11);
    pub const ENVIRONMENT_SENSOR_LEGACY: AntplusDeviceType = AntplusDeviceType(12);
    pub const MULTI_SPORT_SPEED_DISTANCE: AntplusDeviceType = AntplusDeviceType(15);
    pub const CONTROL: AntplusDeviceType = AntplusDeviceType(16);
    pub const FITNESS_EQUIPMENT: AntplusDeviceType = AntplusDeviceType(17);
    pub const BLOOD_PRESSURE: AntplusDeviceType = AntplusDeviceType(18);
    pub const GEOCACHE_NODE: AntplusDeviceType = AntplusDeviceType(19);
    pub const LIGHT_ELECTRIC_VEHICLE: AntplusDeviceType = AntplusDeviceType(20);
    pub const ENV_SENSOR: AntplusDeviceType = AntplusDeviceType(25);
    pub const RACQUET: AntplusDeviceType = AntplusDeviceType(26);
    pub const CONTROL_HUB: AntplusDeviceType = AntplusDeviceType(27);
    pub const MUSCLE_OXYGEN: AntplusDeviceType = AntplusDeviceType(31);
    pub const SHIFTING: AntplusDeviceType = AntplusDeviceType(34);
    pub const BIKE_LIGHT_MAIN: AntplusDeviceType = AntplusDeviceType(35);
    pub const BIKE_LIGHT_SHARED: AntplusDeviceType = AntplusDeviceType(36);
    pub const EXD: AntplusDeviceType = AntplusDeviceType(38);
    pub const BIKE_RADAR: AntplusDeviceType = AntplusDeviceType(40);
    pub const BIKE_AERO: AntplusDeviceType = AntplusDeviceType(46);
    pub const WEIGHT_SCALE: AntplusDeviceType = AntplusDeviceType(119);
    pub const HEART_RATE: AntplusDeviceType = AntplusDeviceType(120);
    pub const BIKE_SPEED_CADENCE: AntplusDeviceType = AntplusDeviceType(121);
    pub const BIKE_CADENCE: AntplusDeviceType = AntplusDeviceType(122);
    pub const BIKE_SPEED: AntplusDeviceType = AntplusDeviceType(123);
    pub const STRIDE_SPEED_DISTANCE: AntplusDeviceType = AntplusDeviceType(124);
}

impl Default for AntplusDeviceType {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for AntplusDeviceType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            1 => write!(f, "antfs"),
            11 => write!(f, "bike_power"),
            12 => write!(f, "environment_sensor_legacy"),
            15 => write!(f, "multi_sport_speed_distance"),
            16 => write!(f, "control"),
            17 => write!(f, "fitness_equipment"),
            18 => write!(f, "blood_pressure"),
            19 => write!(f, "geocache_node"),
            20 => write!(f, "light_electric_vehicle"),
            25 => write!(f, "env_sensor"),
            26 => write!(f, "racquet"),
            27 => write!(f, "control_hub"),
            31 => write!(f, "muscle_oxygen"),
            34 => write!(f, "shifting"),
            35 => write!(f, "bike_light_main"),
            36 => write!(f, "bike_light_shared"),
            38 => write!(f, "exd"),
            40 => write!(f, "bike_radar"),
            46 => write!(f, "bike_aero"),
            119 => write!(f, "weight_scale"),
            120 => write!(f, "heart_rate"),
            121 => write!(f, "bike_speed_cadence"),
            122 => write!(f, "bike_cadence"),
            123 => write!(f, "bike_speed"),
            124 => write!(f, "stride_speed_distance"),
            _ => write!(f, "AntplusDeviceType({})", self.0),
        }
    }
}

impl fmt::Debug for AntplusDeviceType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            1 => write!(f, "AntplusDeviceType::ANTFS(1)"),
            11 => write!(f, "AntplusDeviceType::BIKE_POWER(11)"),
            12 => write!(f, "AntplusDeviceType::ENVIRONMENT_SENSOR_LEGACY(12)"),
            15 => write!(f, "AntplusDeviceType::MULTI_SPORT_SPEED_DISTANCE(15)"),
            16 => write!(f, "AntplusDeviceType::CONTROL(16)"),
            17 => write!(f, "AntplusDeviceType::FITNESS_EQUIPMENT(17)"),
            18 => write!(f, "AntplusDeviceType::BLOOD_PRESSURE(18)"),
            19 => write!(f, "AntplusDeviceType::GEOCACHE_NODE(19)"),
            20 => write!(f, "AntplusDeviceType::LIGHT_ELECTRIC_VEHICLE(20)"),
            25 => write!(f, "AntplusDeviceType::ENV_SENSOR(25)"),
            26 => write!(f, "AntplusDeviceType::RACQUET(26)"),
            27 => write!(f, "AntplusDeviceType::CONTROL_HUB(27)"),
            31 => write!(f, "AntplusDeviceType::MUSCLE_OXYGEN(31)"),
            34 => write!(f, "AntplusDeviceType::SHIFTING(34)"),
            35 => write!(f, "AntplusDeviceType::BIKE_LIGHT_MAIN(35)"),
            36 => write!(f, "AntplusDeviceType::BIKE_LIGHT_SHARED(36)"),
            38 => write!(f, "AntplusDeviceType::EXD(38)"),
            40 => write!(f, "AntplusDeviceType::BIKE_RADAR(40)"),
            46 => write!(f, "AntplusDeviceType::BIKE_AERO(46)"),
            119 => write!(f, "AntplusDeviceType::WEIGHT_SCALE(119)"),
            120 => write!(f, "AntplusDeviceType::HEART_RATE(120)"),
            121 => write!(f, "AntplusDeviceType::BIKE_SPEED_CADENCE(121)"),
            122 => write!(f, "AntplusDeviceType::BIKE_CADENCE(122)"),
            123 => write!(f, "AntplusDeviceType::BIKE_SPEED(123)"),
            124 => write!(f, "AntplusDeviceType::STRIDE_SPEED_DISTANCE(124)"),
            _ => write!(f, "AntplusDeviceType({})", self.0),
        }
    }
}
