// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Auto Activity Detect type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AutoActivityDetect(pub u32);

impl AutoActivityDetect {
    pub const NONE: AutoActivityDetect = AutoActivityDetect(0x00000000);
    pub const RUNNING: AutoActivityDetect = AutoActivityDetect(0x00000001);
    pub const CYCLING: AutoActivityDetect = AutoActivityDetect(0x00000002);
    pub const SWIMMING: AutoActivityDetect = AutoActivityDetect(0x00000004);
    pub const WALKING: AutoActivityDetect = AutoActivityDetect(0x00000008);
    pub const ELLIPTICAL: AutoActivityDetect = AutoActivityDetect(0x00000020);
    pub const SEDENTARY: AutoActivityDetect = AutoActivityDetect(0x00000400);
}

impl Default for AutoActivityDetect {
    fn default() -> Self {
        Self(u32::MAX)
    }
}

impl fmt::Display for AutoActivityDetect {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0x00000000 => write!(f, "none"),
            0x00000001 => write!(f, "running"),
            0x00000002 => write!(f, "cycling"),
            0x00000004 => write!(f, "swimming"),
            0x00000008 => write!(f, "walking"),
            0x00000020 => write!(f, "elliptical"),
            0x00000400 => write!(f, "sedentary"),
            _ => write!(f, "AutoActivityDetect({})", self.0),
        }
    }
}
