// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Autolap Trigger type.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct AutolapTrigger(pub u8);

impl AutolapTrigger {
    pub const TIME: AutolapTrigger = AutolapTrigger(0);
    pub const DISTANCE: AutolapTrigger = AutolapTrigger(1);
    pub const POSITION_START: AutolapTrigger = AutolapTrigger(2);
    pub const POSITION_LAP: AutolapTrigger = AutolapTrigger(3);
    pub const POSITION_WAYPOINT: AutolapTrigger = AutolapTrigger(4);
    pub const POSITION_MARKED: AutolapTrigger = AutolapTrigger(5);
    pub const OFF: AutolapTrigger = AutolapTrigger(6);
    pub const AUTO_SELECT: AutolapTrigger = AutolapTrigger(13);
}

impl Default for AutolapTrigger {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for AutolapTrigger {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "time"),
            1 => write!(f, "distance"),
            2 => write!(f, "position_start"),
            3 => write!(f, "position_lap"),
            4 => write!(f, "position_waypoint"),
            5 => write!(f, "position_marked"),
            6 => write!(f, "off"),
            13 => write!(f, "auto_select"),
            _ => write!(f, "AutolapTrigger({})", self.0),
        }
    }
}

impl fmt::Debug for AutolapTrigger {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "AutolapTrigger::TIME(0)"),
            1 => write!(f, "AutolapTrigger::DISTANCE(1)"),
            2 => write!(f, "AutolapTrigger::POSITION_START(2)"),
            3 => write!(f, "AutolapTrigger::POSITION_LAP(3)"),
            4 => write!(f, "AutolapTrigger::POSITION_WAYPOINT(4)"),
            5 => write!(f, "AutolapTrigger::POSITION_MARKED(5)"),
            6 => write!(f, "AutolapTrigger::OFF(6)"),
            13 => write!(f, "AutolapTrigger::AUTO_SELECT(13)"),
            _ => write!(f, "AutolapTrigger({})", self.0),
        }
    }
}
