// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Banded Exercises Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct BandedExercisesExerciseName(pub u16);

impl BandedExercisesExerciseName {
    pub const AB_TWIST: BandedExercisesExerciseName = BandedExercisesExerciseName(1);
    pub const BACK_EXTENSION: BandedExercisesExerciseName = BandedExercisesExerciseName(2);
    pub const BICYCLE_CRUNCH: BandedExercisesExerciseName = BandedExercisesExerciseName(3);
    pub const CALF_RAISES: BandedExercisesExerciseName = BandedExercisesExerciseName(4);
    pub const CHEST_PRESS: BandedExercisesExerciseName = BandedExercisesExerciseName(5);
    pub const CLAM_SHELLS: BandedExercisesExerciseName = BandedExercisesExerciseName(6);
    pub const CURL: BandedExercisesExerciseName = BandedExercisesExerciseName(7);
    pub const DEADBUG: BandedExercisesExerciseName = BandedExercisesExerciseName(8);
    pub const DEADLIFT: BandedExercisesExerciseName = BandedExercisesExerciseName(9);
    pub const DONKEY_KICK: BandedExercisesExerciseName = BandedExercisesExerciseName(10);
    pub const EXTERNAL_ROTATION: BandedExercisesExerciseName = BandedExercisesExerciseName(11);
    pub const EXTERNAL_ROTATION_AT_90_DEGREE_ABDUCTION: BandedExercisesExerciseName =
        BandedExercisesExerciseName(12);
    pub const FACE_PULL: BandedExercisesExerciseName = BandedExercisesExerciseName(13);
    pub const FIRE_HYDRANT: BandedExercisesExerciseName = BandedExercisesExerciseName(14);
    pub const FLY: BandedExercisesExerciseName = BandedExercisesExerciseName(15);
    pub const FRONT_RAISE: BandedExercisesExerciseName = BandedExercisesExerciseName(16);
    pub const GLUTE_BRIDGE: BandedExercisesExerciseName = BandedExercisesExerciseName(17);
    pub const HAMSTRING_CURLS: BandedExercisesExerciseName = BandedExercisesExerciseName(18);
    pub const HIGH_PLANK_LEG_LIFTS: BandedExercisesExerciseName = BandedExercisesExerciseName(19);
    pub const HIP_EXTENSION: BandedExercisesExerciseName = BandedExercisesExerciseName(20);
    pub const INTERNAL_ROTATION: BandedExercisesExerciseName = BandedExercisesExerciseName(21);
    pub const JUMPING_JACK: BandedExercisesExerciseName = BandedExercisesExerciseName(22);
    pub const KNEELING_CRUNCH: BandedExercisesExerciseName = BandedExercisesExerciseName(23);
    pub const LATERAL_BAND_WALKS: BandedExercisesExerciseName = BandedExercisesExerciseName(24);
    pub const LATERAL_RAISE: BandedExercisesExerciseName = BandedExercisesExerciseName(25);
    pub const LATPULL: BandedExercisesExerciseName = BandedExercisesExerciseName(26);
    pub const LEG_ABDUCTION: BandedExercisesExerciseName = BandedExercisesExerciseName(27);
    pub const LEG_ADDUCTION: BandedExercisesExerciseName = BandedExercisesExerciseName(28);
    pub const LEG_EXTENSION: BandedExercisesExerciseName = BandedExercisesExerciseName(29);
    pub const LUNGE: BandedExercisesExerciseName = BandedExercisesExerciseName(30);
    pub const PLANK: BandedExercisesExerciseName = BandedExercisesExerciseName(31);
    pub const PULL_APART: BandedExercisesExerciseName = BandedExercisesExerciseName(32);
    pub const PUSH_UPS: BandedExercisesExerciseName = BandedExercisesExerciseName(33);
    pub const REVERSE_CRUNCH: BandedExercisesExerciseName = BandedExercisesExerciseName(34);
    pub const ROW: BandedExercisesExerciseName = BandedExercisesExerciseName(35);
    pub const SHOULDER_ABDUCTION: BandedExercisesExerciseName = BandedExercisesExerciseName(36);
    pub const SHOULDER_EXTENSION: BandedExercisesExerciseName = BandedExercisesExerciseName(37);
    pub const SHOULDER_EXTERNAL_ROTATION: BandedExercisesExerciseName =
        BandedExercisesExerciseName(38);
    pub const SHOULDER_FLEXION_TO_90_DEGREES: BandedExercisesExerciseName =
        BandedExercisesExerciseName(39);
    pub const SIDE_PLANK_LEG_LIFTS: BandedExercisesExerciseName = BandedExercisesExerciseName(40);
    pub const SIDE_RAISE: BandedExercisesExerciseName = BandedExercisesExerciseName(41);
    pub const SQUAT: BandedExercisesExerciseName = BandedExercisesExerciseName(42);
    pub const SQUAT_TO_PRESS: BandedExercisesExerciseName = BandedExercisesExerciseName(43);
    pub const TRICEP_EXTENSION: BandedExercisesExerciseName = BandedExercisesExerciseName(44);
    pub const TRICEP_KICKBACK: BandedExercisesExerciseName = BandedExercisesExerciseName(45);
    pub const UPRIGHT_ROW: BandedExercisesExerciseName = BandedExercisesExerciseName(46);
    pub const WALL_CRAWL_WITH_EXTERNAL_ROTATION: BandedExercisesExerciseName =
        BandedExercisesExerciseName(47);
    pub const LATERAL_RAISE_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(49);
    pub const TRICEPS_EXTENSION_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(50);
    pub const CHEST_FLY_INCLINE_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(51);
    pub const CHEST_FLY_DECLINE_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(52);
    pub const PULL_DOWN_WHEELCHAIR: BandedExercisesExerciseName = BandedExercisesExerciseName(53);
    pub const STRAIGHT_ARM_PULL_DOWN_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(54);
    pub const CURL_WHEELCHAIR: BandedExercisesExerciseName = BandedExercisesExerciseName(55);
    pub const OVERHEAD_CURL_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(56);
    pub const FACE_PULL_WHEELCHAIR: BandedExercisesExerciseName = BandedExercisesExerciseName(57);
    pub const AROUND_THE_WORLD_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(58);
    pub const PULL_APART_WHEELCHAIR: BandedExercisesExerciseName = BandedExercisesExerciseName(59);
    pub const SIDE_CURL_WHEELCHAIR: BandedExercisesExerciseName = BandedExercisesExerciseName(60);
    pub const OVERHEAD_PRESS_WHEELCHAIR: BandedExercisesExerciseName =
        BandedExercisesExerciseName(61);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            1 => Some("ab_twist"),
            2 => Some("back_extension"),
            3 => Some("bicycle_crunch"),
            4 => Some("calf_raises"),
            5 => Some("chest_press"),
            6 => Some("clam_shells"),
            7 => Some("curl"),
            8 => Some("deadbug"),
            9 => Some("deadlift"),
            10 => Some("donkey_kick"),
            11 => Some("external_rotation"),
            12 => Some("external_rotation_at_90_degree_abduction"),
            13 => Some("face_pull"),
            14 => Some("fire_hydrant"),
            15 => Some("fly"),
            16 => Some("front_raise"),
            17 => Some("glute_bridge"),
            18 => Some("hamstring_curls"),
            19 => Some("high_plank_leg_lifts"),
            20 => Some("hip_extension"),
            21 => Some("internal_rotation"),
            22 => Some("jumping_jack"),
            23 => Some("kneeling_crunch"),
            24 => Some("lateral_band_walks"),
            25 => Some("lateral_raise"),
            26 => Some("latpull"),
            27 => Some("leg_abduction"),
            28 => Some("leg_adduction"),
            29 => Some("leg_extension"),
            30 => Some("lunge"),
            31 => Some("plank"),
            32 => Some("pull_apart"),
            33 => Some("push_ups"),
            34 => Some("reverse_crunch"),
            35 => Some("row"),
            36 => Some("shoulder_abduction"),
            37 => Some("shoulder_extension"),
            38 => Some("shoulder_external_rotation"),
            39 => Some("shoulder_flexion_to_90_degrees"),
            40 => Some("side_plank_leg_lifts"),
            41 => Some("side_raise"),
            42 => Some("squat"),
            43 => Some("squat_to_press"),
            44 => Some("tricep_extension"),
            45 => Some("tricep_kickback"),
            46 => Some("upright_row"),
            47 => Some("wall_crawl_with_external_rotation"),
            49 => Some("lateral_raise_wheelchair"),
            50 => Some("triceps_extension_wheelchair"),
            51 => Some("chest_fly_incline_wheelchair"),
            52 => Some("chest_fly_decline_wheelchair"),
            53 => Some("pull_down_wheelchair"),
            54 => Some("straight_arm_pull_down_wheelchair"),
            55 => Some("curl_wheelchair"),
            56 => Some("overhead_curl_wheelchair"),
            57 => Some("face_pull_wheelchair"),
            58 => Some("around_the_world_wheelchair"),
            59 => Some("pull_apart_wheelchair"),
            60 => Some("side_curl_wheelchair"),
            61 => Some("overhead_press_wheelchair"),
            _ => None,
        }
    }
}

impl Default for BandedExercisesExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for BandedExercisesExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "BandedExercisesExerciseName({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for BandedExercisesExerciseName {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("BandedExercisesExerciseName", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u16,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for BandedExercisesExerciseName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
