// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct BikeOutdoorExerciseName(pub u16);

impl BikeOutdoorExerciseName {
    pub const BIKE: BikeOutdoorExerciseName = BikeOutdoorExerciseName(0);
}

impl Default for BikeOutdoorExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for BikeOutdoorExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "bike"),
            _ => write!(f, "BikeOutdoorExerciseName({})", self.0),
        }
    }
}

impl fmt::Debug for BikeOutdoorExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "BikeOutdoorExerciseName::BIKE(0)"),
            _ => write!(f, "BikeOutdoorExerciseName({})", self.0),
        }
    }
}
