// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct BodyLocation(pub u8);

impl BodyLocation {
    pub const LEFT_LEG: BodyLocation = BodyLocation(0);
    pub const LEFT_CALF: BodyLocation = BodyLocation(1);
    pub const LEFT_SHIN: BodyLocation = BodyLocation(2);
    pub const LEFT_HAMSTRING: BodyLocation = BodyLocation(3);
    pub const LEFT_QUAD: BodyLocation = BodyLocation(4);
    pub const LEFT_GLUTE: BodyLocation = BodyLocation(5);
    pub const RIGHT_LEG: BodyLocation = BodyLocation(6);
    pub const RIGHT_CALF: BodyLocation = BodyLocation(7);
    pub const RIGHT_SHIN: BodyLocation = BodyLocation(8);
    pub const RIGHT_HAMSTRING: BodyLocation = BodyLocation(9);
    pub const RIGHT_QUAD: BodyLocation = BodyLocation(10);
    pub const RIGHT_GLUTE: BodyLocation = BodyLocation(11);
    pub const TORSO_BACK: BodyLocation = BodyLocation(12);
    pub const LEFT_LOWER_BACK: BodyLocation = BodyLocation(13);
    pub const LEFT_UPPER_BACK: BodyLocation = BodyLocation(14);
    pub const RIGHT_LOWER_BACK: BodyLocation = BodyLocation(15);
    pub const RIGHT_UPPER_BACK: BodyLocation = BodyLocation(16);
    pub const TORSO_FRONT: BodyLocation = BodyLocation(17);
    pub const LEFT_ABDOMEN: BodyLocation = BodyLocation(18);
    pub const LEFT_CHEST: BodyLocation = BodyLocation(19);
    pub const RIGHT_ABDOMEN: BodyLocation = BodyLocation(20);
    pub const RIGHT_CHEST: BodyLocation = BodyLocation(21);
    pub const LEFT_ARM: BodyLocation = BodyLocation(22);
    pub const LEFT_SHOULDER: BodyLocation = BodyLocation(23);
    pub const LEFT_BICEP: BodyLocation = BodyLocation(24);
    pub const LEFT_TRICEP: BodyLocation = BodyLocation(25);
    /// Left anterior forearm
    pub const LEFT_BRACHIORADIALIS: BodyLocation = BodyLocation(26);
    /// Left posterior forearm
    pub const LEFT_FOREARM_EXTENSORS: BodyLocation = BodyLocation(27);
    pub const RIGHT_ARM: BodyLocation = BodyLocation(28);
    pub const RIGHT_SHOULDER: BodyLocation = BodyLocation(29);
    pub const RIGHT_BICEP: BodyLocation = BodyLocation(30);
    pub const RIGHT_TRICEP: BodyLocation = BodyLocation(31);
    /// Right anterior forearm
    pub const RIGHT_BRACHIORADIALIS: BodyLocation = BodyLocation(32);
    /// Right posterior forearm
    pub const RIGHT_FOREARM_EXTENSORS: BodyLocation = BodyLocation(33);
    pub const NECK: BodyLocation = BodyLocation(34);
    pub const THROAT: BodyLocation = BodyLocation(35);
    pub const WAIST_MID_BACK: BodyLocation = BodyLocation(36);
    pub const WAIST_FRONT: BodyLocation = BodyLocation(37);
    pub const WAIST_LEFT: BodyLocation = BodyLocation(38);
    pub const WAIST_RIGHT: BodyLocation = BodyLocation(39);
}

impl Default for BodyLocation {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for BodyLocation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "left_leg"),
            1 => write!(f, "left_calf"),
            2 => write!(f, "left_shin"),
            3 => write!(f, "left_hamstring"),
            4 => write!(f, "left_quad"),
            5 => write!(f, "left_glute"),
            6 => write!(f, "right_leg"),
            7 => write!(f, "right_calf"),
            8 => write!(f, "right_shin"),
            9 => write!(f, "right_hamstring"),
            10 => write!(f, "right_quad"),
            11 => write!(f, "right_glute"),
            12 => write!(f, "torso_back"),
            13 => write!(f, "left_lower_back"),
            14 => write!(f, "left_upper_back"),
            15 => write!(f, "right_lower_back"),
            16 => write!(f, "right_upper_back"),
            17 => write!(f, "torso_front"),
            18 => write!(f, "left_abdomen"),
            19 => write!(f, "left_chest"),
            20 => write!(f, "right_abdomen"),
            21 => write!(f, "right_chest"),
            22 => write!(f, "left_arm"),
            23 => write!(f, "left_shoulder"),
            24 => write!(f, "left_bicep"),
            25 => write!(f, "left_tricep"),
            26 => write!(f, "left_brachioradialis"),
            27 => write!(f, "left_forearm_extensors"),
            28 => write!(f, "right_arm"),
            29 => write!(f, "right_shoulder"),
            30 => write!(f, "right_bicep"),
            31 => write!(f, "right_tricep"),
            32 => write!(f, "right_brachioradialis"),
            33 => write!(f, "right_forearm_extensors"),
            34 => write!(f, "neck"),
            35 => write!(f, "throat"),
            36 => write!(f, "waist_mid_back"),
            37 => write!(f, "waist_front"),
            38 => write!(f, "waist_left"),
            39 => write!(f, "waist_right"),
            _ => write!(f, "BodyLocation({})", self.0),
        }
    }
}

impl fmt::Debug for BodyLocation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "BodyLocation::LEFT_LEG(0)"),
            1 => write!(f, "BodyLocation::LEFT_CALF(1)"),
            2 => write!(f, "BodyLocation::LEFT_SHIN(2)"),
            3 => write!(f, "BodyLocation::LEFT_HAMSTRING(3)"),
            4 => write!(f, "BodyLocation::LEFT_QUAD(4)"),
            5 => write!(f, "BodyLocation::LEFT_GLUTE(5)"),
            6 => write!(f, "BodyLocation::RIGHT_LEG(6)"),
            7 => write!(f, "BodyLocation::RIGHT_CALF(7)"),
            8 => write!(f, "BodyLocation::RIGHT_SHIN(8)"),
            9 => write!(f, "BodyLocation::RIGHT_HAMSTRING(9)"),
            10 => write!(f, "BodyLocation::RIGHT_QUAD(10)"),
            11 => write!(f, "BodyLocation::RIGHT_GLUTE(11)"),
            12 => write!(f, "BodyLocation::TORSO_BACK(12)"),
            13 => write!(f, "BodyLocation::LEFT_LOWER_BACK(13)"),
            14 => write!(f, "BodyLocation::LEFT_UPPER_BACK(14)"),
            15 => write!(f, "BodyLocation::RIGHT_LOWER_BACK(15)"),
            16 => write!(f, "BodyLocation::RIGHT_UPPER_BACK(16)"),
            17 => write!(f, "BodyLocation::TORSO_FRONT(17)"),
            18 => write!(f, "BodyLocation::LEFT_ABDOMEN(18)"),
            19 => write!(f, "BodyLocation::LEFT_CHEST(19)"),
            20 => write!(f, "BodyLocation::RIGHT_ABDOMEN(20)"),
            21 => write!(f, "BodyLocation::RIGHT_CHEST(21)"),
            22 => write!(f, "BodyLocation::LEFT_ARM(22)"),
            23 => write!(f, "BodyLocation::LEFT_SHOULDER(23)"),
            24 => write!(f, "BodyLocation::LEFT_BICEP(24)"),
            25 => write!(f, "BodyLocation::LEFT_TRICEP(25)"),
            26 => write!(f, "BodyLocation::LEFT_BRACHIORADIALIS(26)"),
            27 => write!(f, "BodyLocation::LEFT_FOREARM_EXTENSORS(27)"),
            28 => write!(f, "BodyLocation::RIGHT_ARM(28)"),
            29 => write!(f, "BodyLocation::RIGHT_SHOULDER(29)"),
            30 => write!(f, "BodyLocation::RIGHT_BICEP(30)"),
            31 => write!(f, "BodyLocation::RIGHT_TRICEP(31)"),
            32 => write!(f, "BodyLocation::RIGHT_BRACHIORADIALIS(32)"),
            33 => write!(f, "BodyLocation::RIGHT_FOREARM_EXTENSORS(33)"),
            34 => write!(f, "BodyLocation::NECK(34)"),
            35 => write!(f, "BodyLocation::THROAT(35)"),
            36 => write!(f, "BodyLocation::WAIST_MID_BACK(36)"),
            37 => write!(f, "BodyLocation::WAIST_FRONT(37)"),
            38 => write!(f, "BodyLocation::WAIST_LEFT(38)"),
            39 => write!(f, "BodyLocation::WAIST_RIGHT(39)"),
            _ => write!(f, "BodyLocation({})", self.0),
        }
    }
}
