// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Bp Status type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct BpStatus(pub u8);

impl BpStatus {
    pub const NO_ERROR: BpStatus = BpStatus(0);
    pub const ERROR_INCOMPLETE_DATA: BpStatus = BpStatus(1);
    pub const ERROR_NO_MEASUREMENT: BpStatus = BpStatus(2);
    pub const ERROR_DATA_OUT_OF_RANGE: BpStatus = BpStatus(3);
    pub const ERROR_IRREGULAR_HEART_RATE: BpStatus = BpStatus(4);
}

impl Default for BpStatus {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for BpStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "no_error"),
            1 => write!(f, "error_incomplete_data"),
            2 => write!(f, "error_no_measurement"),
            3 => write!(f, "error_data_out_of_range"),
            4 => write!(f, "error_irregular_heart_rate"),
            _ => write!(f, "BpStatus({})", self.0),
        }
    }
}
