// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Camera Event Type type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CameraEventType(pub u8);

impl CameraEventType {
    /// Start of video recording
    pub const VIDEO_START: CameraEventType = CameraEventType(0);
    /// Mark of video file split (end of one file, beginning of the other)
    pub const VIDEO_SPLIT: CameraEventType = CameraEventType(1);
    /// End of video recording
    pub const VIDEO_END: CameraEventType = CameraEventType(2);
    /// Still photo taken
    pub const PHOTO_TAKEN: CameraEventType = CameraEventType(3);
    pub const VIDEO_SECOND_STREAM_START: CameraEventType = CameraEventType(4);
    pub const VIDEO_SECOND_STREAM_SPLIT: CameraEventType = CameraEventType(5);
    pub const VIDEO_SECOND_STREAM_END: CameraEventType = CameraEventType(6);
    /// Mark of video file split start
    pub const VIDEO_SPLIT_START: CameraEventType = CameraEventType(7);
    pub const VIDEO_SECOND_STREAM_SPLIT_START: CameraEventType = CameraEventType(8);
    /// Mark when a video recording has been paused
    pub const VIDEO_PAUSE: CameraEventType = CameraEventType(11);
    pub const VIDEO_SECOND_STREAM_PAUSE: CameraEventType = CameraEventType(12);
    /// Mark when a video recording has been resumed
    pub const VIDEO_RESUME: CameraEventType = CameraEventType(13);
    pub const VIDEO_SECOND_STREAM_RESUME: CameraEventType = CameraEventType(14);
}

impl Default for CameraEventType {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for CameraEventType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "video_start"),
            1 => write!(f, "video_split"),
            2 => write!(f, "video_end"),
            3 => write!(f, "photo_taken"),
            4 => write!(f, "video_second_stream_start"),
            5 => write!(f, "video_second_stream_split"),
            6 => write!(f, "video_second_stream_end"),
            7 => write!(f, "video_split_start"),
            8 => write!(f, "video_second_stream_split_start"),
            11 => write!(f, "video_pause"),
            12 => write!(f, "video_second_stream_pause"),
            13 => write!(f, "video_resume"),
            14 => write!(f, "video_second_stream_resume"),
            _ => write!(f, "CameraEventType({})", self.0),
        }
    }
}
