// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Ccr Setpoint Switch Mode type.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct CcrSetpointSwitchMode(pub u8);

impl CcrSetpointSwitchMode {
    /// User switches setpoints manually
    pub const MANUAL: CcrSetpointSwitchMode = CcrSetpointSwitchMode(0);
    /// Switch automatically based on depth
    pub const AUTOMATIC: CcrSetpointSwitchMode = CcrSetpointSwitchMode(1);
}

impl Default for CcrSetpointSwitchMode {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for CcrSetpointSwitchMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "manual"),
            1 => write!(f, "automatic"),
            _ => write!(f, "CcrSetpointSwitchMode({})", self.0),
        }
    }
}

impl fmt::Debug for CcrSetpointSwitchMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "CcrSetpointSwitchMode::MANUAL(0)"),
            1 => write!(f, "CcrSetpointSwitchMode::AUTOMATIC(1)"),
            _ => write!(f, "CcrSetpointSwitchMode({})", self.0),
        }
    }
}
