// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Climb Pro Event type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ClimbProEvent(pub u8);

impl ClimbProEvent {
    pub const APPROACH: ClimbProEvent = ClimbProEvent(0);
    pub const START: ClimbProEvent = ClimbProEvent(1);
    pub const COMPLETE: ClimbProEvent = ClimbProEvent(2);
}

impl Default for ClimbProEvent {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for ClimbProEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "approach"),
            1 => write!(f, "start"),
            2 => write!(f, "complete"),
            _ => write!(f, "ClimbProEvent({})", self.0),
        }
    }
}
