// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Climb Grading Scale type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ClimbGradingScale(pub u8);

impl ClimbGradingScale {
    pub const YDS: ClimbGradingScale = ClimbGradingScale(0);
    pub const UIAA: ClimbGradingScale = ClimbGradingScale(1);
    pub const FRENCH: ClimbGradingScale = ClimbGradingScale(2);
    pub const BRITISH_ADJECTIVAL: ClimbGradingScale = ClimbGradingScale(3);
    pub const BRITISH_TECHNICAL: ClimbGradingScale = ClimbGradingScale(4);
    pub const EWBANK: ClimbGradingScale = ClimbGradingScale(5);
    pub const BRAZILIAN: ClimbGradingScale = ClimbGradingScale(6);
    pub const SAXON: ClimbGradingScale = ClimbGradingScale(7);
    pub const VERMIN: ClimbGradingScale = ClimbGradingScale(8);
    pub const FONT: ClimbGradingScale = ClimbGradingScale(9);
    pub const DANKYU: ClimbGradingScale = ClimbGradingScale(10);
    /// YDS Plus Minus Grading Scale
    pub const YDS_PM: ClimbGradingScale = ClimbGradingScale(11);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("yds"),
            1 => Some("uiaa"),
            2 => Some("french"),
            3 => Some("british_adjectival"),
            4 => Some("british_technical"),
            5 => Some("ewbank"),
            6 => Some("brazilian"),
            7 => Some("saxon"),
            8 => Some("vermin"),
            9 => Some("font"),
            10 => Some("dankyu"),
            11 => Some("yds_pm"),
            _ => None,
        }
    }
}

impl Default for ClimbGradingScale {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for ClimbGradingScale {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "ClimbGradingScale({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for ClimbGradingScale {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("ClimbGradingScale", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for ClimbGradingScale {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
