// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Core Exercise Name type.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct CoreExerciseName(pub u16);

impl CoreExerciseName {
    pub const ABS_JABS: CoreExerciseName = CoreExerciseName(0);
    pub const WEIGHTED_ABS_JABS: CoreExerciseName = CoreExerciseName(1);
    pub const ALTERNATING_PLATE_REACH: CoreExerciseName = CoreExerciseName(2);
    pub const BARBELL_ROLLOUT: CoreExerciseName = CoreExerciseName(3);
    pub const WEIGHTED_BARBELL_ROLLOUT: CoreExerciseName = CoreExerciseName(4);
    pub const BODY_BAR_OBLIQUE_TWIST: CoreExerciseName = CoreExerciseName(5);
    pub const CABLE_CORE_PRESS: CoreExerciseName = CoreExerciseName(6);
    pub const CABLE_SIDE_BEND: CoreExerciseName = CoreExerciseName(7);
    pub const SIDE_BEND: CoreExerciseName = CoreExerciseName(8);
    pub const WEIGHTED_SIDE_BEND: CoreExerciseName = CoreExerciseName(9);
    pub const CRESCENT_CIRCLE: CoreExerciseName = CoreExerciseName(10);
    pub const WEIGHTED_CRESCENT_CIRCLE: CoreExerciseName = CoreExerciseName(11);
    pub const CYCLING_RUSSIAN_TWIST: CoreExerciseName = CoreExerciseName(12);
    pub const WEIGHTED_CYCLING_RUSSIAN_TWIST: CoreExerciseName = CoreExerciseName(13);
    pub const ELEVATED_FEET_RUSSIAN_TWIST: CoreExerciseName = CoreExerciseName(14);
    pub const WEIGHTED_ELEVATED_FEET_RUSSIAN_TWIST: CoreExerciseName = CoreExerciseName(15);
    pub const HALF_TURKISH_GET_UP: CoreExerciseName = CoreExerciseName(16);
    pub const KETTLEBELL_WINDMILL: CoreExerciseName = CoreExerciseName(17);
    pub const KNEELING_AB_WHEEL: CoreExerciseName = CoreExerciseName(18);
    pub const WEIGHTED_KNEELING_AB_WHEEL: CoreExerciseName = CoreExerciseName(19);
    pub const MODIFIED_FRONT_LEVER: CoreExerciseName = CoreExerciseName(20);
    pub const OPEN_KNEE_TUCKS: CoreExerciseName = CoreExerciseName(21);
    pub const WEIGHTED_OPEN_KNEE_TUCKS: CoreExerciseName = CoreExerciseName(22);
    pub const SIDE_ABS_LEG_LIFT: CoreExerciseName = CoreExerciseName(23);
    pub const WEIGHTED_SIDE_ABS_LEG_LIFT: CoreExerciseName = CoreExerciseName(24);
    pub const SWISS_BALL_JACKKNIFE: CoreExerciseName = CoreExerciseName(25);
    pub const WEIGHTED_SWISS_BALL_JACKKNIFE: CoreExerciseName = CoreExerciseName(26);
    pub const SWISS_BALL_PIKE: CoreExerciseName = CoreExerciseName(27);
    pub const WEIGHTED_SWISS_BALL_PIKE: CoreExerciseName = CoreExerciseName(28);
    pub const SWISS_BALL_ROLLOUT: CoreExerciseName = CoreExerciseName(29);
    pub const WEIGHTED_SWISS_BALL_ROLLOUT: CoreExerciseName = CoreExerciseName(30);
    pub const TRIANGLE_HIP_PRESS: CoreExerciseName = CoreExerciseName(31);
    pub const WEIGHTED_TRIANGLE_HIP_PRESS: CoreExerciseName = CoreExerciseName(32);
    pub const TRX_SUSPENDED_JACKKNIFE: CoreExerciseName = CoreExerciseName(33);
    pub const WEIGHTED_TRX_SUSPENDED_JACKKNIFE: CoreExerciseName = CoreExerciseName(34);
    pub const U_BOAT: CoreExerciseName = CoreExerciseName(35);
    pub const WEIGHTED_U_BOAT: CoreExerciseName = CoreExerciseName(36);
    pub const WINDMILL_SWITCHES: CoreExerciseName = CoreExerciseName(37);
    pub const WEIGHTED_WINDMILL_SWITCHES: CoreExerciseName = CoreExerciseName(38);
    pub const ALTERNATING_SLIDE_OUT: CoreExerciseName = CoreExerciseName(39);
    pub const WEIGHTED_ALTERNATING_SLIDE_OUT: CoreExerciseName = CoreExerciseName(40);
    pub const GHD_BACK_EXTENSIONS: CoreExerciseName = CoreExerciseName(41);
    pub const WEIGHTED_GHD_BACK_EXTENSIONS: CoreExerciseName = CoreExerciseName(42);
    pub const OVERHEAD_WALK: CoreExerciseName = CoreExerciseName(43);
    pub const INCHWORM: CoreExerciseName = CoreExerciseName(44);
    pub const WEIGHTED_MODIFIED_FRONT_LEVER: CoreExerciseName = CoreExerciseName(45);
    pub const RUSSIAN_TWIST: CoreExerciseName = CoreExerciseName(46);
    /// Deprecated do not use
    pub const ABDOMINAL_LEG_ROTATIONS: CoreExerciseName = CoreExerciseName(47);
    pub const ARM_AND_LEG_EXTENSION_ON_KNEES: CoreExerciseName = CoreExerciseName(48);
    pub const BICYCLE: CoreExerciseName = CoreExerciseName(49);
    pub const BICEP_CURL_WITH_LEG_EXTENSION: CoreExerciseName = CoreExerciseName(50);
    pub const CAT_COW: CoreExerciseName = CoreExerciseName(51);
    pub const CORKSCREW: CoreExerciseName = CoreExerciseName(52);
    pub const CRISS_CROSS: CoreExerciseName = CoreExerciseName(53);
    /// Deprecated do not use
    pub const CRISS_CROSS_WITH_BALL: CoreExerciseName = CoreExerciseName(54);
    pub const DOUBLE_LEG_STRETCH: CoreExerciseName = CoreExerciseName(55);
    pub const KNEE_FOLDS: CoreExerciseName = CoreExerciseName(56);
    pub const LOWER_LIFT: CoreExerciseName = CoreExerciseName(57);
    pub const NECK_PULL: CoreExerciseName = CoreExerciseName(58);
    pub const PELVIC_CLOCKS: CoreExerciseName = CoreExerciseName(59);
    pub const ROLL_OVER: CoreExerciseName = CoreExerciseName(60);
    pub const ROLL_UP: CoreExerciseName = CoreExerciseName(61);
    pub const ROLLING: CoreExerciseName = CoreExerciseName(62);
    pub const ROWING_1: CoreExerciseName = CoreExerciseName(63);
    pub const ROWING_2: CoreExerciseName = CoreExerciseName(64);
    pub const SCISSORS: CoreExerciseName = CoreExerciseName(65);
    pub const SINGLE_LEG_CIRCLES: CoreExerciseName = CoreExerciseName(66);
    pub const SINGLE_LEG_STRETCH: CoreExerciseName = CoreExerciseName(67);
    /// Deprecated do not use
    pub const SNAKE_TWIST_1_AND_2: CoreExerciseName = CoreExerciseName(68);
    pub const SWAN: CoreExerciseName = CoreExerciseName(69);
    pub const SWIMMING: CoreExerciseName = CoreExerciseName(70);
    pub const TEASER: CoreExerciseName = CoreExerciseName(71);
    pub const THE_HUNDRED: CoreExerciseName = CoreExerciseName(72);
    pub const BICEP_CURL_WITH_LEG_EXTENSION_WITH_WEIGHTS: CoreExerciseName = CoreExerciseName(73);
    pub const HANGING_L_SIT: CoreExerciseName = CoreExerciseName(75);
    pub const LOWER_LIFT_WITH_WEIGHTS: CoreExerciseName = CoreExerciseName(77);
    pub const RING_L_SIT: CoreExerciseName = CoreExerciseName(79);
    pub const ROWING_1_WITH_WEIGHTS: CoreExerciseName = CoreExerciseName(80);
    pub const ROWING_2_WITH_WEIGHTS: CoreExerciseName = CoreExerciseName(81);
    pub const SCISSORS_WITH_WEIGHTS: CoreExerciseName = CoreExerciseName(82);
    pub const SINGLE_LEG_STRETCH_WITH_WEIGHTS: CoreExerciseName = CoreExerciseName(83);
    pub const TOES_TO_ELBOWS: CoreExerciseName = CoreExerciseName(84);
    pub const WEIGHTED_CRISS_CROSS: CoreExerciseName = CoreExerciseName(85);
    pub const WEIGHTED_DOUBLE_LEG_STRETCH: CoreExerciseName = CoreExerciseName(86);
    pub const WEIGHTED_THE_HUNDRED: CoreExerciseName = CoreExerciseName(87);
    pub const L_SIT: CoreExerciseName = CoreExerciseName(88);
    pub const TURKISH_GET_UP: CoreExerciseName = CoreExerciseName(89);
    pub const WEIGHTED_RING_L_SIT: CoreExerciseName = CoreExerciseName(90);
    pub const WEIGHTED_HANGING_L_SIT: CoreExerciseName = CoreExerciseName(91);
    pub const WEIGHTED_L_SIT: CoreExerciseName = CoreExerciseName(92);
    pub const SIDE_BEND_LOW_WHEELCHAIR: CoreExerciseName = CoreExerciseName(93);
    pub const SIDE_BEND_MID_WHEELCHAIR: CoreExerciseName = CoreExerciseName(94);
    pub const SIDE_BEND_HIGH_WHEELCHAIR: CoreExerciseName = CoreExerciseName(95);
    pub const SEATED_SIDE_BEND: CoreExerciseName = CoreExerciseName(96);
}

impl Default for CoreExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for CoreExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "abs_jabs"),
            1 => write!(f, "weighted_abs_jabs"),
            2 => write!(f, "alternating_plate_reach"),
            3 => write!(f, "barbell_rollout"),
            4 => write!(f, "weighted_barbell_rollout"),
            5 => write!(f, "body_bar_oblique_twist"),
            6 => write!(f, "cable_core_press"),
            7 => write!(f, "cable_side_bend"),
            8 => write!(f, "side_bend"),
            9 => write!(f, "weighted_side_bend"),
            10 => write!(f, "crescent_circle"),
            11 => write!(f, "weighted_crescent_circle"),
            12 => write!(f, "cycling_russian_twist"),
            13 => write!(f, "weighted_cycling_russian_twist"),
            14 => write!(f, "elevated_feet_russian_twist"),
            15 => write!(f, "weighted_elevated_feet_russian_twist"),
            16 => write!(f, "half_turkish_get_up"),
            17 => write!(f, "kettlebell_windmill"),
            18 => write!(f, "kneeling_ab_wheel"),
            19 => write!(f, "weighted_kneeling_ab_wheel"),
            20 => write!(f, "modified_front_lever"),
            21 => write!(f, "open_knee_tucks"),
            22 => write!(f, "weighted_open_knee_tucks"),
            23 => write!(f, "side_abs_leg_lift"),
            24 => write!(f, "weighted_side_abs_leg_lift"),
            25 => write!(f, "swiss_ball_jackknife"),
            26 => write!(f, "weighted_swiss_ball_jackknife"),
            27 => write!(f, "swiss_ball_pike"),
            28 => write!(f, "weighted_swiss_ball_pike"),
            29 => write!(f, "swiss_ball_rollout"),
            30 => write!(f, "weighted_swiss_ball_rollout"),
            31 => write!(f, "triangle_hip_press"),
            32 => write!(f, "weighted_triangle_hip_press"),
            33 => write!(f, "trx_suspended_jackknife"),
            34 => write!(f, "weighted_trx_suspended_jackknife"),
            35 => write!(f, "u_boat"),
            36 => write!(f, "weighted_u_boat"),
            37 => write!(f, "windmill_switches"),
            38 => write!(f, "weighted_windmill_switches"),
            39 => write!(f, "alternating_slide_out"),
            40 => write!(f, "weighted_alternating_slide_out"),
            41 => write!(f, "ghd_back_extensions"),
            42 => write!(f, "weighted_ghd_back_extensions"),
            43 => write!(f, "overhead_walk"),
            44 => write!(f, "inchworm"),
            45 => write!(f, "weighted_modified_front_lever"),
            46 => write!(f, "russian_twist"),
            47 => write!(f, "abdominal_leg_rotations"),
            48 => write!(f, "arm_and_leg_extension_on_knees"),
            49 => write!(f, "bicycle"),
            50 => write!(f, "bicep_curl_with_leg_extension"),
            51 => write!(f, "cat_cow"),
            52 => write!(f, "corkscrew"),
            53 => write!(f, "criss_cross"),
            54 => write!(f, "criss_cross_with_ball"),
            55 => write!(f, "double_leg_stretch"),
            56 => write!(f, "knee_folds"),
            57 => write!(f, "lower_lift"),
            58 => write!(f, "neck_pull"),
            59 => write!(f, "pelvic_clocks"),
            60 => write!(f, "roll_over"),
            61 => write!(f, "roll_up"),
            62 => write!(f, "rolling"),
            63 => write!(f, "rowing_1"),
            64 => write!(f, "rowing_2"),
            65 => write!(f, "scissors"),
            66 => write!(f, "single_leg_circles"),
            67 => write!(f, "single_leg_stretch"),
            68 => write!(f, "snake_twist_1_and_2"),
            69 => write!(f, "swan"),
            70 => write!(f, "swimming"),
            71 => write!(f, "teaser"),
            72 => write!(f, "the_hundred"),
            73 => write!(f, "bicep_curl_with_leg_extension_with_weights"),
            75 => write!(f, "hanging_l_sit"),
            77 => write!(f, "lower_lift_with_weights"),
            79 => write!(f, "ring_l_sit"),
            80 => write!(f, "rowing_1_with_weights"),
            81 => write!(f, "rowing_2_with_weights"),
            82 => write!(f, "scissors_with_weights"),
            83 => write!(f, "single_leg_stretch_with_weights"),
            84 => write!(f, "toes_to_elbows"),
            85 => write!(f, "weighted_criss_cross"),
            86 => write!(f, "weighted_double_leg_stretch"),
            87 => write!(f, "weighted_the_hundred"),
            88 => write!(f, "l_sit"),
            89 => write!(f, "turkish_get_up"),
            90 => write!(f, "weighted_ring_l_sit"),
            91 => write!(f, "weighted_hanging_l_sit"),
            92 => write!(f, "weighted_l_sit"),
            93 => write!(f, "side_bend_low_wheelchair"),
            94 => write!(f, "side_bend_mid_wheelchair"),
            95 => write!(f, "side_bend_high_wheelchair"),
            96 => write!(f, "seated_side_bend"),
            _ => write!(f, "CoreExerciseName({})", self.0),
        }
    }
}

impl fmt::Debug for CoreExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "CoreExerciseName::ABS_JABS(0)"),
            1 => write!(f, "CoreExerciseName::WEIGHTED_ABS_JABS(1)"),
            2 => write!(f, "CoreExerciseName::ALTERNATING_PLATE_REACH(2)"),
            3 => write!(f, "CoreExerciseName::BARBELL_ROLLOUT(3)"),
            4 => write!(f, "CoreExerciseName::WEIGHTED_BARBELL_ROLLOUT(4)"),
            5 => write!(f, "CoreExerciseName::BODY_BAR_OBLIQUE_TWIST(5)"),
            6 => write!(f, "CoreExerciseName::CABLE_CORE_PRESS(6)"),
            7 => write!(f, "CoreExerciseName::CABLE_SIDE_BEND(7)"),
            8 => write!(f, "CoreExerciseName::SIDE_BEND(8)"),
            9 => write!(f, "CoreExerciseName::WEIGHTED_SIDE_BEND(9)"),
            10 => write!(f, "CoreExerciseName::CRESCENT_CIRCLE(10)"),
            11 => write!(f, "CoreExerciseName::WEIGHTED_CRESCENT_CIRCLE(11)"),
            12 => write!(f, "CoreExerciseName::CYCLING_RUSSIAN_TWIST(12)"),
            13 => write!(f, "CoreExerciseName::WEIGHTED_CYCLING_RUSSIAN_TWIST(13)"),
            14 => write!(f, "CoreExerciseName::ELEVATED_FEET_RUSSIAN_TWIST(14)"),
            15 => write!(
                f,
                "CoreExerciseName::WEIGHTED_ELEVATED_FEET_RUSSIAN_TWIST(15)"
            ),
            16 => write!(f, "CoreExerciseName::HALF_TURKISH_GET_UP(16)"),
            17 => write!(f, "CoreExerciseName::KETTLEBELL_WINDMILL(17)"),
            18 => write!(f, "CoreExerciseName::KNEELING_AB_WHEEL(18)"),
            19 => write!(f, "CoreExerciseName::WEIGHTED_KNEELING_AB_WHEEL(19)"),
            20 => write!(f, "CoreExerciseName::MODIFIED_FRONT_LEVER(20)"),
            21 => write!(f, "CoreExerciseName::OPEN_KNEE_TUCKS(21)"),
            22 => write!(f, "CoreExerciseName::WEIGHTED_OPEN_KNEE_TUCKS(22)"),
            23 => write!(f, "CoreExerciseName::SIDE_ABS_LEG_LIFT(23)"),
            24 => write!(f, "CoreExerciseName::WEIGHTED_SIDE_ABS_LEG_LIFT(24)"),
            25 => write!(f, "CoreExerciseName::SWISS_BALL_JACKKNIFE(25)"),
            26 => write!(f, "CoreExerciseName::WEIGHTED_SWISS_BALL_JACKKNIFE(26)"),
            27 => write!(f, "CoreExerciseName::SWISS_BALL_PIKE(27)"),
            28 => write!(f, "CoreExerciseName::WEIGHTED_SWISS_BALL_PIKE(28)"),
            29 => write!(f, "CoreExerciseName::SWISS_BALL_ROLLOUT(29)"),
            30 => write!(f, "CoreExerciseName::WEIGHTED_SWISS_BALL_ROLLOUT(30)"),
            31 => write!(f, "CoreExerciseName::TRIANGLE_HIP_PRESS(31)"),
            32 => write!(f, "CoreExerciseName::WEIGHTED_TRIANGLE_HIP_PRESS(32)"),
            33 => write!(f, "CoreExerciseName::TRX_SUSPENDED_JACKKNIFE(33)"),
            34 => write!(f, "CoreExerciseName::WEIGHTED_TRX_SUSPENDED_JACKKNIFE(34)"),
            35 => write!(f, "CoreExerciseName::U_BOAT(35)"),
            36 => write!(f, "CoreExerciseName::WEIGHTED_U_BOAT(36)"),
            37 => write!(f, "CoreExerciseName::WINDMILL_SWITCHES(37)"),
            38 => write!(f, "CoreExerciseName::WEIGHTED_WINDMILL_SWITCHES(38)"),
            39 => write!(f, "CoreExerciseName::ALTERNATING_SLIDE_OUT(39)"),
            40 => write!(f, "CoreExerciseName::WEIGHTED_ALTERNATING_SLIDE_OUT(40)"),
            41 => write!(f, "CoreExerciseName::GHD_BACK_EXTENSIONS(41)"),
            42 => write!(f, "CoreExerciseName::WEIGHTED_GHD_BACK_EXTENSIONS(42)"),
            43 => write!(f, "CoreExerciseName::OVERHEAD_WALK(43)"),
            44 => write!(f, "CoreExerciseName::INCHWORM(44)"),
            45 => write!(f, "CoreExerciseName::WEIGHTED_MODIFIED_FRONT_LEVER(45)"),
            46 => write!(f, "CoreExerciseName::RUSSIAN_TWIST(46)"),
            47 => write!(f, "CoreExerciseName::ABDOMINAL_LEG_ROTATIONS(47)"),
            48 => write!(f, "CoreExerciseName::ARM_AND_LEG_EXTENSION_ON_KNEES(48)"),
            49 => write!(f, "CoreExerciseName::BICYCLE(49)"),
            50 => write!(f, "CoreExerciseName::BICEP_CURL_WITH_LEG_EXTENSION(50)"),
            51 => write!(f, "CoreExerciseName::CAT_COW(51)"),
            52 => write!(f, "CoreExerciseName::CORKSCREW(52)"),
            53 => write!(f, "CoreExerciseName::CRISS_CROSS(53)"),
            54 => write!(f, "CoreExerciseName::CRISS_CROSS_WITH_BALL(54)"),
            55 => write!(f, "CoreExerciseName::DOUBLE_LEG_STRETCH(55)"),
            56 => write!(f, "CoreExerciseName::KNEE_FOLDS(56)"),
            57 => write!(f, "CoreExerciseName::LOWER_LIFT(57)"),
            58 => write!(f, "CoreExerciseName::NECK_PULL(58)"),
            59 => write!(f, "CoreExerciseName::PELVIC_CLOCKS(59)"),
            60 => write!(f, "CoreExerciseName::ROLL_OVER(60)"),
            61 => write!(f, "CoreExerciseName::ROLL_UP(61)"),
            62 => write!(f, "CoreExerciseName::ROLLING(62)"),
            63 => write!(f, "CoreExerciseName::ROWING_1(63)"),
            64 => write!(f, "CoreExerciseName::ROWING_2(64)"),
            65 => write!(f, "CoreExerciseName::SCISSORS(65)"),
            66 => write!(f, "CoreExerciseName::SINGLE_LEG_CIRCLES(66)"),
            67 => write!(f, "CoreExerciseName::SINGLE_LEG_STRETCH(67)"),
            68 => write!(f, "CoreExerciseName::SNAKE_TWIST_1_AND_2(68)"),
            69 => write!(f, "CoreExerciseName::SWAN(69)"),
            70 => write!(f, "CoreExerciseName::SWIMMING(70)"),
            71 => write!(f, "CoreExerciseName::TEASER(71)"),
            72 => write!(f, "CoreExerciseName::THE_HUNDRED(72)"),
            73 => write!(
                f,
                "CoreExerciseName::BICEP_CURL_WITH_LEG_EXTENSION_WITH_WEIGHTS(73)"
            ),
            75 => write!(f, "CoreExerciseName::HANGING_L_SIT(75)"),
            77 => write!(f, "CoreExerciseName::LOWER_LIFT_WITH_WEIGHTS(77)"),
            79 => write!(f, "CoreExerciseName::RING_L_SIT(79)"),
            80 => write!(f, "CoreExerciseName::ROWING_1_WITH_WEIGHTS(80)"),
            81 => write!(f, "CoreExerciseName::ROWING_2_WITH_WEIGHTS(81)"),
            82 => write!(f, "CoreExerciseName::SCISSORS_WITH_WEIGHTS(82)"),
            83 => write!(f, "CoreExerciseName::SINGLE_LEG_STRETCH_WITH_WEIGHTS(83)"),
            84 => write!(f, "CoreExerciseName::TOES_TO_ELBOWS(84)"),
            85 => write!(f, "CoreExerciseName::WEIGHTED_CRISS_CROSS(85)"),
            86 => write!(f, "CoreExerciseName::WEIGHTED_DOUBLE_LEG_STRETCH(86)"),
            87 => write!(f, "CoreExerciseName::WEIGHTED_THE_HUNDRED(87)"),
            88 => write!(f, "CoreExerciseName::L_SIT(88)"),
            89 => write!(f, "CoreExerciseName::TURKISH_GET_UP(89)"),
            90 => write!(f, "CoreExerciseName::WEIGHTED_RING_L_SIT(90)"),
            91 => write!(f, "CoreExerciseName::WEIGHTED_HANGING_L_SIT(91)"),
            92 => write!(f, "CoreExerciseName::WEIGHTED_L_SIT(92)"),
            93 => write!(f, "CoreExerciseName::SIDE_BEND_LOW_WHEELCHAIR(93)"),
            94 => write!(f, "CoreExerciseName::SIDE_BEND_MID_WHEELCHAIR(94)"),
            95 => write!(f, "CoreExerciseName::SIDE_BEND_HIGH_WHEELCHAIR(95)"),
            96 => write!(f, "CoreExerciseName::SEATED_SIDE_BEND(96)"),
            _ => write!(f, "CoreExerciseName({})", self.0),
        }
    }
}
