// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Curl Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CurlExerciseName(pub u16);

impl CurlExerciseName {
    pub const ALTERNATING_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(0);
    pub const ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL: CurlExerciseName =
        CurlExerciseName(1);
    pub const ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(2);
    pub const BARBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(3);
    pub const BARBELL_REVERSE_WRIST_CURL: CurlExerciseName = CurlExerciseName(4);
    pub const BARBELL_WRIST_CURL: CurlExerciseName = CurlExerciseName(5);
    pub const BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL: CurlExerciseName = CurlExerciseName(6);
    pub const BEHIND_THE_BACK_ONE_ARM_CABLE_CURL: CurlExerciseName = CurlExerciseName(7);
    pub const CABLE_BICEPS_CURL: CurlExerciseName = CurlExerciseName(8);
    pub const CABLE_HAMMER_CURL: CurlExerciseName = CurlExerciseName(9);
    pub const CHEATING_BARBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(10);
    pub const CLOSE_GRIP_EZ_BAR_BICEPS_CURL: CurlExerciseName = CurlExerciseName(11);
    pub const CROSS_BODY_DUMBBELL_HAMMER_CURL: CurlExerciseName = CurlExerciseName(12);
    pub const DEAD_HANG_BICEPS_CURL: CurlExerciseName = CurlExerciseName(13);
    pub const DECLINE_HAMMER_CURL: CurlExerciseName = CurlExerciseName(14);
    pub const DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD: CurlExerciseName = CurlExerciseName(15);
    pub const DUMBBELL_HAMMER_CURL: CurlExerciseName = CurlExerciseName(16);
    pub const DUMBBELL_REVERSE_WRIST_CURL: CurlExerciseName = CurlExerciseName(17);
    pub const DUMBBELL_WRIST_CURL: CurlExerciseName = CurlExerciseName(18);
    pub const EZ_BAR_PREACHER_CURL: CurlExerciseName = CurlExerciseName(19);
    pub const FORWARD_BEND_BICEPS_CURL: CurlExerciseName = CurlExerciseName(20);
    pub const HAMMER_CURL_TO_PRESS: CurlExerciseName = CurlExerciseName(21);
    pub const INCLINE_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(22);
    pub const INCLINE_OFFSET_THUMB_DUMBBELL_CURL: CurlExerciseName = CurlExerciseName(23);
    pub const KETTLEBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(24);
    pub const LYING_CONCENTRATION_CABLE_CURL: CurlExerciseName = CurlExerciseName(25);
    pub const ONE_ARM_PREACHER_CURL: CurlExerciseName = CurlExerciseName(26);
    pub const PLATE_PINCH_CURL: CurlExerciseName = CurlExerciseName(27);
    pub const PREACHER_CURL_WITH_CABLE: CurlExerciseName = CurlExerciseName(28);
    pub const REVERSE_EZ_BAR_CURL: CurlExerciseName = CurlExerciseName(29);
    pub const REVERSE_GRIP_WRIST_CURL: CurlExerciseName = CurlExerciseName(30);
    pub const REVERSE_GRIP_BARBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(31);
    pub const SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(32);
    pub const SEATED_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(33);
    pub const SEATED_REVERSE_DUMBBELL_CURL: CurlExerciseName = CurlExerciseName(34);
    pub const SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL: CurlExerciseName = CurlExerciseName(35);
    pub const STANDING_ALTERNATING_DUMBBELL_CURLS: CurlExerciseName = CurlExerciseName(36);
    pub const STANDING_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(37);
    pub const STANDING_EZ_BAR_BICEPS_CURL: CurlExerciseName = CurlExerciseName(38);
    pub const STATIC_CURL: CurlExerciseName = CurlExerciseName(39);
    pub const SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION: CurlExerciseName =
        CurlExerciseName(40);
    pub const SWISS_BALL_EZ_BAR_PREACHER_CURL: CurlExerciseName = CurlExerciseName(41);
    pub const TWISTING_STANDING_DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(42);
    pub const WIDE_GRIP_EZ_BAR_BICEPS_CURL: CurlExerciseName = CurlExerciseName(43);
    pub const ONE_ARM_CONCENTRATION_CURL: CurlExerciseName = CurlExerciseName(44);
    pub const STANDING_ZOTTMAN_BICEPS_CURL: CurlExerciseName = CurlExerciseName(45);
    pub const DUMBBELL_BICEPS_CURL: CurlExerciseName = CurlExerciseName(46);
    pub const DRAG_CURL_WHEELCHAIR: CurlExerciseName = CurlExerciseName(47);
    pub const DUMBBELL_BICEPS_CURL_WHEELCHAIR: CurlExerciseName = CurlExerciseName(48);
    pub const BOTTLE_CURL: CurlExerciseName = CurlExerciseName(49);
    pub const SEATED_BOTTLE_CURL: CurlExerciseName = CurlExerciseName(50);
}

impl Default for CurlExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for CurlExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "alternating_dumbbell_biceps_curl"),
            1 => write!(f, "alternating_dumbbell_biceps_curl_on_swiss_ball"),
            2 => write!(f, "alternating_incline_dumbbell_biceps_curl"),
            3 => write!(f, "barbell_biceps_curl"),
            4 => write!(f, "barbell_reverse_wrist_curl"),
            5 => write!(f, "barbell_wrist_curl"),
            6 => write!(f, "behind_the_back_barbell_reverse_wrist_curl"),
            7 => write!(f, "behind_the_back_one_arm_cable_curl"),
            8 => write!(f, "cable_biceps_curl"),
            9 => write!(f, "cable_hammer_curl"),
            10 => write!(f, "cheating_barbell_biceps_curl"),
            11 => write!(f, "close_grip_ez_bar_biceps_curl"),
            12 => write!(f, "cross_body_dumbbell_hammer_curl"),
            13 => write!(f, "dead_hang_biceps_curl"),
            14 => write!(f, "decline_hammer_curl"),
            15 => write!(f, "dumbbell_biceps_curl_with_static_hold"),
            16 => write!(f, "dumbbell_hammer_curl"),
            17 => write!(f, "dumbbell_reverse_wrist_curl"),
            18 => write!(f, "dumbbell_wrist_curl"),
            19 => write!(f, "ez_bar_preacher_curl"),
            20 => write!(f, "forward_bend_biceps_curl"),
            21 => write!(f, "hammer_curl_to_press"),
            22 => write!(f, "incline_dumbbell_biceps_curl"),
            23 => write!(f, "incline_offset_thumb_dumbbell_curl"),
            24 => write!(f, "kettlebell_biceps_curl"),
            25 => write!(f, "lying_concentration_cable_curl"),
            26 => write!(f, "one_arm_preacher_curl"),
            27 => write!(f, "plate_pinch_curl"),
            28 => write!(f, "preacher_curl_with_cable"),
            29 => write!(f, "reverse_ez_bar_curl"),
            30 => write!(f, "reverse_grip_wrist_curl"),
            31 => write!(f, "reverse_grip_barbell_biceps_curl"),
            32 => write!(f, "seated_alternating_dumbbell_biceps_curl"),
            33 => write!(f, "seated_dumbbell_biceps_curl"),
            34 => write!(f, "seated_reverse_dumbbell_curl"),
            35 => write!(f, "split_stance_offset_pinky_dumbbell_curl"),
            36 => write!(f, "standing_alternating_dumbbell_curls"),
            37 => write!(f, "standing_dumbbell_biceps_curl"),
            38 => write!(f, "standing_ez_bar_biceps_curl"),
            39 => write!(f, "static_curl"),
            40 => write!(f, "swiss_ball_dumbbell_overhead_triceps_extension"),
            41 => write!(f, "swiss_ball_ez_bar_preacher_curl"),
            42 => write!(f, "twisting_standing_dumbbell_biceps_curl"),
            43 => write!(f, "wide_grip_ez_bar_biceps_curl"),
            44 => write!(f, "one_arm_concentration_curl"),
            45 => write!(f, "standing_zottman_biceps_curl"),
            46 => write!(f, "dumbbell_biceps_curl"),
            47 => write!(f, "drag_curl_wheelchair"),
            48 => write!(f, "dumbbell_biceps_curl_wheelchair"),
            49 => write!(f, "bottle_curl"),
            50 => write!(f, "seated_bottle_curl"),
            _ => write!(f, "CurlExerciseName({})", self.0),
        }
    }
}
