// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct DeadliftExerciseName(pub u16);

impl DeadliftExerciseName {
    pub const BARBELL_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(0);
    pub const BARBELL_STRAIGHT_LEG_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(1);
    pub const DUMBBELL_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(2);
    pub const DUMBBELL_SINGLE_LEG_DEADLIFT_TO_ROW: DeadliftExerciseName = DeadliftExerciseName(3);
    pub const DUMBBELL_STRAIGHT_LEG_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(4);
    pub const KETTLEBELL_FLOOR_TO_SHELF: DeadliftExerciseName = DeadliftExerciseName(5);
    pub const ONE_ARM_ONE_LEG_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(6);
    pub const RACK_PULL: DeadliftExerciseName = DeadliftExerciseName(7);
    pub const ROTATIONAL_DUMBBELL_STRAIGHT_LEG_DEADLIFT: DeadliftExerciseName =
        DeadliftExerciseName(8);
    pub const SINGLE_ARM_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(9);
    pub const SINGLE_LEG_BARBELL_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(10);
    pub const SINGLE_LEG_BARBELL_STRAIGHT_LEG_DEADLIFT: DeadliftExerciseName =
        DeadliftExerciseName(11);
    pub const SINGLE_LEG_DEADLIFT_WITH_BARBELL: DeadliftExerciseName = DeadliftExerciseName(12);
    pub const SINGLE_LEG_RDL_CIRCUIT: DeadliftExerciseName = DeadliftExerciseName(13);
    pub const SINGLE_LEG_ROMANIAN_DEADLIFT_WITH_DUMBBELL: DeadliftExerciseName =
        DeadliftExerciseName(14);
    pub const SUMO_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(15);
    pub const SUMO_DEADLIFT_HIGH_PULL: DeadliftExerciseName = DeadliftExerciseName(16);
    pub const TRAP_BAR_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(17);
    pub const WIDE_GRIP_BARBELL_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(18);
    pub const KETTLEBELL_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(20);
    pub const KETTLEBELL_SUMO_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(21);
    pub const ROMANIAN_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(23);
    pub const SINGLE_LEG_ROMANIAN_DEADLIFT_CIRCUIT: DeadliftExerciseName = DeadliftExerciseName(24);
    pub const STRAIGHT_LEG_DEADLIFT: DeadliftExerciseName = DeadliftExerciseName(25);
}

impl Default for DeadliftExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for DeadliftExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "barbell_deadlift"),
            1 => write!(f, "barbell_straight_leg_deadlift"),
            2 => write!(f, "dumbbell_deadlift"),
            3 => write!(f, "dumbbell_single_leg_deadlift_to_row"),
            4 => write!(f, "dumbbell_straight_leg_deadlift"),
            5 => write!(f, "kettlebell_floor_to_shelf"),
            6 => write!(f, "one_arm_one_leg_deadlift"),
            7 => write!(f, "rack_pull"),
            8 => write!(f, "rotational_dumbbell_straight_leg_deadlift"),
            9 => write!(f, "single_arm_deadlift"),
            10 => write!(f, "single_leg_barbell_deadlift"),
            11 => write!(f, "single_leg_barbell_straight_leg_deadlift"),
            12 => write!(f, "single_leg_deadlift_with_barbell"),
            13 => write!(f, "single_leg_rdl_circuit"),
            14 => write!(f, "single_leg_romanian_deadlift_with_dumbbell"),
            15 => write!(f, "sumo_deadlift"),
            16 => write!(f, "sumo_deadlift_high_pull"),
            17 => write!(f, "trap_bar_deadlift"),
            18 => write!(f, "wide_grip_barbell_deadlift"),
            20 => write!(f, "kettlebell_deadlift"),
            21 => write!(f, "kettlebell_sumo_deadlift"),
            23 => write!(f, "romanian_deadlift"),
            24 => write!(f, "single_leg_romanian_deadlift_circuit"),
            25 => write!(f, "straight_leg_deadlift"),
            _ => write!(f, "DeadliftExerciseName({})", self.0),
        }
    }
}

impl fmt::Debug for DeadliftExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "DeadliftExerciseName::BARBELL_DEADLIFT(0)"),
            1 => write!(f, "DeadliftExerciseName::BARBELL_STRAIGHT_LEG_DEADLIFT(1)"),
            2 => write!(f, "DeadliftExerciseName::DUMBBELL_DEADLIFT(2)"),
            3 => write!(
                f,
                "DeadliftExerciseName::DUMBBELL_SINGLE_LEG_DEADLIFT_TO_ROW(3)"
            ),
            4 => write!(f, "DeadliftExerciseName::DUMBBELL_STRAIGHT_LEG_DEADLIFT(4)"),
            5 => write!(f, "DeadliftExerciseName::KETTLEBELL_FLOOR_TO_SHELF(5)"),
            6 => write!(f, "DeadliftExerciseName::ONE_ARM_ONE_LEG_DEADLIFT(6)"),
            7 => write!(f, "DeadliftExerciseName::RACK_PULL(7)"),
            8 => write!(
                f,
                "DeadliftExerciseName::ROTATIONAL_DUMBBELL_STRAIGHT_LEG_DEADLIFT(8)"
            ),
            9 => write!(f, "DeadliftExerciseName::SINGLE_ARM_DEADLIFT(9)"),
            10 => write!(f, "DeadliftExerciseName::SINGLE_LEG_BARBELL_DEADLIFT(10)"),
            11 => write!(
                f,
                "DeadliftExerciseName::SINGLE_LEG_BARBELL_STRAIGHT_LEG_DEADLIFT(11)"
            ),
            12 => write!(
                f,
                "DeadliftExerciseName::SINGLE_LEG_DEADLIFT_WITH_BARBELL(12)"
            ),
            13 => write!(f, "DeadliftExerciseName::SINGLE_LEG_RDL_CIRCUIT(13)"),
            14 => write!(
                f,
                "DeadliftExerciseName::SINGLE_LEG_ROMANIAN_DEADLIFT_WITH_DUMBBELL(14)"
            ),
            15 => write!(f, "DeadliftExerciseName::SUMO_DEADLIFT(15)"),
            16 => write!(f, "DeadliftExerciseName::SUMO_DEADLIFT_HIGH_PULL(16)"),
            17 => write!(f, "DeadliftExerciseName::TRAP_BAR_DEADLIFT(17)"),
            18 => write!(f, "DeadliftExerciseName::WIDE_GRIP_BARBELL_DEADLIFT(18)"),
            20 => write!(f, "DeadliftExerciseName::KETTLEBELL_DEADLIFT(20)"),
            21 => write!(f, "DeadliftExerciseName::KETTLEBELL_SUMO_DEADLIFT(21)"),
            23 => write!(f, "DeadliftExerciseName::ROMANIAN_DEADLIFT(23)"),
            24 => write!(
                f,
                "DeadliftExerciseName::SINGLE_LEG_ROMANIAN_DEADLIFT_CIRCUIT(24)"
            ),
            25 => write!(f, "DeadliftExerciseName::STRAIGHT_LEG_DEADLIFT(25)"),
            _ => write!(f, "DeadliftExerciseName({})", self.0),
        }
    }
}
