// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct DisplayMeasure(pub u8);

impl DisplayMeasure {
    pub const METRIC: DisplayMeasure = DisplayMeasure(0);
    pub const STATUTE: DisplayMeasure = DisplayMeasure(1);
    pub const NAUTICAL: DisplayMeasure = DisplayMeasure(2);
}

impl Default for DisplayMeasure {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for DisplayMeasure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "metric"),
            1 => write!(f, "statute"),
            2 => write!(f, "nautical"),
            _ => write!(f, "DisplayMeasure({})", self.0),
        }
    }
}

impl fmt::Debug for DisplayMeasure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "DisplayMeasure::METRIC(0)"),
            1 => write!(f, "DisplayMeasure::STATUTE(1)"),
            2 => write!(f, "DisplayMeasure::NAUTICAL(2)"),
            _ => write!(f, "DisplayMeasure({})", self.0),
        }
    }
}
