// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Dive Alert type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DiveAlert(pub u8);

impl DiveAlert {
    pub const NDL_REACHED: DiveAlert = DiveAlert(0);
    pub const GAS_SWITCH_PROMPTED: DiveAlert = DiveAlert(1);
    pub const NEAR_SURFACE: DiveAlert = DiveAlert(2);
    pub const APPROACHING_NDL: DiveAlert = DiveAlert(3);
    pub const PO2_WARN: DiveAlert = DiveAlert(4);
    pub const PO2_CRIT_HIGH: DiveAlert = DiveAlert(5);
    pub const PO2_CRIT_LOW: DiveAlert = DiveAlert(6);
    pub const TIME_ALERT: DiveAlert = DiveAlert(7);
    pub const DEPTH_ALERT: DiveAlert = DiveAlert(8);
    pub const DECO_CEILING_BROKEN: DiveAlert = DiveAlert(9);
    pub const DECO_COMPLETE: DiveAlert = DiveAlert(10);
    pub const SAFETY_STOP_BROKEN: DiveAlert = DiveAlert(11);
    pub const SAFETY_STOP_COMPLETE: DiveAlert = DiveAlert(12);
    pub const CNS_WARNING: DiveAlert = DiveAlert(13);
    pub const CNS_CRITICAL: DiveAlert = DiveAlert(14);
    pub const OTU_WARNING: DiveAlert = DiveAlert(15);
    pub const OTU_CRITICAL: DiveAlert = DiveAlert(16);
    pub const ASCENT_CRITICAL: DiveAlert = DiveAlert(17);
    pub const ALERT_DISMISSED_BY_KEY: DiveAlert = DiveAlert(18);
    pub const ALERT_DISMISSED_BY_TIMEOUT: DiveAlert = DiveAlert(19);
    pub const BATTERY_LOW: DiveAlert = DiveAlert(20);
    pub const BATTERY_CRITICAL: DiveAlert = DiveAlert(21);
    pub const SAFETY_STOP_STARTED: DiveAlert = DiveAlert(22);
    pub const APPROACHING_FIRST_DECO_STOP: DiveAlert = DiveAlert(23);
    pub const SETPOINT_SWITCH_AUTO_LOW: DiveAlert = DiveAlert(24);
    pub const SETPOINT_SWITCH_AUTO_HIGH: DiveAlert = DiveAlert(25);
    pub const SETPOINT_SWITCH_MANUAL_LOW: DiveAlert = DiveAlert(26);
    pub const SETPOINT_SWITCH_MANUAL_HIGH: DiveAlert = DiveAlert(27);
    pub const AUTO_SETPOINT_SWITCH_IGNORED: DiveAlert = DiveAlert(28);
    pub const SWITCHED_TO_OPEN_CIRCUIT: DiveAlert = DiveAlert(29);
    pub const SWITCHED_TO_CLOSED_CIRCUIT: DiveAlert = DiveAlert(30);
    pub const TANK_BATTERY_LOW: DiveAlert = DiveAlert(32);
    /// ccr diluent has low po2
    pub const PO2_CCR_DIL_LOW: DiveAlert = DiveAlert(33);
    /// a deco stop has been cleared
    pub const DECO_STOP_CLEARED: DiveAlert = DiveAlert(34);
    /// Target Depth Apnea Alarm triggered
    pub const APNEA_NEUTRAL_BUOYANCY: DiveAlert = DiveAlert(35);
    /// Neutral Buoyance Apnea Alarm triggered
    pub const APNEA_TARGET_DEPTH: DiveAlert = DiveAlert(36);
    /// Surface Apnea Alarm triggered
    pub const APNEA_SURFACE: DiveAlert = DiveAlert(37);
    /// High Speed Apnea Alarm triggered
    pub const APNEA_HIGH_SPEED: DiveAlert = DiveAlert(38);
    /// Low Speed Apnea Alarm triggered
    pub const APNEA_LOW_SPEED: DiveAlert = DiveAlert(39);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("ndl_reached"),
            1 => Some("gas_switch_prompted"),
            2 => Some("near_surface"),
            3 => Some("approaching_ndl"),
            4 => Some("po2_warn"),
            5 => Some("po2_crit_high"),
            6 => Some("po2_crit_low"),
            7 => Some("time_alert"),
            8 => Some("depth_alert"),
            9 => Some("deco_ceiling_broken"),
            10 => Some("deco_complete"),
            11 => Some("safety_stop_broken"),
            12 => Some("safety_stop_complete"),
            13 => Some("cns_warning"),
            14 => Some("cns_critical"),
            15 => Some("otu_warning"),
            16 => Some("otu_critical"),
            17 => Some("ascent_critical"),
            18 => Some("alert_dismissed_by_key"),
            19 => Some("alert_dismissed_by_timeout"),
            20 => Some("battery_low"),
            21 => Some("battery_critical"),
            22 => Some("safety_stop_started"),
            23 => Some("approaching_first_deco_stop"),
            24 => Some("setpoint_switch_auto_low"),
            25 => Some("setpoint_switch_auto_high"),
            26 => Some("setpoint_switch_manual_low"),
            27 => Some("setpoint_switch_manual_high"),
            28 => Some("auto_setpoint_switch_ignored"),
            29 => Some("switched_to_open_circuit"),
            30 => Some("switched_to_closed_circuit"),
            32 => Some("tank_battery_low"),
            33 => Some("po2_ccr_dil_low"),
            34 => Some("deco_stop_cleared"),
            35 => Some("apnea_neutral_buoyancy"),
            36 => Some("apnea_target_depth"),
            37 => Some("apnea_surface"),
            38 => Some("apnea_high_speed"),
            39 => Some("apnea_low_speed"),
            _ => None,
        }
    }
}

impl Default for DiveAlert {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for DiveAlert {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "DiveAlert({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for DiveAlert {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("DiveAlert", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for DiveAlert {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
