// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Ewbank Grading Scale type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EwbankGradingScale(pub u8);

impl EwbankGradingScale {
    /// 4
    pub const _4: EwbankGradingScale = EwbankGradingScale(0);
    /// 5
    pub const _5: EwbankGradingScale = EwbankGradingScale(1);
    /// 6
    pub const _6: EwbankGradingScale = EwbankGradingScale(2);
    /// 7
    pub const _7: EwbankGradingScale = EwbankGradingScale(3);
    /// 8
    pub const _8: EwbankGradingScale = EwbankGradingScale(4);
    /// 9
    pub const _9: EwbankGradingScale = EwbankGradingScale(5);
    /// 10
    pub const _10: EwbankGradingScale = EwbankGradingScale(6);
    /// 11
    pub const _11: EwbankGradingScale = EwbankGradingScale(7);
    /// 12
    pub const _12: EwbankGradingScale = EwbankGradingScale(8);
    /// 13
    pub const _13: EwbankGradingScale = EwbankGradingScale(9);
    /// 14
    pub const _14: EwbankGradingScale = EwbankGradingScale(10);
    /// 15
    pub const _15: EwbankGradingScale = EwbankGradingScale(11);
    /// 16
    pub const _16: EwbankGradingScale = EwbankGradingScale(12);
    /// 17
    pub const _17: EwbankGradingScale = EwbankGradingScale(13);
    /// 18
    pub const _18: EwbankGradingScale = EwbankGradingScale(14);
    /// 19
    pub const _19: EwbankGradingScale = EwbankGradingScale(15);
    /// 20
    pub const _20: EwbankGradingScale = EwbankGradingScale(16);
    /// 21
    pub const _21: EwbankGradingScale = EwbankGradingScale(17);
    /// 22
    pub const _22: EwbankGradingScale = EwbankGradingScale(18);
    /// 23
    pub const _23: EwbankGradingScale = EwbankGradingScale(19);
    /// 24
    pub const _24: EwbankGradingScale = EwbankGradingScale(20);
    /// 25
    pub const _25: EwbankGradingScale = EwbankGradingScale(21);
    /// 26
    pub const _26: EwbankGradingScale = EwbankGradingScale(22);
    /// 27
    pub const _27: EwbankGradingScale = EwbankGradingScale(23);
    /// 28
    pub const _28: EwbankGradingScale = EwbankGradingScale(24);
    /// 29
    pub const _29: EwbankGradingScale = EwbankGradingScale(25);
    /// 30
    pub const _30: EwbankGradingScale = EwbankGradingScale(26);
    /// 31
    pub const _31: EwbankGradingScale = EwbankGradingScale(27);
    /// 32
    pub const _32: EwbankGradingScale = EwbankGradingScale(28);
    /// 33
    pub const _33: EwbankGradingScale = EwbankGradingScale(29);
    /// 34
    pub const _34: EwbankGradingScale = EwbankGradingScale(30);
    /// 35
    pub const _35: EwbankGradingScale = EwbankGradingScale(31);
    /// 36
    pub const _36: EwbankGradingScale = EwbankGradingScale(32);
    /// 37
    pub const _37: EwbankGradingScale = EwbankGradingScale(33);
    /// 38
    pub const _38: EwbankGradingScale = EwbankGradingScale(34);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("4"),
            1 => Some("5"),
            2 => Some("6"),
            3 => Some("7"),
            4 => Some("8"),
            5 => Some("9"),
            6 => Some("10"),
            7 => Some("11"),
            8 => Some("12"),
            9 => Some("13"),
            10 => Some("14"),
            11 => Some("15"),
            12 => Some("16"),
            13 => Some("17"),
            14 => Some("18"),
            15 => Some("19"),
            16 => Some("20"),
            17 => Some("21"),
            18 => Some("22"),
            19 => Some("23"),
            20 => Some("24"),
            21 => Some("25"),
            22 => Some("26"),
            23 => Some("27"),
            24 => Some("28"),
            25 => Some("29"),
            26 => Some("30"),
            27 => Some("31"),
            28 => Some("32"),
            29 => Some("33"),
            30 => Some("34"),
            31 => Some("35"),
            32 => Some("36"),
            33 => Some("37"),
            34 => Some("38"),
            _ => None,
        }
    }
}

impl Default for EwbankGradingScale {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for EwbankGradingScale {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "EwbankGradingScale({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for EwbankGradingScale {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("EwbankGradingScale", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for EwbankGradingScale {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
