// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Exd Display Type type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ExdDisplayType(pub u8);

impl ExdDisplayType {
    pub const NUMERICAL: ExdDisplayType = ExdDisplayType(0);
    pub const SIMPLE: ExdDisplayType = ExdDisplayType(1);
    pub const GRAPH: ExdDisplayType = ExdDisplayType(2);
    pub const BAR: ExdDisplayType = ExdDisplayType(3);
    pub const CIRCLE_GRAPH: ExdDisplayType = ExdDisplayType(4);
    pub const VIRTUAL_PARTNER: ExdDisplayType = ExdDisplayType(5);
    pub const BALANCE: ExdDisplayType = ExdDisplayType(6);
    pub const STRING_LIST: ExdDisplayType = ExdDisplayType(7);
    pub const STRING: ExdDisplayType = ExdDisplayType(8);
    pub const SIMPLE_DYNAMIC_ICON: ExdDisplayType = ExdDisplayType(9);
    pub const GAUGE: ExdDisplayType = ExdDisplayType(10);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("numerical"),
            1 => Some("simple"),
            2 => Some("graph"),
            3 => Some("bar"),
            4 => Some("circle_graph"),
            5 => Some("virtual_partner"),
            6 => Some("balance"),
            7 => Some("string_list"),
            8 => Some("string"),
            9 => Some("simple_dynamic_icon"),
            10 => Some("gauge"),
            _ => None,
        }
    }
}

impl Default for ExdDisplayType {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for ExdDisplayType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "ExdDisplayType({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for ExdDisplayType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("ExdDisplayType", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for ExdDisplayType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
