// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ExdQualifiers(pub u8);

impl ExdQualifiers {
    pub const NO_QUALIFIER: ExdQualifiers = ExdQualifiers(0);
    pub const INSTANTANEOUS: ExdQualifiers = ExdQualifiers(1);
    pub const AVERAGE: ExdQualifiers = ExdQualifiers(2);
    pub const LAP: ExdQualifiers = ExdQualifiers(3);
    pub const MAXIMUM: ExdQualifiers = ExdQualifiers(4);
    pub const MAXIMUM_AVERAGE: ExdQualifiers = ExdQualifiers(5);
    pub const MAXIMUM_LAP: ExdQualifiers = ExdQualifiers(6);
    pub const LAST_LAP: ExdQualifiers = ExdQualifiers(7);
    pub const AVERAGE_LAP: ExdQualifiers = ExdQualifiers(8);
    pub const TO_DESTINATION: ExdQualifiers = ExdQualifiers(9);
    pub const TO_GO: ExdQualifiers = ExdQualifiers(10);
    pub const TO_NEXT: ExdQualifiers = ExdQualifiers(11);
    pub const NEXT_COURSE_POINT: ExdQualifiers = ExdQualifiers(12);
    pub const TOTAL: ExdQualifiers = ExdQualifiers(13);
    pub const THREE_SECOND_AVERAGE: ExdQualifiers = ExdQualifiers(14);
    pub const TEN_SECOND_AVERAGE: ExdQualifiers = ExdQualifiers(15);
    pub const THIRTY_SECOND_AVERAGE: ExdQualifiers = ExdQualifiers(16);
    pub const PERCENT_MAXIMUM: ExdQualifiers = ExdQualifiers(17);
    pub const PERCENT_MAXIMUM_AVERAGE: ExdQualifiers = ExdQualifiers(18);
    pub const LAP_PERCENT_MAXIMUM: ExdQualifiers = ExdQualifiers(19);
    pub const ELAPSED: ExdQualifiers = ExdQualifiers(20);
    pub const SUNRISE: ExdQualifiers = ExdQualifiers(21);
    pub const SUNSET: ExdQualifiers = ExdQualifiers(22);
    pub const COMPARED_TO_VIRTUAL_PARTNER: ExdQualifiers = ExdQualifiers(23);
    pub const MAXIMUM_24H: ExdQualifiers = ExdQualifiers(24);
    pub const MINIMUM_24H: ExdQualifiers = ExdQualifiers(25);
    pub const MINIMUM: ExdQualifiers = ExdQualifiers(26);
    pub const FIRST: ExdQualifiers = ExdQualifiers(27);
    pub const SECOND: ExdQualifiers = ExdQualifiers(28);
    pub const THIRD: ExdQualifiers = ExdQualifiers(29);
    pub const SHIFTER: ExdQualifiers = ExdQualifiers(30);
    pub const LAST_SPORT: ExdQualifiers = ExdQualifiers(31);
    pub const MOVING: ExdQualifiers = ExdQualifiers(32);
    pub const STOPPED: ExdQualifiers = ExdQualifiers(33);
    pub const ESTIMATED_TOTAL: ExdQualifiers = ExdQualifiers(34);
    pub const ZONE_9: ExdQualifiers = ExdQualifiers(242);
    pub const ZONE_8: ExdQualifiers = ExdQualifiers(243);
    pub const ZONE_7: ExdQualifiers = ExdQualifiers(244);
    pub const ZONE_6: ExdQualifiers = ExdQualifiers(245);
    pub const ZONE_5: ExdQualifiers = ExdQualifiers(246);
    pub const ZONE_4: ExdQualifiers = ExdQualifiers(247);
    pub const ZONE_3: ExdQualifiers = ExdQualifiers(248);
    pub const ZONE_2: ExdQualifiers = ExdQualifiers(249);
    pub const ZONE_1: ExdQualifiers = ExdQualifiers(250);
}

impl Default for ExdQualifiers {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for ExdQualifiers {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "no_qualifier"),
            1 => write!(f, "instantaneous"),
            2 => write!(f, "average"),
            3 => write!(f, "lap"),
            4 => write!(f, "maximum"),
            5 => write!(f, "maximum_average"),
            6 => write!(f, "maximum_lap"),
            7 => write!(f, "last_lap"),
            8 => write!(f, "average_lap"),
            9 => write!(f, "to_destination"),
            10 => write!(f, "to_go"),
            11 => write!(f, "to_next"),
            12 => write!(f, "next_course_point"),
            13 => write!(f, "total"),
            14 => write!(f, "three_second_average"),
            15 => write!(f, "ten_second_average"),
            16 => write!(f, "thirty_second_average"),
            17 => write!(f, "percent_maximum"),
            18 => write!(f, "percent_maximum_average"),
            19 => write!(f, "lap_percent_maximum"),
            20 => write!(f, "elapsed"),
            21 => write!(f, "sunrise"),
            22 => write!(f, "sunset"),
            23 => write!(f, "compared_to_virtual_partner"),
            24 => write!(f, "maximum_24h"),
            25 => write!(f, "minimum_24h"),
            26 => write!(f, "minimum"),
            27 => write!(f, "first"),
            28 => write!(f, "second"),
            29 => write!(f, "third"),
            30 => write!(f, "shifter"),
            31 => write!(f, "last_sport"),
            32 => write!(f, "moving"),
            33 => write!(f, "stopped"),
            34 => write!(f, "estimated_total"),
            242 => write!(f, "zone_9"),
            243 => write!(f, "zone_8"),
            244 => write!(f, "zone_7"),
            245 => write!(f, "zone_6"),
            246 => write!(f, "zone_5"),
            247 => write!(f, "zone_4"),
            248 => write!(f, "zone_3"),
            249 => write!(f, "zone_2"),
            250 => write!(f, "zone_1"),
            _ => write!(f, "ExdQualifiers({})", self.0),
        }
    }
}

impl fmt::Debug for ExdQualifiers {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "ExdQualifiers::NO_QUALIFIER(0)"),
            1 => write!(f, "ExdQualifiers::INSTANTANEOUS(1)"),
            2 => write!(f, "ExdQualifiers::AVERAGE(2)"),
            3 => write!(f, "ExdQualifiers::LAP(3)"),
            4 => write!(f, "ExdQualifiers::MAXIMUM(4)"),
            5 => write!(f, "ExdQualifiers::MAXIMUM_AVERAGE(5)"),
            6 => write!(f, "ExdQualifiers::MAXIMUM_LAP(6)"),
            7 => write!(f, "ExdQualifiers::LAST_LAP(7)"),
            8 => write!(f, "ExdQualifiers::AVERAGE_LAP(8)"),
            9 => write!(f, "ExdQualifiers::TO_DESTINATION(9)"),
            10 => write!(f, "ExdQualifiers::TO_GO(10)"),
            11 => write!(f, "ExdQualifiers::TO_NEXT(11)"),
            12 => write!(f, "ExdQualifiers::NEXT_COURSE_POINT(12)"),
            13 => write!(f, "ExdQualifiers::TOTAL(13)"),
            14 => write!(f, "ExdQualifiers::THREE_SECOND_AVERAGE(14)"),
            15 => write!(f, "ExdQualifiers::TEN_SECOND_AVERAGE(15)"),
            16 => write!(f, "ExdQualifiers::THIRTY_SECOND_AVERAGE(16)"),
            17 => write!(f, "ExdQualifiers::PERCENT_MAXIMUM(17)"),
            18 => write!(f, "ExdQualifiers::PERCENT_MAXIMUM_AVERAGE(18)"),
            19 => write!(f, "ExdQualifiers::LAP_PERCENT_MAXIMUM(19)"),
            20 => write!(f, "ExdQualifiers::ELAPSED(20)"),
            21 => write!(f, "ExdQualifiers::SUNRISE(21)"),
            22 => write!(f, "ExdQualifiers::SUNSET(22)"),
            23 => write!(f, "ExdQualifiers::COMPARED_TO_VIRTUAL_PARTNER(23)"),
            24 => write!(f, "ExdQualifiers::MAXIMUM_24H(24)"),
            25 => write!(f, "ExdQualifiers::MINIMUM_24H(25)"),
            26 => write!(f, "ExdQualifiers::MINIMUM(26)"),
            27 => write!(f, "ExdQualifiers::FIRST(27)"),
            28 => write!(f, "ExdQualifiers::SECOND(28)"),
            29 => write!(f, "ExdQualifiers::THIRD(29)"),
            30 => write!(f, "ExdQualifiers::SHIFTER(30)"),
            31 => write!(f, "ExdQualifiers::LAST_SPORT(31)"),
            32 => write!(f, "ExdQualifiers::MOVING(32)"),
            33 => write!(f, "ExdQualifiers::STOPPED(33)"),
            34 => write!(f, "ExdQualifiers::ESTIMATED_TOTAL(34)"),
            242 => write!(f, "ExdQualifiers::ZONE_9(242)"),
            243 => write!(f, "ExdQualifiers::ZONE_8(243)"),
            244 => write!(f, "ExdQualifiers::ZONE_7(244)"),
            245 => write!(f, "ExdQualifiers::ZONE_6(245)"),
            246 => write!(f, "ExdQualifiers::ZONE_5(246)"),
            247 => write!(f, "ExdQualifiers::ZONE_4(247)"),
            248 => write!(f, "ExdQualifiers::ZONE_3(248)"),
            249 => write!(f, "ExdQualifiers::ZONE_2(249)"),
            250 => write!(f, "ExdQualifiers::ZONE_1(250)"),
            _ => write!(f, "ExdQualifiers({})", self.0),
        }
    }
}
