// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Hip Raise Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HipRaiseExerciseName(pub u16);

impl HipRaiseExerciseName {
    pub const BARBELL_HIP_THRUST_ON_FLOOR: HipRaiseExerciseName = HipRaiseExerciseName(0);
    pub const BARBELL_HIP_THRUST_WITH_BENCH: HipRaiseExerciseName = HipRaiseExerciseName(1);
    pub const BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE: HipRaiseExerciseName =
        HipRaiseExerciseName(2);
    pub const WEIGHTED_BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE: HipRaiseExerciseName =
        HipRaiseExerciseName(3);
    pub const BRIDGE_WITH_LEG_EXTENSION: HipRaiseExerciseName = HipRaiseExerciseName(4);
    pub const WEIGHTED_BRIDGE_WITH_LEG_EXTENSION: HipRaiseExerciseName = HipRaiseExerciseName(5);
    pub const CLAM_BRIDGE: HipRaiseExerciseName = HipRaiseExerciseName(6);
    pub const FRONT_KICK_TABLETOP: HipRaiseExerciseName = HipRaiseExerciseName(7);
    pub const WEIGHTED_FRONT_KICK_TABLETOP: HipRaiseExerciseName = HipRaiseExerciseName(8);
    pub const HIP_EXTENSION_AND_CROSS: HipRaiseExerciseName = HipRaiseExerciseName(9);
    pub const WEIGHTED_HIP_EXTENSION_AND_CROSS: HipRaiseExerciseName = HipRaiseExerciseName(10);
    pub const HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(11);
    pub const WEIGHTED_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(12);
    pub const HIP_RAISE_WITH_FEET_ON_SWISS_BALL: HipRaiseExerciseName = HipRaiseExerciseName(13);
    pub const WEIGHTED_HIP_RAISE_WITH_FEET_ON_SWISS_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(14);
    pub const HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: HipRaiseExerciseName = HipRaiseExerciseName(15);
    pub const WEIGHTED_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(16);
    pub const HIP_RAISE_WITH_HEAD_ON_SWISS_BALL: HipRaiseExerciseName = HipRaiseExerciseName(17);
    pub const WEIGHTED_HIP_RAISE_WITH_HEAD_ON_SWISS_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(18);
    pub const HIP_RAISE_WITH_KNEE_SQUEEZE: HipRaiseExerciseName = HipRaiseExerciseName(19);
    pub const WEIGHTED_HIP_RAISE_WITH_KNEE_SQUEEZE: HipRaiseExerciseName = HipRaiseExerciseName(20);
    pub const INCLINE_REAR_LEG_EXTENSION: HipRaiseExerciseName = HipRaiseExerciseName(21);
    pub const WEIGHTED_INCLINE_REAR_LEG_EXTENSION: HipRaiseExerciseName = HipRaiseExerciseName(22);
    pub const KETTLEBELL_SWING: HipRaiseExerciseName = HipRaiseExerciseName(23);
    pub const MARCHING_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(24);
    pub const WEIGHTED_MARCHING_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(25);
    pub const MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(26);
    pub const WEIGHTED_MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(27);
    pub const REVERSE_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(28);
    pub const WEIGHTED_REVERSE_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(29);
    pub const SINGLE_LEG_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(30);
    pub const WEIGHTED_SINGLE_LEG_HIP_RAISE: HipRaiseExerciseName = HipRaiseExerciseName(31);
    pub const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH: HipRaiseExerciseName =
        HipRaiseExerciseName(32);
    pub const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH: HipRaiseExerciseName =
        HipRaiseExerciseName(33);
    pub const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(34);
    pub const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(35);
    pub const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER: HipRaiseExerciseName =
        HipRaiseExerciseName(36);
    pub const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER: HipRaiseExerciseName =
        HipRaiseExerciseName(37);
    pub const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(38);
    pub const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(39);
    pub const SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(40);
    pub const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: HipRaiseExerciseName =
        HipRaiseExerciseName(41);
    pub const WEIGHTED_CLAM_BRIDGE: HipRaiseExerciseName = HipRaiseExerciseName(42);
    pub const SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL: HipRaiseExerciseName =
        HipRaiseExerciseName(43);
    pub const CLAMS: HipRaiseExerciseName = HipRaiseExerciseName(44);
    /// Deprecated do not use
    pub const INNER_THIGH_CIRCLES: HipRaiseExerciseName = HipRaiseExerciseName(45);
    /// Deprecated do not use
    pub const INNER_THIGH_SIDE_LIFT: HipRaiseExerciseName = HipRaiseExerciseName(46);
    pub const LEG_CIRCLES: HipRaiseExerciseName = HipRaiseExerciseName(47);
    pub const LEG_LIFT: HipRaiseExerciseName = HipRaiseExerciseName(48);
    pub const LEG_LIFT_IN_EXTERNAL_ROTATION: HipRaiseExerciseName = HipRaiseExerciseName(49);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("barbell_hip_thrust_on_floor"),
            1 => Some("barbell_hip_thrust_with_bench"),
            2 => Some("bent_knee_swiss_ball_reverse_hip_raise"),
            3 => Some("weighted_bent_knee_swiss_ball_reverse_hip_raise"),
            4 => Some("bridge_with_leg_extension"),
            5 => Some("weighted_bridge_with_leg_extension"),
            6 => Some("clam_bridge"),
            7 => Some("front_kick_tabletop"),
            8 => Some("weighted_front_kick_tabletop"),
            9 => Some("hip_extension_and_cross"),
            10 => Some("weighted_hip_extension_and_cross"),
            11 => Some("hip_raise"),
            12 => Some("weighted_hip_raise"),
            13 => Some("hip_raise_with_feet_on_swiss_ball"),
            14 => Some("weighted_hip_raise_with_feet_on_swiss_ball"),
            15 => Some("hip_raise_with_head_on_bosu_ball"),
            16 => Some("weighted_hip_raise_with_head_on_bosu_ball"),
            17 => Some("hip_raise_with_head_on_swiss_ball"),
            18 => Some("weighted_hip_raise_with_head_on_swiss_ball"),
            19 => Some("hip_raise_with_knee_squeeze"),
            20 => Some("weighted_hip_raise_with_knee_squeeze"),
            21 => Some("incline_rear_leg_extension"),
            22 => Some("weighted_incline_rear_leg_extension"),
            23 => Some("kettlebell_swing"),
            24 => Some("marching_hip_raise"),
            25 => Some("weighted_marching_hip_raise"),
            26 => Some("marching_hip_raise_with_feet_on_a_swiss_ball"),
            27 => Some("weighted_marching_hip_raise_with_feet_on_a_swiss_ball"),
            28 => Some("reverse_hip_raise"),
            29 => Some("weighted_reverse_hip_raise"),
            30 => Some("single_leg_hip_raise"),
            31 => Some("weighted_single_leg_hip_raise"),
            32 => Some("single_leg_hip_raise_with_foot_on_bench"),
            33 => Some("weighted_single_leg_hip_raise_with_foot_on_bench"),
            34 => Some("single_leg_hip_raise_with_foot_on_bosu_ball"),
            35 => Some("weighted_single_leg_hip_raise_with_foot_on_bosu_ball"),
            36 => Some("single_leg_hip_raise_with_foot_on_foam_roller"),
            37 => Some("weighted_single_leg_hip_raise_with_foot_on_foam_roller"),
            38 => Some("single_leg_hip_raise_with_foot_on_medicine_ball"),
            39 => Some("weighted_single_leg_hip_raise_with_foot_on_medicine_ball"),
            40 => Some("single_leg_hip_raise_with_head_on_bosu_ball"),
            41 => Some("weighted_single_leg_hip_raise_with_head_on_bosu_ball"),
            42 => Some("weighted_clam_bridge"),
            43 => Some("single_leg_swiss_ball_hip_raise_and_leg_curl"),
            44 => Some("clams"),
            45 => Some("inner_thigh_circles"),
            46 => Some("inner_thigh_side_lift"),
            47 => Some("leg_circles"),
            48 => Some("leg_lift"),
            49 => Some("leg_lift_in_external_rotation"),
            _ => None,
        }
    }
}

impl Default for HipRaiseExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for HipRaiseExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "HipRaiseExerciseName({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for HipRaiseExerciseName {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("HipRaiseExerciseName", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u16,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for HipRaiseExerciseName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
