// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct HipSwingExerciseName(pub u16);

impl HipSwingExerciseName {
    pub const SINGLE_ARM_KETTLEBELL_SWING: HipSwingExerciseName = HipSwingExerciseName(0);
    pub const SINGLE_ARM_DUMBBELL_SWING: HipSwingExerciseName = HipSwingExerciseName(1);
    pub const STEP_OUT_SWING: HipSwingExerciseName = HipSwingExerciseName(2);
    pub const ONE_ARM_SWING: HipSwingExerciseName = HipSwingExerciseName(3);
}

impl Default for HipSwingExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for HipSwingExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "single_arm_kettlebell_swing"),
            1 => write!(f, "single_arm_dumbbell_swing"),
            2 => write!(f, "step_out_swing"),
            3 => write!(f, "one_arm_swing"),
            _ => write!(f, "HipSwingExerciseName({})", self.0),
        }
    }
}

impl fmt::Debug for HipSwingExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "HipSwingExerciseName::SINGLE_ARM_KETTLEBELL_SWING(0)"),
            1 => write!(f, "HipSwingExerciseName::SINGLE_ARM_DUMBBELL_SWING(1)"),
            2 => write!(f, "HipSwingExerciseName::STEP_OUT_SWING(2)"),
            3 => write!(f, "HipSwingExerciseName::ONE_ARM_SWING(3)"),
            _ => write!(f, "HipSwingExerciseName({})", self.0),
        }
    }
}
