// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Language Bits 0 type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LanguageBits0(pub u8);

impl LanguageBits0 {
    pub const ENGLISH: LanguageBits0 = LanguageBits0(0x01);
    pub const FRENCH: LanguageBits0 = LanguageBits0(0x02);
    pub const ITALIAN: LanguageBits0 = LanguageBits0(0x04);
    pub const GERMAN: LanguageBits0 = LanguageBits0(0x08);
    pub const SPANISH: LanguageBits0 = LanguageBits0(0x10);
    pub const CROATIAN: LanguageBits0 = LanguageBits0(0x20);
    pub const CZECH: LanguageBits0 = LanguageBits0(0x40);
    pub const DANISH: LanguageBits0 = LanguageBits0(0x80);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0x01 => Some("english"),
            0x02 => Some("french"),
            0x04 => Some("italian"),
            0x08 => Some("german"),
            0x10 => Some("spanish"),
            0x20 => Some("croatian"),
            0x40 => Some("czech"),
            0x80 => Some("danish"),
            _ => None,
        }
    }
}

impl Default for LanguageBits0 {
    fn default() -> Self {
        Self(u8::MIN)
    }
}

impl fmt::Display for LanguageBits0 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "LanguageBits0({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for LanguageBits0 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("LanguageBits0", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for LanguageBits0 {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
