// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Lunge Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LungeExerciseName(pub u16);

impl LungeExerciseName {
    pub const OVERHEAD_LUNGE: LungeExerciseName = LungeExerciseName(0);
    pub const LUNGE_MATRIX: LungeExerciseName = LungeExerciseName(1);
    pub const WEIGHTED_LUNGE_MATRIX: LungeExerciseName = LungeExerciseName(2);
    pub const ALTERNATING_BARBELL_FORWARD_LUNGE: LungeExerciseName = LungeExerciseName(3);
    pub const ALTERNATING_DUMBBELL_LUNGE_WITH_REACH: LungeExerciseName = LungeExerciseName(4);
    pub const BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(5);
    pub const BARBELL_BOX_LUNGE: LungeExerciseName = LungeExerciseName(6);
    pub const BARBELL_BULGARIAN_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(7);
    pub const BARBELL_CROSSOVER_LUNGE: LungeExerciseName = LungeExerciseName(8);
    pub const BARBELL_FRONT_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(9);
    pub const BARBELL_LUNGE: LungeExerciseName = LungeExerciseName(10);
    pub const BARBELL_REVERSE_LUNGE: LungeExerciseName = LungeExerciseName(11);
    pub const BARBELL_SIDE_LUNGE: LungeExerciseName = LungeExerciseName(12);
    pub const BARBELL_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(13);
    pub const CORE_CONTROL_REAR_LUNGE: LungeExerciseName = LungeExerciseName(14);
    pub const DIAGONAL_LUNGE: LungeExerciseName = LungeExerciseName(15);
    pub const DROP_LUNGE: LungeExerciseName = LungeExerciseName(16);
    pub const DUMBBELL_BOX_LUNGE: LungeExerciseName = LungeExerciseName(17);
    pub const DUMBBELL_BULGARIAN_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(18);
    pub const DUMBBELL_CROSSOVER_LUNGE: LungeExerciseName = LungeExerciseName(19);
    pub const DUMBBELL_DIAGONAL_LUNGE: LungeExerciseName = LungeExerciseName(20);
    pub const DUMBBELL_LUNGE: LungeExerciseName = LungeExerciseName(21);
    pub const DUMBBELL_LUNGE_AND_ROTATION: LungeExerciseName = LungeExerciseName(22);
    pub const DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(23);
    pub const DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS: LungeExerciseName =
        LungeExerciseName(24);
    pub const DUMBBELL_SIDE_LUNGE: LungeExerciseName = LungeExerciseName(25);
    pub const ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(26);
    pub const FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(27);
    pub const GUNSLINGER_LUNGE: LungeExerciseName = LungeExerciseName(28);
    pub const LAWNMOWER_LUNGE: LungeExerciseName = LungeExerciseName(29);
    pub const LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION: LungeExerciseName = LungeExerciseName(30);
    pub const LOW_SIDE_TO_SIDE_LUNGE: LungeExerciseName = LungeExerciseName(31);
    pub const LUNGE: LungeExerciseName = LungeExerciseName(32);
    pub const WEIGHTED_LUNGE: LungeExerciseName = LungeExerciseName(33);
    pub const LUNGE_WITH_ARM_REACH: LungeExerciseName = LungeExerciseName(34);
    pub const LUNGE_WITH_DIAGONAL_REACH: LungeExerciseName = LungeExerciseName(35);
    pub const LUNGE_WITH_SIDE_BEND: LungeExerciseName = LungeExerciseName(36);
    pub const OFFSET_DUMBBELL_LUNGE: LungeExerciseName = LungeExerciseName(37);
    pub const OFFSET_DUMBBELL_REVERSE_LUNGE: LungeExerciseName = LungeExerciseName(38);
    pub const OVERHEAD_BULGARIAN_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(39);
    pub const OVERHEAD_DUMBBELL_REVERSE_LUNGE: LungeExerciseName = LungeExerciseName(40);
    pub const OVERHEAD_DUMBBELL_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(41);
    pub const OVERHEAD_LUNGE_WITH_ROTATION: LungeExerciseName = LungeExerciseName(42);
    pub const REVERSE_BARBELL_BOX_LUNGE: LungeExerciseName = LungeExerciseName(43);
    pub const REVERSE_BOX_LUNGE: LungeExerciseName = LungeExerciseName(44);
    pub const REVERSE_DUMBBELL_BOX_LUNGE: LungeExerciseName = LungeExerciseName(45);
    pub const REVERSE_DUMBBELL_CROSSOVER_LUNGE: LungeExerciseName = LungeExerciseName(46);
    pub const REVERSE_DUMBBELL_DIAGONAL_LUNGE: LungeExerciseName = LungeExerciseName(47);
    pub const REVERSE_LUNGE_WITH_REACH_BACK: LungeExerciseName = LungeExerciseName(48);
    pub const WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK: LungeExerciseName = LungeExerciseName(49);
    pub const REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH: LungeExerciseName =
        LungeExerciseName(50);
    pub const WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH: LungeExerciseName =
        LungeExerciseName(51);
    pub const REVERSE_SLIDING_BOX_LUNGE: LungeExerciseName = LungeExerciseName(52);
    pub const WEIGHTED_REVERSE_SLIDING_BOX_LUNGE: LungeExerciseName = LungeExerciseName(53);
    pub const REVERSE_SLIDING_LUNGE: LungeExerciseName = LungeExerciseName(54);
    pub const WEIGHTED_REVERSE_SLIDING_LUNGE: LungeExerciseName = LungeExerciseName(55);
    pub const RUNNERS_LUNGE_TO_BALANCE: LungeExerciseName = LungeExerciseName(56);
    pub const WEIGHTED_RUNNERS_LUNGE_TO_BALANCE: LungeExerciseName = LungeExerciseName(57);
    pub const SHIFTING_SIDE_LUNGE: LungeExerciseName = LungeExerciseName(58);
    pub const SIDE_AND_CROSSOVER_LUNGE: LungeExerciseName = LungeExerciseName(59);
    pub const WEIGHTED_SIDE_AND_CROSSOVER_LUNGE: LungeExerciseName = LungeExerciseName(60);
    pub const SIDE_LUNGE: LungeExerciseName = LungeExerciseName(61);
    pub const WEIGHTED_SIDE_LUNGE: LungeExerciseName = LungeExerciseName(62);
    pub const SIDE_LUNGE_AND_PRESS: LungeExerciseName = LungeExerciseName(63);
    pub const SIDE_LUNGE_JUMP_OFF: LungeExerciseName = LungeExerciseName(64);
    pub const SIDE_LUNGE_SWEEP: LungeExerciseName = LungeExerciseName(65);
    pub const WEIGHTED_SIDE_LUNGE_SWEEP: LungeExerciseName = LungeExerciseName(66);
    pub const SIDE_LUNGE_TO_CROSSOVER_TAP: LungeExerciseName = LungeExerciseName(67);
    pub const WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP: LungeExerciseName = LungeExerciseName(68);
    pub const SIDE_TO_SIDE_LUNGE_CHOPS: LungeExerciseName = LungeExerciseName(69);
    pub const WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS: LungeExerciseName = LungeExerciseName(70);
    pub const SIFF_JUMP_LUNGE: LungeExerciseName = LungeExerciseName(71);
    pub const WEIGHTED_SIFF_JUMP_LUNGE: LungeExerciseName = LungeExerciseName(72);
    pub const SINGLE_ARM_REVERSE_LUNGE_AND_PRESS: LungeExerciseName = LungeExerciseName(73);
    pub const SLIDING_LATERAL_LUNGE: LungeExerciseName = LungeExerciseName(74);
    pub const WEIGHTED_SLIDING_LATERAL_LUNGE: LungeExerciseName = LungeExerciseName(75);
    pub const WALKING_BARBELL_LUNGE: LungeExerciseName = LungeExerciseName(76);
    pub const WALKING_DUMBBELL_LUNGE: LungeExerciseName = LungeExerciseName(77);
    pub const WALKING_LUNGE: LungeExerciseName = LungeExerciseName(78);
    pub const WEIGHTED_WALKING_LUNGE: LungeExerciseName = LungeExerciseName(79);
    pub const WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT: LungeExerciseName = LungeExerciseName(80);
    pub const ALTERNATING_DUMBBELL_LUNGE: LungeExerciseName = LungeExerciseName(81);
    pub const DUMBBELL_REVERSE_LUNGE: LungeExerciseName = LungeExerciseName(82);
    pub const OVERHEAD_DUMBBELL_LUNGE: LungeExerciseName = LungeExerciseName(83);
    pub const SCISSOR_POWER_SWITCH: LungeExerciseName = LungeExerciseName(84);
    pub const DUMBBELL_OVERHEAD_WALKING_LUNGE: LungeExerciseName = LungeExerciseName(85);
    pub const CURTSY_LUNGE: LungeExerciseName = LungeExerciseName(86);
    pub const WEIGHTED_CURTSY_LUNGE: LungeExerciseName = LungeExerciseName(87);
    pub const WEIGHTED_SHIFTING_SIDE_LUNGE: LungeExerciseName = LungeExerciseName(88);
    pub const WEIGHTED_SIDE_LUNGE_AND_PRESS: LungeExerciseName = LungeExerciseName(89);
    pub const WEIGHTED_SIDE_LUNGE_JUMP_OFF: LungeExerciseName = LungeExerciseName(90);
}

impl Default for LungeExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for LungeExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "overhead_lunge"),
            1 => write!(f, "lunge_matrix"),
            2 => write!(f, "weighted_lunge_matrix"),
            3 => write!(f, "alternating_barbell_forward_lunge"),
            4 => write!(f, "alternating_dumbbell_lunge_with_reach"),
            5 => write!(f, "back_foot_elevated_dumbbell_split_squat"),
            6 => write!(f, "barbell_box_lunge"),
            7 => write!(f, "barbell_bulgarian_split_squat"),
            8 => write!(f, "barbell_crossover_lunge"),
            9 => write!(f, "barbell_front_split_squat"),
            10 => write!(f, "barbell_lunge"),
            11 => write!(f, "barbell_reverse_lunge"),
            12 => write!(f, "barbell_side_lunge"),
            13 => write!(f, "barbell_split_squat"),
            14 => write!(f, "core_control_rear_lunge"),
            15 => write!(f, "diagonal_lunge"),
            16 => write!(f, "drop_lunge"),
            17 => write!(f, "dumbbell_box_lunge"),
            18 => write!(f, "dumbbell_bulgarian_split_squat"),
            19 => write!(f, "dumbbell_crossover_lunge"),
            20 => write!(f, "dumbbell_diagonal_lunge"),
            21 => write!(f, "dumbbell_lunge"),
            22 => write!(f, "dumbbell_lunge_and_rotation"),
            23 => write!(f, "dumbbell_overhead_bulgarian_split_squat"),
            24 => write!(f, "dumbbell_reverse_lunge_to_high_knee_and_press"),
            25 => write!(f, "dumbbell_side_lunge"),
            26 => write!(f, "elevated_front_foot_barbell_split_squat"),
            27 => write!(f, "front_foot_elevated_dumbbell_split_squat"),
            28 => write!(f, "gunslinger_lunge"),
            29 => write!(f, "lawnmower_lunge"),
            30 => write!(f, "low_lunge_with_isometric_adduction"),
            31 => write!(f, "low_side_to_side_lunge"),
            32 => write!(f, "lunge"),
            33 => write!(f, "weighted_lunge"),
            34 => write!(f, "lunge_with_arm_reach"),
            35 => write!(f, "lunge_with_diagonal_reach"),
            36 => write!(f, "lunge_with_side_bend"),
            37 => write!(f, "offset_dumbbell_lunge"),
            38 => write!(f, "offset_dumbbell_reverse_lunge"),
            39 => write!(f, "overhead_bulgarian_split_squat"),
            40 => write!(f, "overhead_dumbbell_reverse_lunge"),
            41 => write!(f, "overhead_dumbbell_split_squat"),
            42 => write!(f, "overhead_lunge_with_rotation"),
            43 => write!(f, "reverse_barbell_box_lunge"),
            44 => write!(f, "reverse_box_lunge"),
            45 => write!(f, "reverse_dumbbell_box_lunge"),
            46 => write!(f, "reverse_dumbbell_crossover_lunge"),
            47 => write!(f, "reverse_dumbbell_diagonal_lunge"),
            48 => write!(f, "reverse_lunge_with_reach_back"),
            49 => write!(f, "weighted_reverse_lunge_with_reach_back"),
            50 => write!(f, "reverse_lunge_with_twist_and_overhead_reach"),
            51 => write!(f, "weighted_reverse_lunge_with_twist_and_overhead_reach"),
            52 => write!(f, "reverse_sliding_box_lunge"),
            53 => write!(f, "weighted_reverse_sliding_box_lunge"),
            54 => write!(f, "reverse_sliding_lunge"),
            55 => write!(f, "weighted_reverse_sliding_lunge"),
            56 => write!(f, "runners_lunge_to_balance"),
            57 => write!(f, "weighted_runners_lunge_to_balance"),
            58 => write!(f, "shifting_side_lunge"),
            59 => write!(f, "side_and_crossover_lunge"),
            60 => write!(f, "weighted_side_and_crossover_lunge"),
            61 => write!(f, "side_lunge"),
            62 => write!(f, "weighted_side_lunge"),
            63 => write!(f, "side_lunge_and_press"),
            64 => write!(f, "side_lunge_jump_off"),
            65 => write!(f, "side_lunge_sweep"),
            66 => write!(f, "weighted_side_lunge_sweep"),
            67 => write!(f, "side_lunge_to_crossover_tap"),
            68 => write!(f, "weighted_side_lunge_to_crossover_tap"),
            69 => write!(f, "side_to_side_lunge_chops"),
            70 => write!(f, "weighted_side_to_side_lunge_chops"),
            71 => write!(f, "siff_jump_lunge"),
            72 => write!(f, "weighted_siff_jump_lunge"),
            73 => write!(f, "single_arm_reverse_lunge_and_press"),
            74 => write!(f, "sliding_lateral_lunge"),
            75 => write!(f, "weighted_sliding_lateral_lunge"),
            76 => write!(f, "walking_barbell_lunge"),
            77 => write!(f, "walking_dumbbell_lunge"),
            78 => write!(f, "walking_lunge"),
            79 => write!(f, "weighted_walking_lunge"),
            80 => write!(f, "wide_grip_overhead_barbell_split_squat"),
            81 => write!(f, "alternating_dumbbell_lunge"),
            82 => write!(f, "dumbbell_reverse_lunge"),
            83 => write!(f, "overhead_dumbbell_lunge"),
            84 => write!(f, "scissor_power_switch"),
            85 => write!(f, "dumbbell_overhead_walking_lunge"),
            86 => write!(f, "curtsy_lunge"),
            87 => write!(f, "weighted_curtsy_lunge"),
            88 => write!(f, "weighted_shifting_side_lunge"),
            89 => write!(f, "weighted_side_lunge_and_press"),
            90 => write!(f, "weighted_side_lunge_jump_off"),
            _ => write!(f, "LungeExerciseName({})", self.0),
        }
    }
}
