// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Projectile Type type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ProjectileType(pub u8);

impl ProjectileType {
    /// Arrow projectile type
    pub const ARROW: ProjectileType = ProjectileType(0);
    /// Rifle cartridge projectile type
    pub const RIFLE_CARTRIDGE: ProjectileType = ProjectileType(1);
    /// Pistol cartridge projectile type
    pub const PISTOL_CARTRIDGE: ProjectileType = ProjectileType(2);
    /// Shotshell projectile type
    pub const SHOTSHELL: ProjectileType = ProjectileType(3);
    /// Air rifle pellet projectile type
    pub const AIR_RIFLE_PELLET: ProjectileType = ProjectileType(4);
    /// Other projectile type
    pub const OTHER: ProjectileType = ProjectileType(5);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("arrow"),
            1 => Some("rifle_cartridge"),
            2 => Some("pistol_cartridge"),
            3 => Some("shotshell"),
            4 => Some("air_rifle_pellet"),
            5 => Some("other"),
            _ => None,
        }
    }
}

impl Default for ProjectileType {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for ProjectileType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "ProjectileType({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for ProjectileType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("ProjectileType", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for ProjectileType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
