// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Segment Lap Status type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SegmentLapStatus(pub u8);

impl SegmentLapStatus {
    pub const END: SegmentLapStatus = SegmentLapStatus(0);
    pub const FAIL: SegmentLapStatus = SegmentLapStatus(1);
}

impl Default for SegmentLapStatus {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for SegmentLapStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "end"),
            1 => write!(f, "fail"),
            _ => write!(f, "SegmentLapStatus({})", self.0),
        }
    }
}
