// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Shrug Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ShrugExerciseName(pub u16);

impl ShrugExerciseName {
    pub const BARBELL_JUMP_SHRUG: ShrugExerciseName = ShrugExerciseName(0);
    pub const BARBELL_SHRUG: ShrugExerciseName = ShrugExerciseName(1);
    pub const BARBELL_UPRIGHT_ROW: ShrugExerciseName = ShrugExerciseName(2);
    pub const BEHIND_THE_BACK_SMITH_MACHINE_SHRUG: ShrugExerciseName = ShrugExerciseName(3);
    pub const DUMBBELL_JUMP_SHRUG: ShrugExerciseName = ShrugExerciseName(4);
    pub const DUMBBELL_SHRUG: ShrugExerciseName = ShrugExerciseName(5);
    pub const DUMBBELL_UPRIGHT_ROW: ShrugExerciseName = ShrugExerciseName(6);
    pub const INCLINE_DUMBBELL_SHRUG: ShrugExerciseName = ShrugExerciseName(7);
    pub const OVERHEAD_BARBELL_SHRUG: ShrugExerciseName = ShrugExerciseName(8);
    pub const OVERHEAD_DUMBBELL_SHRUG: ShrugExerciseName = ShrugExerciseName(9);
    pub const SCAPTION_AND_SHRUG: ShrugExerciseName = ShrugExerciseName(10);
    pub const SCAPULAR_RETRACTION: ShrugExerciseName = ShrugExerciseName(11);
    pub const SERRATUS_CHAIR_SHRUG: ShrugExerciseName = ShrugExerciseName(12);
    pub const WEIGHTED_SERRATUS_CHAIR_SHRUG: ShrugExerciseName = ShrugExerciseName(13);
    pub const SERRATUS_SHRUG: ShrugExerciseName = ShrugExerciseName(14);
    pub const WEIGHTED_SERRATUS_SHRUG: ShrugExerciseName = ShrugExerciseName(15);
    pub const WIDE_GRIP_JUMP_SHRUG: ShrugExerciseName = ShrugExerciseName(16);
    pub const WIDE_GRIP_BARBELL_SHRUG: ShrugExerciseName = ShrugExerciseName(17);
    pub const BEHIND_THE_BACK_SHRUG: ShrugExerciseName = ShrugExerciseName(18);
    pub const DUMBBELL_SHRUG_WHEELCHAIR: ShrugExerciseName = ShrugExerciseName(19);
    pub const SHRUG_WHEELCHAIR: ShrugExerciseName = ShrugExerciseName(20);
    pub const SHRUG_ARM_DOWN_WHEELCHAIR: ShrugExerciseName = ShrugExerciseName(21);
    pub const SHRUG_ARM_MID_WHEELCHAIR: ShrugExerciseName = ShrugExerciseName(22);
    pub const SHRUG_ARM_UP_WHEELCHAIR: ShrugExerciseName = ShrugExerciseName(23);
    pub const UPRIGHT_ROW: ShrugExerciseName = ShrugExerciseName(24);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("barbell_jump_shrug"),
            1 => Some("barbell_shrug"),
            2 => Some("barbell_upright_row"),
            3 => Some("behind_the_back_smith_machine_shrug"),
            4 => Some("dumbbell_jump_shrug"),
            5 => Some("dumbbell_shrug"),
            6 => Some("dumbbell_upright_row"),
            7 => Some("incline_dumbbell_shrug"),
            8 => Some("overhead_barbell_shrug"),
            9 => Some("overhead_dumbbell_shrug"),
            10 => Some("scaption_and_shrug"),
            11 => Some("scapular_retraction"),
            12 => Some("serratus_chair_shrug"),
            13 => Some("weighted_serratus_chair_shrug"),
            14 => Some("serratus_shrug"),
            15 => Some("weighted_serratus_shrug"),
            16 => Some("wide_grip_jump_shrug"),
            17 => Some("wide_grip_barbell_shrug"),
            18 => Some("behind_the_back_shrug"),
            19 => Some("dumbbell_shrug_wheelchair"),
            20 => Some("shrug_wheelchair"),
            21 => Some("shrug_arm_down_wheelchair"),
            22 => Some("shrug_arm_mid_wheelchair"),
            23 => Some("shrug_arm_up_wheelchair"),
            24 => Some("upright_row"),
            _ => None,
        }
    }
}

impl Default for ShrugExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for ShrugExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "ShrugExerciseName({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for ShrugExerciseName {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("ShrugExerciseName", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u16,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for ShrugExerciseName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
