// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Sit Up Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SitUpExerciseName(pub u16);

impl SitUpExerciseName {
    pub const ALTERNATING_SIT_UP: SitUpExerciseName = SitUpExerciseName(0);
    pub const WEIGHTED_ALTERNATING_SIT_UP: SitUpExerciseName = SitUpExerciseName(1);
    pub const BENT_KNEE_V_UP: SitUpExerciseName = SitUpExerciseName(2);
    pub const WEIGHTED_BENT_KNEE_V_UP: SitUpExerciseName = SitUpExerciseName(3);
    pub const BUTTERFLY_SIT_UP: SitUpExerciseName = SitUpExerciseName(4);
    pub const WEIGHTED_BUTTERFLY_SITUP: SitUpExerciseName = SitUpExerciseName(5);
    pub const CROSS_PUNCH_ROLL_UP: SitUpExerciseName = SitUpExerciseName(6);
    pub const WEIGHTED_CROSS_PUNCH_ROLL_UP: SitUpExerciseName = SitUpExerciseName(7);
    pub const CROSSED_ARMS_SIT_UP: SitUpExerciseName = SitUpExerciseName(8);
    pub const WEIGHTED_CROSSED_ARMS_SIT_UP: SitUpExerciseName = SitUpExerciseName(9);
    pub const GET_UP_SIT_UP: SitUpExerciseName = SitUpExerciseName(10);
    pub const WEIGHTED_GET_UP_SIT_UP: SitUpExerciseName = SitUpExerciseName(11);
    pub const HOVERING_SIT_UP: SitUpExerciseName = SitUpExerciseName(12);
    pub const WEIGHTED_HOVERING_SIT_UP: SitUpExerciseName = SitUpExerciseName(13);
    pub const KETTLEBELL_SIT_UP: SitUpExerciseName = SitUpExerciseName(14);
    pub const MEDICINE_BALL_ALTERNATING_V_UP: SitUpExerciseName = SitUpExerciseName(15);
    pub const MEDICINE_BALL_SIT_UP: SitUpExerciseName = SitUpExerciseName(16);
    pub const MEDICINE_BALL_V_UP: SitUpExerciseName = SitUpExerciseName(17);
    pub const MODIFIED_SIT_UP: SitUpExerciseName = SitUpExerciseName(18);
    pub const NEGATIVE_SIT_UP: SitUpExerciseName = SitUpExerciseName(19);
    pub const ONE_ARM_FULL_SIT_UP: SitUpExerciseName = SitUpExerciseName(20);
    pub const RECLINING_CIRCLE: SitUpExerciseName = SitUpExerciseName(21);
    pub const WEIGHTED_RECLINING_CIRCLE: SitUpExerciseName = SitUpExerciseName(22);
    pub const REVERSE_CURL_UP: SitUpExerciseName = SitUpExerciseName(23);
    pub const WEIGHTED_REVERSE_CURL_UP: SitUpExerciseName = SitUpExerciseName(24);
    pub const SINGLE_LEG_SWISS_BALL_JACKKNIFE: SitUpExerciseName = SitUpExerciseName(25);
    pub const WEIGHTED_SINGLE_LEG_SWISS_BALL_JACKKNIFE: SitUpExerciseName = SitUpExerciseName(26);
    pub const THE_TEASER: SitUpExerciseName = SitUpExerciseName(27);
    pub const THE_TEASER_WEIGHTED: SitUpExerciseName = SitUpExerciseName(28);
    pub const THREE_PART_ROLL_DOWN: SitUpExerciseName = SitUpExerciseName(29);
    pub const WEIGHTED_THREE_PART_ROLL_DOWN: SitUpExerciseName = SitUpExerciseName(30);
    pub const V_UP: SitUpExerciseName = SitUpExerciseName(31);
    pub const WEIGHTED_V_UP: SitUpExerciseName = SitUpExerciseName(32);
    pub const WEIGHTED_RUSSIAN_TWIST_ON_SWISS_BALL: SitUpExerciseName = SitUpExerciseName(33);
    pub const WEIGHTED_SIT_UP: SitUpExerciseName = SitUpExerciseName(34);
    pub const X_ABS: SitUpExerciseName = SitUpExerciseName(35);
    pub const WEIGHTED_X_ABS: SitUpExerciseName = SitUpExerciseName(36);
    pub const SIT_UP: SitUpExerciseName = SitUpExerciseName(37);
    pub const GHD_SIT_UPS: SitUpExerciseName = SitUpExerciseName(38);
    pub const SIT_UP_TURKISH_GET_UP: SitUpExerciseName = SitUpExerciseName(39);
    pub const RUSSIAN_TWIST_ON_SWISS_BALL: SitUpExerciseName = SitUpExerciseName(40);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("alternating_sit_up"),
            1 => Some("weighted_alternating_sit_up"),
            2 => Some("bent_knee_v_up"),
            3 => Some("weighted_bent_knee_v_up"),
            4 => Some("butterfly_sit_up"),
            5 => Some("weighted_butterfly_situp"),
            6 => Some("cross_punch_roll_up"),
            7 => Some("weighted_cross_punch_roll_up"),
            8 => Some("crossed_arms_sit_up"),
            9 => Some("weighted_crossed_arms_sit_up"),
            10 => Some("get_up_sit_up"),
            11 => Some("weighted_get_up_sit_up"),
            12 => Some("hovering_sit_up"),
            13 => Some("weighted_hovering_sit_up"),
            14 => Some("kettlebell_sit_up"),
            15 => Some("medicine_ball_alternating_v_up"),
            16 => Some("medicine_ball_sit_up"),
            17 => Some("medicine_ball_v_up"),
            18 => Some("modified_sit_up"),
            19 => Some("negative_sit_up"),
            20 => Some("one_arm_full_sit_up"),
            21 => Some("reclining_circle"),
            22 => Some("weighted_reclining_circle"),
            23 => Some("reverse_curl_up"),
            24 => Some("weighted_reverse_curl_up"),
            25 => Some("single_leg_swiss_ball_jackknife"),
            26 => Some("weighted_single_leg_swiss_ball_jackknife"),
            27 => Some("the_teaser"),
            28 => Some("the_teaser_weighted"),
            29 => Some("three_part_roll_down"),
            30 => Some("weighted_three_part_roll_down"),
            31 => Some("v_up"),
            32 => Some("weighted_v_up"),
            33 => Some("weighted_russian_twist_on_swiss_ball"),
            34 => Some("weighted_sit_up"),
            35 => Some("x_abs"),
            36 => Some("weighted_x_abs"),
            37 => Some("sit_up"),
            38 => Some("ghd_sit_ups"),
            39 => Some("sit_up_turkish_get_up"),
            40 => Some("russian_twist_on_swiss_ball"),
            _ => None,
        }
    }
}

impl Default for SitUpExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for SitUpExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "SitUpExerciseName({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for SitUpExerciseName {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("SitUpExerciseName", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u16,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for SitUpExerciseName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
