// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Sleep Disruption Severity type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SleepDisruptionSeverity(pub u8);

impl SleepDisruptionSeverity {
    pub const NONE: SleepDisruptionSeverity = SleepDisruptionSeverity(0);
    pub const LOW: SleepDisruptionSeverity = SleepDisruptionSeverity(1);
    pub const MEDIUM: SleepDisruptionSeverity = SleepDisruptionSeverity(2);
    pub const HIGH: SleepDisruptionSeverity = SleepDisruptionSeverity(3);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("none"),
            1 => Some("low"),
            2 => Some("medium"),
            3 => Some("high"),
            _ => None,
        }
    }
}

impl Default for SleepDisruptionSeverity {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for SleepDisruptionSeverity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "SleepDisruptionSeverity({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for SleepDisruptionSeverity {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("SleepDisruptionSeverity", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for SleepDisruptionSeverity {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
