// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use std::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct SportBits2(pub u8);

impl SportBits2 {
    pub const MOUNTAINEERING: SportBits2 = SportBits2(0x01);
    pub const HIKING: SportBits2 = SportBits2(0x02);
    pub const MULTISPORT: SportBits2 = SportBits2(0x04);
    pub const PADDLING: SportBits2 = SportBits2(0x08);
    pub const FLYING: SportBits2 = SportBits2(0x10);
    pub const E_BIKING: SportBits2 = SportBits2(0x20);
    pub const MOTORCYCLING: SportBits2 = SportBits2(0x40);
    pub const BOATING: SportBits2 = SportBits2(0x80);
}

impl Default for SportBits2 {
    fn default() -> Self {
        Self(u8::MIN)
    }
}

impl fmt::Display for SportBits2 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0x01 => write!(f, "mountaineering"),
            0x02 => write!(f, "hiking"),
            0x04 => write!(f, "multisport"),
            0x08 => write!(f, "paddling"),
            0x10 => write!(f, "flying"),
            0x20 => write!(f, "e_biking"),
            0x40 => write!(f, "motorcycling"),
            0x80 => write!(f, "boating"),
            _ => write!(f, "SportBits2({})", self.0),
        }
    }
}

impl fmt::Debug for SportBits2 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0x01 => write!(f, "SportBits2::MOUNTAINEERING(0x01)"),
            0x02 => write!(f, "SportBits2::HIKING(0x02)"),
            0x04 => write!(f, "SportBits2::MULTISPORT(0x04)"),
            0x08 => write!(f, "SportBits2::PADDLING(0x08)"),
            0x10 => write!(f, "SportBits2::FLYING(0x10)"),
            0x20 => write!(f, "SportBits2::E_BIKING(0x20)"),
            0x40 => write!(f, "SportBits2::MOTORCYCLING(0x40)"),
            0x80 => write!(f, "SportBits2::BOATING(0x80)"),
            _ => write!(f, "SportBits2({})", self.0),
        }
    }
}
