// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Squat Exercise Name type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SquatExerciseName(pub u16);

impl SquatExerciseName {
    pub const LEG_PRESS: SquatExerciseName = SquatExerciseName(0);
    pub const BACK_SQUAT_WITH_BODY_BAR: SquatExerciseName = SquatExerciseName(1);
    pub const BACK_SQUATS: SquatExerciseName = SquatExerciseName(2);
    pub const WEIGHTED_BACK_SQUATS: SquatExerciseName = SquatExerciseName(3);
    pub const BALANCING_SQUAT: SquatExerciseName = SquatExerciseName(4);
    pub const WEIGHTED_BALANCING_SQUAT: SquatExerciseName = SquatExerciseName(5);
    pub const BARBELL_BACK_SQUAT: SquatExerciseName = SquatExerciseName(6);
    pub const BARBELL_BOX_SQUAT: SquatExerciseName = SquatExerciseName(7);
    pub const BARBELL_FRONT_SQUAT: SquatExerciseName = SquatExerciseName(8);
    pub const BARBELL_HACK_SQUAT: SquatExerciseName = SquatExerciseName(9);
    pub const BARBELL_HANG_SQUAT_SNATCH: SquatExerciseName = SquatExerciseName(10);
    pub const BARBELL_LATERAL_STEP_UP: SquatExerciseName = SquatExerciseName(11);
    pub const BARBELL_QUARTER_SQUAT: SquatExerciseName = SquatExerciseName(12);
    pub const BARBELL_SIFF_SQUAT: SquatExerciseName = SquatExerciseName(13);
    pub const BARBELL_SQUAT_SNATCH: SquatExerciseName = SquatExerciseName(14);
    pub const BARBELL_SQUAT_WITH_HEELS_RAISED: SquatExerciseName = SquatExerciseName(15);
    pub const BARBELL_STEPOVER: SquatExerciseName = SquatExerciseName(16);
    pub const BARBELL_STEP_UP: SquatExerciseName = SquatExerciseName(17);
    pub const BENCH_SQUAT_WITH_ROTATIONAL_CHOP: SquatExerciseName = SquatExerciseName(18);
    pub const WEIGHTED_BENCH_SQUAT_WITH_ROTATIONAL_CHOP: SquatExerciseName = SquatExerciseName(19);
    pub const BODY_WEIGHT_WALL_SQUAT: SquatExerciseName = SquatExerciseName(20);
    pub const WEIGHTED_WALL_SQUAT: SquatExerciseName = SquatExerciseName(21);
    pub const BOX_STEP_SQUAT: SquatExerciseName = SquatExerciseName(22);
    pub const WEIGHTED_BOX_STEP_SQUAT: SquatExerciseName = SquatExerciseName(23);
    pub const BRACED_SQUAT: SquatExerciseName = SquatExerciseName(24);
    pub const CROSSED_ARM_BARBELL_FRONT_SQUAT: SquatExerciseName = SquatExerciseName(25);
    pub const CROSSOVER_DUMBBELL_STEP_UP: SquatExerciseName = SquatExerciseName(26);
    pub const DUMBBELL_FRONT_SQUAT: SquatExerciseName = SquatExerciseName(27);
    pub const DUMBBELL_SPLIT_SQUAT: SquatExerciseName = SquatExerciseName(28);
    pub const DUMBBELL_SQUAT: SquatExerciseName = SquatExerciseName(29);
    pub const DUMBBELL_SQUAT_CLEAN: SquatExerciseName = SquatExerciseName(30);
    pub const DUMBBELL_STEPOVER: SquatExerciseName = SquatExerciseName(31);
    pub const DUMBBELL_STEP_UP: SquatExerciseName = SquatExerciseName(32);
    pub const ELEVATED_SINGLE_LEG_SQUAT: SquatExerciseName = SquatExerciseName(33);
    pub const WEIGHTED_ELEVATED_SINGLE_LEG_SQUAT: SquatExerciseName = SquatExerciseName(34);
    pub const FIGURE_FOUR_SQUATS: SquatExerciseName = SquatExerciseName(35);
    pub const WEIGHTED_FIGURE_FOUR_SQUATS: SquatExerciseName = SquatExerciseName(36);
    pub const GOBLET_SQUAT: SquatExerciseName = SquatExerciseName(37);
    pub const KETTLEBELL_SQUAT: SquatExerciseName = SquatExerciseName(38);
    pub const KETTLEBELL_SWING_OVERHEAD: SquatExerciseName = SquatExerciseName(39);
    pub const KETTLEBELL_SWING_WITH_FLIP_TO_SQUAT: SquatExerciseName = SquatExerciseName(40);
    pub const LATERAL_DUMBBELL_STEP_UP: SquatExerciseName = SquatExerciseName(41);
    pub const ONE_LEGGED_SQUAT: SquatExerciseName = SquatExerciseName(42);
    pub const OVERHEAD_DUMBBELL_SQUAT: SquatExerciseName = SquatExerciseName(43);
    pub const OVERHEAD_SQUAT: SquatExerciseName = SquatExerciseName(44);
    pub const PARTIAL_SINGLE_LEG_SQUAT: SquatExerciseName = SquatExerciseName(45);
    pub const WEIGHTED_PARTIAL_SINGLE_LEG_SQUAT: SquatExerciseName = SquatExerciseName(46);
    pub const PISTOL_SQUAT: SquatExerciseName = SquatExerciseName(47);
    pub const WEIGHTED_PISTOL_SQUAT: SquatExerciseName = SquatExerciseName(48);
    pub const PLIE_SLIDES: SquatExerciseName = SquatExerciseName(49);
    pub const WEIGHTED_PLIE_SLIDES: SquatExerciseName = SquatExerciseName(50);
    pub const PLIE_SQUAT: SquatExerciseName = SquatExerciseName(51);
    pub const WEIGHTED_PLIE_SQUAT: SquatExerciseName = SquatExerciseName(52);
    pub const PRISONER_SQUAT: SquatExerciseName = SquatExerciseName(53);
    pub const WEIGHTED_PRISONER_SQUAT: SquatExerciseName = SquatExerciseName(54);
    pub const SINGLE_LEG_BENCH_GET_UP: SquatExerciseName = SquatExerciseName(55);
    pub const WEIGHTED_SINGLE_LEG_BENCH_GET_UP: SquatExerciseName = SquatExerciseName(56);
    pub const SINGLE_LEG_BENCH_SQUAT: SquatExerciseName = SquatExerciseName(57);
    pub const WEIGHTED_SINGLE_LEG_BENCH_SQUAT: SquatExerciseName = SquatExerciseName(58);
    pub const SINGLE_LEG_SQUAT_ON_SWISS_BALL: SquatExerciseName = SquatExerciseName(59);
    pub const WEIGHTED_SINGLE_LEG_SQUAT_ON_SWISS_BALL: SquatExerciseName = SquatExerciseName(60);
    pub const SQUAT: SquatExerciseName = SquatExerciseName(61);
    pub const WEIGHTED_SQUAT: SquatExerciseName = SquatExerciseName(62);
    pub const SQUATS_WITH_BAND: SquatExerciseName = SquatExerciseName(63);
    pub const STAGGERED_SQUAT: SquatExerciseName = SquatExerciseName(64);
    pub const WEIGHTED_STAGGERED_SQUAT: SquatExerciseName = SquatExerciseName(65);
    pub const STEP_UP: SquatExerciseName = SquatExerciseName(66);
    pub const WEIGHTED_STEP_UP: SquatExerciseName = SquatExerciseName(67);
    pub const SUITCASE_SQUATS: SquatExerciseName = SquatExerciseName(68);
    pub const SUMO_SQUAT: SquatExerciseName = SquatExerciseName(69);
    pub const SUMO_SQUAT_SLIDE_IN: SquatExerciseName = SquatExerciseName(70);
    pub const WEIGHTED_SUMO_SQUAT_SLIDE_IN: SquatExerciseName = SquatExerciseName(71);
    pub const SUMO_SQUAT_TO_HIGH_PULL: SquatExerciseName = SquatExerciseName(72);
    pub const SUMO_SQUAT_TO_STAND: SquatExerciseName = SquatExerciseName(73);
    pub const WEIGHTED_SUMO_SQUAT_TO_STAND: SquatExerciseName = SquatExerciseName(74);
    pub const SUMO_SQUAT_WITH_ROTATION: SquatExerciseName = SquatExerciseName(75);
    pub const WEIGHTED_SUMO_SQUAT_WITH_ROTATION: SquatExerciseName = SquatExerciseName(76);
    pub const SWISS_BALL_BODY_WEIGHT_WALL_SQUAT: SquatExerciseName = SquatExerciseName(77);
    pub const WEIGHTED_SWISS_BALL_WALL_SQUAT: SquatExerciseName = SquatExerciseName(78);
    pub const THRUSTERS: SquatExerciseName = SquatExerciseName(79);
    pub const UNEVEN_SQUAT: SquatExerciseName = SquatExerciseName(80);
    pub const WEIGHTED_UNEVEN_SQUAT: SquatExerciseName = SquatExerciseName(81);
    pub const WAIST_SLIMMING_SQUAT: SquatExerciseName = SquatExerciseName(82);
    pub const WALL_BALL: SquatExerciseName = SquatExerciseName(83);
    pub const WIDE_STANCE_BARBELL_SQUAT: SquatExerciseName = SquatExerciseName(84);
    pub const WIDE_STANCE_GOBLET_SQUAT: SquatExerciseName = SquatExerciseName(85);
    pub const ZERCHER_SQUAT: SquatExerciseName = SquatExerciseName(86);
    /// Deprecated do not use
    pub const KBS_OVERHEAD: SquatExerciseName = SquatExerciseName(87);
    pub const SQUAT_AND_SIDE_KICK: SquatExerciseName = SquatExerciseName(88);
    pub const SQUAT_JUMPS_IN_N_OUT: SquatExerciseName = SquatExerciseName(89);
    pub const PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS: SquatExerciseName =
        SquatExerciseName(90);
    pub const RELEVE_STRAIGHT_LEG_AND_KNEE_BENT_WITH_ONE_LEG_VARIATION: SquatExerciseName =
        SquatExerciseName(91);
    pub const ALTERNATING_BOX_DUMBBELL_STEP_UPS: SquatExerciseName = SquatExerciseName(92);
    pub const DUMBBELL_OVERHEAD_SQUAT_SINGLE_ARM: SquatExerciseName = SquatExerciseName(93);
    pub const DUMBBELL_SQUAT_SNATCH: SquatExerciseName = SquatExerciseName(94);
    pub const MEDICINE_BALL_SQUAT: SquatExerciseName = SquatExerciseName(95);
    pub const WALL_BALL_SQUAT_AND_PRESS: SquatExerciseName = SquatExerciseName(97);
    pub const SQUAT_AMERICAN_SWING: SquatExerciseName = SquatExerciseName(98);
    pub const AIR_SQUAT: SquatExerciseName = SquatExerciseName(100);
    pub const DUMBBELL_THRUSTERS: SquatExerciseName = SquatExerciseName(101);
    pub const OVERHEAD_BARBELL_SQUAT: SquatExerciseName = SquatExerciseName(102);
}

impl Default for SquatExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for SquatExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "leg_press"),
            1 => write!(f, "back_squat_with_body_bar"),
            2 => write!(f, "back_squats"),
            3 => write!(f, "weighted_back_squats"),
            4 => write!(f, "balancing_squat"),
            5 => write!(f, "weighted_balancing_squat"),
            6 => write!(f, "barbell_back_squat"),
            7 => write!(f, "barbell_box_squat"),
            8 => write!(f, "barbell_front_squat"),
            9 => write!(f, "barbell_hack_squat"),
            10 => write!(f, "barbell_hang_squat_snatch"),
            11 => write!(f, "barbell_lateral_step_up"),
            12 => write!(f, "barbell_quarter_squat"),
            13 => write!(f, "barbell_siff_squat"),
            14 => write!(f, "barbell_squat_snatch"),
            15 => write!(f, "barbell_squat_with_heels_raised"),
            16 => write!(f, "barbell_stepover"),
            17 => write!(f, "barbell_step_up"),
            18 => write!(f, "bench_squat_with_rotational_chop"),
            19 => write!(f, "weighted_bench_squat_with_rotational_chop"),
            20 => write!(f, "body_weight_wall_squat"),
            21 => write!(f, "weighted_wall_squat"),
            22 => write!(f, "box_step_squat"),
            23 => write!(f, "weighted_box_step_squat"),
            24 => write!(f, "braced_squat"),
            25 => write!(f, "crossed_arm_barbell_front_squat"),
            26 => write!(f, "crossover_dumbbell_step_up"),
            27 => write!(f, "dumbbell_front_squat"),
            28 => write!(f, "dumbbell_split_squat"),
            29 => write!(f, "dumbbell_squat"),
            30 => write!(f, "dumbbell_squat_clean"),
            31 => write!(f, "dumbbell_stepover"),
            32 => write!(f, "dumbbell_step_up"),
            33 => write!(f, "elevated_single_leg_squat"),
            34 => write!(f, "weighted_elevated_single_leg_squat"),
            35 => write!(f, "figure_four_squats"),
            36 => write!(f, "weighted_figure_four_squats"),
            37 => write!(f, "goblet_squat"),
            38 => write!(f, "kettlebell_squat"),
            39 => write!(f, "kettlebell_swing_overhead"),
            40 => write!(f, "kettlebell_swing_with_flip_to_squat"),
            41 => write!(f, "lateral_dumbbell_step_up"),
            42 => write!(f, "one_legged_squat"),
            43 => write!(f, "overhead_dumbbell_squat"),
            44 => write!(f, "overhead_squat"),
            45 => write!(f, "partial_single_leg_squat"),
            46 => write!(f, "weighted_partial_single_leg_squat"),
            47 => write!(f, "pistol_squat"),
            48 => write!(f, "weighted_pistol_squat"),
            49 => write!(f, "plie_slides"),
            50 => write!(f, "weighted_plie_slides"),
            51 => write!(f, "plie_squat"),
            52 => write!(f, "weighted_plie_squat"),
            53 => write!(f, "prisoner_squat"),
            54 => write!(f, "weighted_prisoner_squat"),
            55 => write!(f, "single_leg_bench_get_up"),
            56 => write!(f, "weighted_single_leg_bench_get_up"),
            57 => write!(f, "single_leg_bench_squat"),
            58 => write!(f, "weighted_single_leg_bench_squat"),
            59 => write!(f, "single_leg_squat_on_swiss_ball"),
            60 => write!(f, "weighted_single_leg_squat_on_swiss_ball"),
            61 => write!(f, "squat"),
            62 => write!(f, "weighted_squat"),
            63 => write!(f, "squats_with_band"),
            64 => write!(f, "staggered_squat"),
            65 => write!(f, "weighted_staggered_squat"),
            66 => write!(f, "step_up"),
            67 => write!(f, "weighted_step_up"),
            68 => write!(f, "suitcase_squats"),
            69 => write!(f, "sumo_squat"),
            70 => write!(f, "sumo_squat_slide_in"),
            71 => write!(f, "weighted_sumo_squat_slide_in"),
            72 => write!(f, "sumo_squat_to_high_pull"),
            73 => write!(f, "sumo_squat_to_stand"),
            74 => write!(f, "weighted_sumo_squat_to_stand"),
            75 => write!(f, "sumo_squat_with_rotation"),
            76 => write!(f, "weighted_sumo_squat_with_rotation"),
            77 => write!(f, "swiss_ball_body_weight_wall_squat"),
            78 => write!(f, "weighted_swiss_ball_wall_squat"),
            79 => write!(f, "thrusters"),
            80 => write!(f, "uneven_squat"),
            81 => write!(f, "weighted_uneven_squat"),
            82 => write!(f, "waist_slimming_squat"),
            83 => write!(f, "wall_ball"),
            84 => write!(f, "wide_stance_barbell_squat"),
            85 => write!(f, "wide_stance_goblet_squat"),
            86 => write!(f, "zercher_squat"),
            87 => write!(f, "kbs_overhead"),
            88 => write!(f, "squat_and_side_kick"),
            89 => write!(f, "squat_jumps_in_n_out"),
            90 => write!(f, "pilates_plie_squats_parallel_turned_out_flat_and_heels"),
            91 => write!(
                f,
                "releve_straight_leg_and_knee_bent_with_one_leg_variation"
            ),
            92 => write!(f, "alternating_box_dumbbell_step_ups"),
            93 => write!(f, "dumbbell_overhead_squat_single_arm"),
            94 => write!(f, "dumbbell_squat_snatch"),
            95 => write!(f, "medicine_ball_squat"),
            97 => write!(f, "wall_ball_squat_and_press"),
            98 => write!(f, "squat_american_swing"),
            100 => write!(f, "air_squat"),
            101 => write!(f, "dumbbell_thrusters"),
            102 => write!(f, "overhead_barbell_squat"),
            _ => write!(f, "SquatExerciseName({})", self.0),
        }
    }
}
