// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct StairStepperExerciseName(pub u16);

impl StairStepperExerciseName {
    pub const STAIR_STEPPER: StairStepperExerciseName = StairStepperExerciseName(0);
}

impl Default for StairStepperExerciseName {
    fn default() -> Self {
        Self(u16::MAX)
    }
}

impl fmt::Display for StairStepperExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "stair_stepper"),
            _ => write!(f, "StairStepperExerciseName({})", self.0),
        }
    }
}

impl fmt::Debug for StairStepperExerciseName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "StairStepperExerciseName::STAIR_STEPPER(0)"),
            _ => write!(f, "StairStepperExerciseName({})", self.0),
        }
    }
}
