// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Time Zone type.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct TimeZone(pub u8);

impl TimeZone {
    pub const ALMATY: TimeZone = TimeZone(0);
    pub const BANGKOK: TimeZone = TimeZone(1);
    pub const BOMBAY: TimeZone = TimeZone(2);
    pub const BRASILIA: TimeZone = TimeZone(3);
    pub const CAIRO: TimeZone = TimeZone(4);
    pub const CAPE_VERDE_IS: TimeZone = TimeZone(5);
    pub const DARWIN: TimeZone = TimeZone(6);
    pub const ENIWETOK: TimeZone = TimeZone(7);
    pub const FIJI: TimeZone = TimeZone(8);
    pub const HONG_KONG: TimeZone = TimeZone(9);
    pub const ISLAMABAD: TimeZone = TimeZone(10);
    pub const KABUL: TimeZone = TimeZone(11);
    pub const MAGADAN: TimeZone = TimeZone(12);
    pub const MID_ATLANTIC: TimeZone = TimeZone(13);
    pub const MOSCOW: TimeZone = TimeZone(14);
    pub const MUSCAT: TimeZone = TimeZone(15);
    pub const NEWFOUNDLAND: TimeZone = TimeZone(16);
    pub const SAMOA: TimeZone = TimeZone(17);
    pub const SYDNEY: TimeZone = TimeZone(18);
    pub const TEHRAN: TimeZone = TimeZone(19);
    pub const TOKYO: TimeZone = TimeZone(20);
    pub const US_ALASKA: TimeZone = TimeZone(21);
    pub const US_ATLANTIC: TimeZone = TimeZone(22);
    pub const US_CENTRAL: TimeZone = TimeZone(23);
    pub const US_EASTERN: TimeZone = TimeZone(24);
    pub const US_HAWAII: TimeZone = TimeZone(25);
    pub const US_MOUNTAIN: TimeZone = TimeZone(26);
    pub const US_PACIFIC: TimeZone = TimeZone(27);
    pub const OTHER: TimeZone = TimeZone(28);
    pub const AUCKLAND: TimeZone = TimeZone(29);
    pub const KATHMANDU: TimeZone = TimeZone(30);
    pub const EUROPE_WESTERN_WET: TimeZone = TimeZone(31);
    pub const EUROPE_CENTRAL_CET: TimeZone = TimeZone(32);
    pub const EUROPE_EASTERN_EET: TimeZone = TimeZone(33);
    pub const JAKARTA: TimeZone = TimeZone(34);
    pub const PERTH: TimeZone = TimeZone(35);
    pub const ADELAIDE: TimeZone = TimeZone(36);
    pub const BRISBANE: TimeZone = TimeZone(37);
    pub const TASMANIA: TimeZone = TimeZone(38);
    pub const ICELAND: TimeZone = TimeZone(39);
    pub const AMSTERDAM: TimeZone = TimeZone(40);
    pub const ATHENS: TimeZone = TimeZone(41);
    pub const BARCELONA: TimeZone = TimeZone(42);
    pub const BERLIN: TimeZone = TimeZone(43);
    pub const BRUSSELS: TimeZone = TimeZone(44);
    pub const BUDAPEST: TimeZone = TimeZone(45);
    pub const COPENHAGEN: TimeZone = TimeZone(46);
    pub const DUBLIN: TimeZone = TimeZone(47);
    pub const HELSINKI: TimeZone = TimeZone(48);
    pub const LISBON: TimeZone = TimeZone(49);
    pub const LONDON: TimeZone = TimeZone(50);
    pub const MADRID: TimeZone = TimeZone(51);
    pub const MUNICH: TimeZone = TimeZone(52);
    pub const OSLO: TimeZone = TimeZone(53);
    pub const PARIS: TimeZone = TimeZone(54);
    pub const PRAGUE: TimeZone = TimeZone(55);
    pub const REYKJAVIK: TimeZone = TimeZone(56);
    pub const ROME: TimeZone = TimeZone(57);
    pub const STOCKHOLM: TimeZone = TimeZone(58);
    pub const VIENNA: TimeZone = TimeZone(59);
    pub const WARSAW: TimeZone = TimeZone(60);
    pub const ZURICH: TimeZone = TimeZone(61);
    pub const QUEBEC: TimeZone = TimeZone(62);
    pub const ONTARIO: TimeZone = TimeZone(63);
    pub const MANITOBA: TimeZone = TimeZone(64);
    pub const SASKATCHEWAN: TimeZone = TimeZone(65);
    pub const ALBERTA: TimeZone = TimeZone(66);
    pub const BRITISH_COLUMBIA: TimeZone = TimeZone(67);
    pub const BOISE: TimeZone = TimeZone(68);
    pub const BOSTON: TimeZone = TimeZone(69);
    pub const CHICAGO: TimeZone = TimeZone(70);
    pub const DALLAS: TimeZone = TimeZone(71);
    pub const DENVER: TimeZone = TimeZone(72);
    pub const KANSAS_CITY: TimeZone = TimeZone(73);
    pub const LAS_VEGAS: TimeZone = TimeZone(74);
    pub const LOS_ANGELES: TimeZone = TimeZone(75);
    pub const MIAMI: TimeZone = TimeZone(76);
    pub const MINNEAPOLIS: TimeZone = TimeZone(77);
    pub const NEW_YORK: TimeZone = TimeZone(78);
    pub const NEW_ORLEANS: TimeZone = TimeZone(79);
    pub const PHOENIX: TimeZone = TimeZone(80);
    pub const SANTA_FE: TimeZone = TimeZone(81);
    pub const SEATTLE: TimeZone = TimeZone(82);
    pub const WASHINGTON_DC: TimeZone = TimeZone(83);
    pub const US_ARIZONA: TimeZone = TimeZone(84);
    pub const CHITA: TimeZone = TimeZone(85);
    pub const EKATERINBURG: TimeZone = TimeZone(86);
    pub const IRKUTSK: TimeZone = TimeZone(87);
    pub const KALININGRAD: TimeZone = TimeZone(88);
    pub const KRASNOYARSK: TimeZone = TimeZone(89);
    pub const NOVOSIBIRSK: TimeZone = TimeZone(90);
    pub const PETROPAVLOVSK_KAMCHATSKIY: TimeZone = TimeZone(91);
    pub const SAMARA: TimeZone = TimeZone(92);
    pub const VLADIVOSTOK: TimeZone = TimeZone(93);
    pub const MEXICO_CENTRAL: TimeZone = TimeZone(94);
    pub const MEXICO_MOUNTAIN: TimeZone = TimeZone(95);
    pub const MEXICO_PACIFIC: TimeZone = TimeZone(96);
    pub const CAPE_TOWN: TimeZone = TimeZone(97);
    pub const WINKHOEK: TimeZone = TimeZone(98);
    pub const LAGOS: TimeZone = TimeZone(99);
    pub const RIYAHD: TimeZone = TimeZone(100);
    pub const VENEZUELA: TimeZone = TimeZone(101);
    pub const AUSTRALIA_LH: TimeZone = TimeZone(102);
    pub const SANTIAGO: TimeZone = TimeZone(103);
    pub const MANUAL: TimeZone = TimeZone(253);
    pub const AUTOMATIC: TimeZone = TimeZone(254);
}

impl Default for TimeZone {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for TimeZone {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "almaty"),
            1 => write!(f, "bangkok"),
            2 => write!(f, "bombay"),
            3 => write!(f, "brasilia"),
            4 => write!(f, "cairo"),
            5 => write!(f, "cape_verde_is"),
            6 => write!(f, "darwin"),
            7 => write!(f, "eniwetok"),
            8 => write!(f, "fiji"),
            9 => write!(f, "hong_kong"),
            10 => write!(f, "islamabad"),
            11 => write!(f, "kabul"),
            12 => write!(f, "magadan"),
            13 => write!(f, "mid_atlantic"),
            14 => write!(f, "moscow"),
            15 => write!(f, "muscat"),
            16 => write!(f, "newfoundland"),
            17 => write!(f, "samoa"),
            18 => write!(f, "sydney"),
            19 => write!(f, "tehran"),
            20 => write!(f, "tokyo"),
            21 => write!(f, "us_alaska"),
            22 => write!(f, "us_atlantic"),
            23 => write!(f, "us_central"),
            24 => write!(f, "us_eastern"),
            25 => write!(f, "us_hawaii"),
            26 => write!(f, "us_mountain"),
            27 => write!(f, "us_pacific"),
            28 => write!(f, "other"),
            29 => write!(f, "auckland"),
            30 => write!(f, "kathmandu"),
            31 => write!(f, "europe_western_wet"),
            32 => write!(f, "europe_central_cet"),
            33 => write!(f, "europe_eastern_eet"),
            34 => write!(f, "jakarta"),
            35 => write!(f, "perth"),
            36 => write!(f, "adelaide"),
            37 => write!(f, "brisbane"),
            38 => write!(f, "tasmania"),
            39 => write!(f, "iceland"),
            40 => write!(f, "amsterdam"),
            41 => write!(f, "athens"),
            42 => write!(f, "barcelona"),
            43 => write!(f, "berlin"),
            44 => write!(f, "brussels"),
            45 => write!(f, "budapest"),
            46 => write!(f, "copenhagen"),
            47 => write!(f, "dublin"),
            48 => write!(f, "helsinki"),
            49 => write!(f, "lisbon"),
            50 => write!(f, "london"),
            51 => write!(f, "madrid"),
            52 => write!(f, "munich"),
            53 => write!(f, "oslo"),
            54 => write!(f, "paris"),
            55 => write!(f, "prague"),
            56 => write!(f, "reykjavik"),
            57 => write!(f, "rome"),
            58 => write!(f, "stockholm"),
            59 => write!(f, "vienna"),
            60 => write!(f, "warsaw"),
            61 => write!(f, "zurich"),
            62 => write!(f, "quebec"),
            63 => write!(f, "ontario"),
            64 => write!(f, "manitoba"),
            65 => write!(f, "saskatchewan"),
            66 => write!(f, "alberta"),
            67 => write!(f, "british_columbia"),
            68 => write!(f, "boise"),
            69 => write!(f, "boston"),
            70 => write!(f, "chicago"),
            71 => write!(f, "dallas"),
            72 => write!(f, "denver"),
            73 => write!(f, "kansas_city"),
            74 => write!(f, "las_vegas"),
            75 => write!(f, "los_angeles"),
            76 => write!(f, "miami"),
            77 => write!(f, "minneapolis"),
            78 => write!(f, "new_york"),
            79 => write!(f, "new_orleans"),
            80 => write!(f, "phoenix"),
            81 => write!(f, "santa_fe"),
            82 => write!(f, "seattle"),
            83 => write!(f, "washington_dc"),
            84 => write!(f, "us_arizona"),
            85 => write!(f, "chita"),
            86 => write!(f, "ekaterinburg"),
            87 => write!(f, "irkutsk"),
            88 => write!(f, "kaliningrad"),
            89 => write!(f, "krasnoyarsk"),
            90 => write!(f, "novosibirsk"),
            91 => write!(f, "petropavlovsk_kamchatskiy"),
            92 => write!(f, "samara"),
            93 => write!(f, "vladivostok"),
            94 => write!(f, "mexico_central"),
            95 => write!(f, "mexico_mountain"),
            96 => write!(f, "mexico_pacific"),
            97 => write!(f, "cape_town"),
            98 => write!(f, "winkhoek"),
            99 => write!(f, "lagos"),
            100 => write!(f, "riyahd"),
            101 => write!(f, "venezuela"),
            102 => write!(f, "australia_lh"),
            103 => write!(f, "santiago"),
            253 => write!(f, "manual"),
            254 => write!(f, "automatic"),
            _ => write!(f, "TimeZone({})", self.0),
        }
    }
}

impl fmt::Debug for TimeZone {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "TimeZone::ALMATY(0)"),
            1 => write!(f, "TimeZone::BANGKOK(1)"),
            2 => write!(f, "TimeZone::BOMBAY(2)"),
            3 => write!(f, "TimeZone::BRASILIA(3)"),
            4 => write!(f, "TimeZone::CAIRO(4)"),
            5 => write!(f, "TimeZone::CAPE_VERDE_IS(5)"),
            6 => write!(f, "TimeZone::DARWIN(6)"),
            7 => write!(f, "TimeZone::ENIWETOK(7)"),
            8 => write!(f, "TimeZone::FIJI(8)"),
            9 => write!(f, "TimeZone::HONG_KONG(9)"),
            10 => write!(f, "TimeZone::ISLAMABAD(10)"),
            11 => write!(f, "TimeZone::KABUL(11)"),
            12 => write!(f, "TimeZone::MAGADAN(12)"),
            13 => write!(f, "TimeZone::MID_ATLANTIC(13)"),
            14 => write!(f, "TimeZone::MOSCOW(14)"),
            15 => write!(f, "TimeZone::MUSCAT(15)"),
            16 => write!(f, "TimeZone::NEWFOUNDLAND(16)"),
            17 => write!(f, "TimeZone::SAMOA(17)"),
            18 => write!(f, "TimeZone::SYDNEY(18)"),
            19 => write!(f, "TimeZone::TEHRAN(19)"),
            20 => write!(f, "TimeZone::TOKYO(20)"),
            21 => write!(f, "TimeZone::US_ALASKA(21)"),
            22 => write!(f, "TimeZone::US_ATLANTIC(22)"),
            23 => write!(f, "TimeZone::US_CENTRAL(23)"),
            24 => write!(f, "TimeZone::US_EASTERN(24)"),
            25 => write!(f, "TimeZone::US_HAWAII(25)"),
            26 => write!(f, "TimeZone::US_MOUNTAIN(26)"),
            27 => write!(f, "TimeZone::US_PACIFIC(27)"),
            28 => write!(f, "TimeZone::OTHER(28)"),
            29 => write!(f, "TimeZone::AUCKLAND(29)"),
            30 => write!(f, "TimeZone::KATHMANDU(30)"),
            31 => write!(f, "TimeZone::EUROPE_WESTERN_WET(31)"),
            32 => write!(f, "TimeZone::EUROPE_CENTRAL_CET(32)"),
            33 => write!(f, "TimeZone::EUROPE_EASTERN_EET(33)"),
            34 => write!(f, "TimeZone::JAKARTA(34)"),
            35 => write!(f, "TimeZone::PERTH(35)"),
            36 => write!(f, "TimeZone::ADELAIDE(36)"),
            37 => write!(f, "TimeZone::BRISBANE(37)"),
            38 => write!(f, "TimeZone::TASMANIA(38)"),
            39 => write!(f, "TimeZone::ICELAND(39)"),
            40 => write!(f, "TimeZone::AMSTERDAM(40)"),
            41 => write!(f, "TimeZone::ATHENS(41)"),
            42 => write!(f, "TimeZone::BARCELONA(42)"),
            43 => write!(f, "TimeZone::BERLIN(43)"),
            44 => write!(f, "TimeZone::BRUSSELS(44)"),
            45 => write!(f, "TimeZone::BUDAPEST(45)"),
            46 => write!(f, "TimeZone::COPENHAGEN(46)"),
            47 => write!(f, "TimeZone::DUBLIN(47)"),
            48 => write!(f, "TimeZone::HELSINKI(48)"),
            49 => write!(f, "TimeZone::LISBON(49)"),
            50 => write!(f, "TimeZone::LONDON(50)"),
            51 => write!(f, "TimeZone::MADRID(51)"),
            52 => write!(f, "TimeZone::MUNICH(52)"),
            53 => write!(f, "TimeZone::OSLO(53)"),
            54 => write!(f, "TimeZone::PARIS(54)"),
            55 => write!(f, "TimeZone::PRAGUE(55)"),
            56 => write!(f, "TimeZone::REYKJAVIK(56)"),
            57 => write!(f, "TimeZone::ROME(57)"),
            58 => write!(f, "TimeZone::STOCKHOLM(58)"),
            59 => write!(f, "TimeZone::VIENNA(59)"),
            60 => write!(f, "TimeZone::WARSAW(60)"),
            61 => write!(f, "TimeZone::ZURICH(61)"),
            62 => write!(f, "TimeZone::QUEBEC(62)"),
            63 => write!(f, "TimeZone::ONTARIO(63)"),
            64 => write!(f, "TimeZone::MANITOBA(64)"),
            65 => write!(f, "TimeZone::SASKATCHEWAN(65)"),
            66 => write!(f, "TimeZone::ALBERTA(66)"),
            67 => write!(f, "TimeZone::BRITISH_COLUMBIA(67)"),
            68 => write!(f, "TimeZone::BOISE(68)"),
            69 => write!(f, "TimeZone::BOSTON(69)"),
            70 => write!(f, "TimeZone::CHICAGO(70)"),
            71 => write!(f, "TimeZone::DALLAS(71)"),
            72 => write!(f, "TimeZone::DENVER(72)"),
            73 => write!(f, "TimeZone::KANSAS_CITY(73)"),
            74 => write!(f, "TimeZone::LAS_VEGAS(74)"),
            75 => write!(f, "TimeZone::LOS_ANGELES(75)"),
            76 => write!(f, "TimeZone::MIAMI(76)"),
            77 => write!(f, "TimeZone::MINNEAPOLIS(77)"),
            78 => write!(f, "TimeZone::NEW_YORK(78)"),
            79 => write!(f, "TimeZone::NEW_ORLEANS(79)"),
            80 => write!(f, "TimeZone::PHOENIX(80)"),
            81 => write!(f, "TimeZone::SANTA_FE(81)"),
            82 => write!(f, "TimeZone::SEATTLE(82)"),
            83 => write!(f, "TimeZone::WASHINGTON_DC(83)"),
            84 => write!(f, "TimeZone::US_ARIZONA(84)"),
            85 => write!(f, "TimeZone::CHITA(85)"),
            86 => write!(f, "TimeZone::EKATERINBURG(86)"),
            87 => write!(f, "TimeZone::IRKUTSK(87)"),
            88 => write!(f, "TimeZone::KALININGRAD(88)"),
            89 => write!(f, "TimeZone::KRASNOYARSK(89)"),
            90 => write!(f, "TimeZone::NOVOSIBIRSK(90)"),
            91 => write!(f, "TimeZone::PETROPAVLOVSK_KAMCHATSKIY(91)"),
            92 => write!(f, "TimeZone::SAMARA(92)"),
            93 => write!(f, "TimeZone::VLADIVOSTOK(93)"),
            94 => write!(f, "TimeZone::MEXICO_CENTRAL(94)"),
            95 => write!(f, "TimeZone::MEXICO_MOUNTAIN(95)"),
            96 => write!(f, "TimeZone::MEXICO_PACIFIC(96)"),
            97 => write!(f, "TimeZone::CAPE_TOWN(97)"),
            98 => write!(f, "TimeZone::WINKHOEK(98)"),
            99 => write!(f, "TimeZone::LAGOS(99)"),
            100 => write!(f, "TimeZone::RIYAHD(100)"),
            101 => write!(f, "TimeZone::VENEZUELA(101)"),
            102 => write!(f, "TimeZone::AUSTRALIA_LH(102)"),
            103 => write!(f, "TimeZone::SANTIAGO(103)"),
            253 => write!(f, "TimeZone::MANUAL(253)"),
            254 => write!(f, "TimeZone::AUTOMATIC(254)"),
            _ => write!(f, "TimeZone({})", self.0),
        }
    }
}
