// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

/// Weather Report type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct WeatherReport(pub u8);

impl WeatherReport {
    pub const CURRENT: WeatherReport = WeatherReport(0);
    // Deprecated use hourly_forecast instead: pub const FORECAST: WeatherReport = WeatherReport(1);
    pub const HOURLY_FORECAST: WeatherReport = WeatherReport(1);
    pub const DAILY_FORECAST: WeatherReport = WeatherReport(2);
}

impl Default for WeatherReport {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for WeatherReport {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "current"),
            // Deprecated use hourly_forecast instead: 1 => write!(f, "forecast"),
            1 => write!(f, "hourly_forecast"),
            2 => write!(f, "daily_forecast"),
            _ => write!(f, "WeatherReport({})", self.0),
        }
    }
}
