// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::match_single_binding)]

use core::fmt;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct WeatherStatus(pub u8);

impl WeatherStatus {
    pub const CLEAR: WeatherStatus = WeatherStatus(0);
    pub const PARTLY_CLOUDY: WeatherStatus = WeatherStatus(1);
    pub const MOSTLY_CLOUDY: WeatherStatus = WeatherStatus(2);
    pub const RAIN: WeatherStatus = WeatherStatus(3);
    pub const SNOW: WeatherStatus = WeatherStatus(4);
    pub const WINDY: WeatherStatus = WeatherStatus(5);
    pub const THUNDERSTORMS: WeatherStatus = WeatherStatus(6);
    pub const WINTRY_MIX: WeatherStatus = WeatherStatus(7);
    pub const FOG: WeatherStatus = WeatherStatus(8);
    pub const HAZY: WeatherStatus = WeatherStatus(11);
    pub const HAIL: WeatherStatus = WeatherStatus(12);
    pub const SCATTERED_SHOWERS: WeatherStatus = WeatherStatus(13);
    pub const SCATTERED_THUNDERSTORMS: WeatherStatus = WeatherStatus(14);
    pub const UNKNOWN_PRECIPITATION: WeatherStatus = WeatherStatus(15);
    pub const LIGHT_RAIN: WeatherStatus = WeatherStatus(16);
    pub const HEAVY_RAIN: WeatherStatus = WeatherStatus(17);
    pub const LIGHT_SNOW: WeatherStatus = WeatherStatus(18);
    pub const HEAVY_SNOW: WeatherStatus = WeatherStatus(19);
    pub const LIGHT_RAIN_SNOW: WeatherStatus = WeatherStatus(20);
    pub const HEAVY_RAIN_SNOW: WeatherStatus = WeatherStatus(21);
    pub const CLOUDY: WeatherStatus = WeatherStatus(22);
}

impl Default for WeatherStatus {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for WeatherStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "clear"),
            1 => write!(f, "partly_cloudy"),
            2 => write!(f, "mostly_cloudy"),
            3 => write!(f, "rain"),
            4 => write!(f, "snow"),
            5 => write!(f, "windy"),
            6 => write!(f, "thunderstorms"),
            7 => write!(f, "wintry_mix"),
            8 => write!(f, "fog"),
            11 => write!(f, "hazy"),
            12 => write!(f, "hail"),
            13 => write!(f, "scattered_showers"),
            14 => write!(f, "scattered_thunderstorms"),
            15 => write!(f, "unknown_precipitation"),
            16 => write!(f, "light_rain"),
            17 => write!(f, "heavy_rain"),
            18 => write!(f, "light_snow"),
            19 => write!(f, "heavy_snow"),
            20 => write!(f, "light_rain_snow"),
            21 => write!(f, "heavy_rain_snow"),
            22 => write!(f, "cloudy"),
            _ => write!(f, "WeatherStatus({})", self.0),
        }
    }
}

impl fmt::Debug for WeatherStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "WeatherStatus::CLEAR(0)"),
            1 => write!(f, "WeatherStatus::PARTLY_CLOUDY(1)"),
            2 => write!(f, "WeatherStatus::MOSTLY_CLOUDY(2)"),
            3 => write!(f, "WeatherStatus::RAIN(3)"),
            4 => write!(f, "WeatherStatus::SNOW(4)"),
            5 => write!(f, "WeatherStatus::WINDY(5)"),
            6 => write!(f, "WeatherStatus::THUNDERSTORMS(6)"),
            7 => write!(f, "WeatherStatus::WINTRY_MIX(7)"),
            8 => write!(f, "WeatherStatus::FOG(8)"),
            11 => write!(f, "WeatherStatus::HAZY(11)"),
            12 => write!(f, "WeatherStatus::HAIL(12)"),
            13 => write!(f, "WeatherStatus::SCATTERED_SHOWERS(13)"),
            14 => write!(f, "WeatherStatus::SCATTERED_THUNDERSTORMS(14)"),
            15 => write!(f, "WeatherStatus::UNKNOWN_PRECIPITATION(15)"),
            16 => write!(f, "WeatherStatus::LIGHT_RAIN(16)"),
            17 => write!(f, "WeatherStatus::HEAVY_RAIN(17)"),
            18 => write!(f, "WeatherStatus::LIGHT_SNOW(18)"),
            19 => write!(f, "WeatherStatus::HEAVY_SNOW(19)"),
            20 => write!(f, "WeatherStatus::LIGHT_RAIN_SNOW(20)"),
            21 => write!(f, "WeatherStatus::HEAVY_RAIN_SNOW(21)"),
            22 => write!(f, "WeatherStatus::CLOUDY(22)"),
            _ => write!(f, "WeatherStatus({})", self.0),
        }
    }
}
