// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Weather Severe Type type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct WeatherSevereType(pub u8);

impl WeatherSevereType {
    pub const UNSPECIFIED: WeatherSevereType = WeatherSevereType(0);
    pub const TORNADO: WeatherSevereType = WeatherSevereType(1);
    pub const TSUNAMI: WeatherSevereType = WeatherSevereType(2);
    pub const HURRICANE: WeatherSevereType = WeatherSevereType(3);
    pub const EXTREME_WIND: WeatherSevereType = WeatherSevereType(4);
    pub const TYPHOON: WeatherSevereType = WeatherSevereType(5);
    pub const INLAND_HURRICANE: WeatherSevereType = WeatherSevereType(6);
    pub const HURRICANE_FORCE_WIND: WeatherSevereType = WeatherSevereType(7);
    pub const WATERSPOUT: WeatherSevereType = WeatherSevereType(8);
    pub const SEVERE_THUNDERSTORM: WeatherSevereType = WeatherSevereType(9);
    pub const WRECKHOUSE_WINDS: WeatherSevereType = WeatherSevereType(10);
    pub const LES_SUETES_WIND: WeatherSevereType = WeatherSevereType(11);
    pub const AVALANCHE: WeatherSevereType = WeatherSevereType(12);
    pub const FLASH_FLOOD: WeatherSevereType = WeatherSevereType(13);
    pub const TROPICAL_STORM: WeatherSevereType = WeatherSevereType(14);
    pub const INLAND_TROPICAL_STORM: WeatherSevereType = WeatherSevereType(15);
    pub const BLIZZARD: WeatherSevereType = WeatherSevereType(16);
    pub const ICE_STORM: WeatherSevereType = WeatherSevereType(17);
    pub const FREEZING_RAIN: WeatherSevereType = WeatherSevereType(18);
    pub const DEBRIS_FLOW: WeatherSevereType = WeatherSevereType(19);
    pub const FLASH_FREEZE: WeatherSevereType = WeatherSevereType(20);
    pub const DUST_STORM: WeatherSevereType = WeatherSevereType(21);
    pub const HIGH_WIND: WeatherSevereType = WeatherSevereType(22);
    pub const WINTER_STORM: WeatherSevereType = WeatherSevereType(23);
    pub const HEAVY_FREEZING_SPRAY: WeatherSevereType = WeatherSevereType(24);
    pub const EXTREME_COLD: WeatherSevereType = WeatherSevereType(25);
    pub const WIND_CHILL: WeatherSevereType = WeatherSevereType(26);
    pub const COLD_WAVE: WeatherSevereType = WeatherSevereType(27);
    pub const HEAVY_SNOW_ALERT: WeatherSevereType = WeatherSevereType(28);
    pub const LAKE_EFFECT_BLOWING_SNOW: WeatherSevereType = WeatherSevereType(29);
    pub const SNOW_SQUALL: WeatherSevereType = WeatherSevereType(30);
    pub const LAKE_EFFECT_SNOW: WeatherSevereType = WeatherSevereType(31);
    pub const WINTER_WEATHER: WeatherSevereType = WeatherSevereType(32);
    pub const SLEET: WeatherSevereType = WeatherSevereType(33);
    pub const SNOWFALL: WeatherSevereType = WeatherSevereType(34);
    pub const SNOW_AND_BLOWING_SNOW: WeatherSevereType = WeatherSevereType(35);
    pub const BLOWING_SNOW: WeatherSevereType = WeatherSevereType(36);
    pub const SNOW_ALERT: WeatherSevereType = WeatherSevereType(37);
    pub const ARCTIC_OUTFLOW: WeatherSevereType = WeatherSevereType(38);
    pub const FREEZING_DRIZZLE: WeatherSevereType = WeatherSevereType(39);
    pub const STORM: WeatherSevereType = WeatherSevereType(40);
    pub const STORM_SURGE: WeatherSevereType = WeatherSevereType(41);
    pub const RAINFALL: WeatherSevereType = WeatherSevereType(42);
    pub const AREAL_FLOOD: WeatherSevereType = WeatherSevereType(43);
    pub const COASTAL_FLOOD: WeatherSevereType = WeatherSevereType(44);
    pub const LAKESHORE_FLOOD: WeatherSevereType = WeatherSevereType(45);
    pub const EXCESSIVE_HEAT: WeatherSevereType = WeatherSevereType(46);
    pub const HEAT: WeatherSevereType = WeatherSevereType(47);
    pub const WEATHER: WeatherSevereType = WeatherSevereType(48);
    pub const HIGH_HEAT_AND_HUMIDITY: WeatherSevereType = WeatherSevereType(49);
    pub const HUMIDEX_AND_HEALTH: WeatherSevereType = WeatherSevereType(50);
    pub const HUMIDEX: WeatherSevereType = WeatherSevereType(51);
    pub const GALE: WeatherSevereType = WeatherSevereType(52);
    pub const FREEZING_SPRAY: WeatherSevereType = WeatherSevereType(53);
    pub const SPECIAL_MARINE: WeatherSevereType = WeatherSevereType(54);
    pub const SQUALL: WeatherSevereType = WeatherSevereType(55);
    pub const STRONG_WIND: WeatherSevereType = WeatherSevereType(56);
    pub const LAKE_WIND: WeatherSevereType = WeatherSevereType(57);
    pub const MARINE_WEATHER: WeatherSevereType = WeatherSevereType(58);
    pub const WIND: WeatherSevereType = WeatherSevereType(59);
    pub const SMALL_CRAFT_HAZARDOUS_SEAS: WeatherSevereType = WeatherSevereType(60);
    pub const HAZARDOUS_SEAS: WeatherSevereType = WeatherSevereType(61);
    pub const SMALL_CRAFT: WeatherSevereType = WeatherSevereType(62);
    pub const SMALL_CRAFT_WINDS: WeatherSevereType = WeatherSevereType(63);
    pub const SMALL_CRAFT_ROUGH_BAR: WeatherSevereType = WeatherSevereType(64);
    pub const HIGH_WATER_LEVEL: WeatherSevereType = WeatherSevereType(65);
    pub const ASHFALL: WeatherSevereType = WeatherSevereType(66);
    pub const FREEZING_FOG: WeatherSevereType = WeatherSevereType(67);
    pub const DENSE_FOG: WeatherSevereType = WeatherSevereType(68);
    pub const DENSE_SMOKE: WeatherSevereType = WeatherSevereType(69);
    pub const BLOWING_DUST: WeatherSevereType = WeatherSevereType(70);
    pub const HARD_FREEZE: WeatherSevereType = WeatherSevereType(71);
    pub const FREEZE: WeatherSevereType = WeatherSevereType(72);
    pub const FROST: WeatherSevereType = WeatherSevereType(73);
    pub const FIRE_WEATHER: WeatherSevereType = WeatherSevereType(74);
    pub const FLOOD: WeatherSevereType = WeatherSevereType(75);
    pub const RIP_TIDE: WeatherSevereType = WeatherSevereType(76);
    pub const HIGH_SURF: WeatherSevereType = WeatherSevereType(77);
    pub const SMOG: WeatherSevereType = WeatherSevereType(78);
    pub const AIR_QUALITY: WeatherSevereType = WeatherSevereType(79);
    pub const BRISK_WIND: WeatherSevereType = WeatherSevereType(80);
    pub const AIR_STAGNATION: WeatherSevereType = WeatherSevereType(81);
    pub const LOW_WATER: WeatherSevereType = WeatherSevereType(82);
    pub const HYDROLOGICAL: WeatherSevereType = WeatherSevereType(83);
    pub const SPECIAL_WEATHER: WeatherSevereType = WeatherSevereType(84);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("unspecified"),
            1 => Some("tornado"),
            2 => Some("tsunami"),
            3 => Some("hurricane"),
            4 => Some("extreme_wind"),
            5 => Some("typhoon"),
            6 => Some("inland_hurricane"),
            7 => Some("hurricane_force_wind"),
            8 => Some("waterspout"),
            9 => Some("severe_thunderstorm"),
            10 => Some("wreckhouse_winds"),
            11 => Some("les_suetes_wind"),
            12 => Some("avalanche"),
            13 => Some("flash_flood"),
            14 => Some("tropical_storm"),
            15 => Some("inland_tropical_storm"),
            16 => Some("blizzard"),
            17 => Some("ice_storm"),
            18 => Some("freezing_rain"),
            19 => Some("debris_flow"),
            20 => Some("flash_freeze"),
            21 => Some("dust_storm"),
            22 => Some("high_wind"),
            23 => Some("winter_storm"),
            24 => Some("heavy_freezing_spray"),
            25 => Some("extreme_cold"),
            26 => Some("wind_chill"),
            27 => Some("cold_wave"),
            28 => Some("heavy_snow_alert"),
            29 => Some("lake_effect_blowing_snow"),
            30 => Some("snow_squall"),
            31 => Some("lake_effect_snow"),
            32 => Some("winter_weather"),
            33 => Some("sleet"),
            34 => Some("snowfall"),
            35 => Some("snow_and_blowing_snow"),
            36 => Some("blowing_snow"),
            37 => Some("snow_alert"),
            38 => Some("arctic_outflow"),
            39 => Some("freezing_drizzle"),
            40 => Some("storm"),
            41 => Some("storm_surge"),
            42 => Some("rainfall"),
            43 => Some("areal_flood"),
            44 => Some("coastal_flood"),
            45 => Some("lakeshore_flood"),
            46 => Some("excessive_heat"),
            47 => Some("heat"),
            48 => Some("weather"),
            49 => Some("high_heat_and_humidity"),
            50 => Some("humidex_and_health"),
            51 => Some("humidex"),
            52 => Some("gale"),
            53 => Some("freezing_spray"),
            54 => Some("special_marine"),
            55 => Some("squall"),
            56 => Some("strong_wind"),
            57 => Some("lake_wind"),
            58 => Some("marine_weather"),
            59 => Some("wind"),
            60 => Some("small_craft_hazardous_seas"),
            61 => Some("hazardous_seas"),
            62 => Some("small_craft"),
            63 => Some("small_craft_winds"),
            64 => Some("small_craft_rough_bar"),
            65 => Some("high_water_level"),
            66 => Some("ashfall"),
            67 => Some("freezing_fog"),
            68 => Some("dense_fog"),
            69 => Some("dense_smoke"),
            70 => Some("blowing_dust"),
            71 => Some("hard_freeze"),
            72 => Some("freeze"),
            73 => Some("frost"),
            74 => Some("fire_weather"),
            75 => Some("flood"),
            76 => Some("rip_tide"),
            77 => Some("high_surf"),
            78 => Some("smog"),
            79 => Some("air_quality"),
            80 => Some("brisk_wind"),
            81 => Some("air_stagnation"),
            82 => Some("low_water"),
            83 => Some("hydrological"),
            84 => Some("special_weather"),
            _ => None,
        }
    }
}

impl Default for WeatherSevereType {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for WeatherSevereType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "WeatherSevereType({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for WeatherSevereType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("WeatherSevereType", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for WeatherSevereType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
