// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use core::fmt;
#[cfg(feature = "serde")]
use serde::{Deserialize, Deserializer, Serialize, Serializer, de, ser::SerializeStruct};

/// Yds Grading Scale type.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct YdsGradingScale(pub u8);

impl YdsGradingScale {
    /// 5.1
    pub const _5_1: YdsGradingScale = YdsGradingScale(0);
    /// 5.2
    pub const _5_2: YdsGradingScale = YdsGradingScale(1);
    /// 5.3
    pub const _5_3: YdsGradingScale = YdsGradingScale(2);
    /// 5.4
    pub const _5_4: YdsGradingScale = YdsGradingScale(3);
    /// 5.5
    pub const _5_5: YdsGradingScale = YdsGradingScale(4);
    /// 5.6
    pub const _5_6: YdsGradingScale = YdsGradingScale(5);
    /// 5.7
    pub const _5_7: YdsGradingScale = YdsGradingScale(6);
    /// 5.8
    pub const _5_8: YdsGradingScale = YdsGradingScale(7);
    /// 5.9
    pub const _5_9: YdsGradingScale = YdsGradingScale(8);
    /// 5.1
    pub const _5_10: YdsGradingScale = YdsGradingScale(9);
    /// 5.10a
    pub const _5_10A: YdsGradingScale = YdsGradingScale(10);
    /// 5.10b
    pub const _5_10B: YdsGradingScale = YdsGradingScale(11);
    /// 5.10c
    pub const _5_10C: YdsGradingScale = YdsGradingScale(12);
    /// 5.10d
    pub const _5_10D: YdsGradingScale = YdsGradingScale(13);
    /// 5.11
    pub const _5_11: YdsGradingScale = YdsGradingScale(14);
    /// 5.11a
    pub const _5_11A: YdsGradingScale = YdsGradingScale(15);
    /// 5.11b
    pub const _5_11B: YdsGradingScale = YdsGradingScale(16);
    /// 5.11c
    pub const _5_11C: YdsGradingScale = YdsGradingScale(17);
    /// 5.11d
    pub const _5_11D: YdsGradingScale = YdsGradingScale(18);
    /// 5.12
    pub const _5_12: YdsGradingScale = YdsGradingScale(19);
    /// 5.12a
    pub const _5_12A: YdsGradingScale = YdsGradingScale(20);
    /// 5.12b
    pub const _5_12B: YdsGradingScale = YdsGradingScale(21);
    /// 5.12c
    pub const _5_12C: YdsGradingScale = YdsGradingScale(22);
    /// 5.12d
    pub const _5_12D: YdsGradingScale = YdsGradingScale(23);
    /// 5.13
    pub const _5_13: YdsGradingScale = YdsGradingScale(24);
    /// 5.13a
    pub const _5_13A: YdsGradingScale = YdsGradingScale(25);
    /// 5.13b
    pub const _5_13B: YdsGradingScale = YdsGradingScale(26);
    /// 5.13c
    pub const _5_13C: YdsGradingScale = YdsGradingScale(27);
    /// 5.13d
    pub const _5_13D: YdsGradingScale = YdsGradingScale(28);
    /// 5.14
    pub const _5_14: YdsGradingScale = YdsGradingScale(29);
    /// 5.14a
    pub const _5_14A: YdsGradingScale = YdsGradingScale(30);
    /// 5.14b
    pub const _5_14B: YdsGradingScale = YdsGradingScale(31);
    /// 5.14c
    pub const _5_14C: YdsGradingScale = YdsGradingScale(32);
    /// 5.14d
    pub const _5_14D: YdsGradingScale = YdsGradingScale(33);
    /// 5.15
    pub const _5_15: YdsGradingScale = YdsGradingScale(34);
    /// 5.15a
    pub const _5_15A: YdsGradingScale = YdsGradingScale(35);
    /// 5.15b
    pub const _5_15B: YdsGradingScale = YdsGradingScale(36);
    /// 5.15c
    pub const _5_15C: YdsGradingScale = YdsGradingScale(37);
    /// 5.15d
    pub const _5_15D: YdsGradingScale = YdsGradingScale(38);
    /// 5.1-
    pub const _5_1_MINUS: YdsGradingScale = YdsGradingScale(39);
    /// 5.1+
    pub const _5_1_PLUS: YdsGradingScale = YdsGradingScale(40);
    /// 5.2-
    pub const _5_2_MINUS: YdsGradingScale = YdsGradingScale(41);
    /// 5.2+
    pub const _5_2_PLUS: YdsGradingScale = YdsGradingScale(42);
    /// 5.3-
    pub const _5_3_MINUS: YdsGradingScale = YdsGradingScale(43);
    /// 5.3+
    pub const _5_3_PLUS: YdsGradingScale = YdsGradingScale(44);
    /// 5.4-
    pub const _5_4_MINUS: YdsGradingScale = YdsGradingScale(45);
    /// 5.4+
    pub const _5_4_PLUS: YdsGradingScale = YdsGradingScale(46);
    /// 5.5-
    pub const _5_5_MINUS: YdsGradingScale = YdsGradingScale(47);
    /// 5.5+
    pub const _5_5_PLUS: YdsGradingScale = YdsGradingScale(48);
    /// 5.6-
    pub const _5_6_MINUS: YdsGradingScale = YdsGradingScale(49);
    /// 5.6+
    pub const _5_6_PLUS: YdsGradingScale = YdsGradingScale(50);
    /// 5.7-
    pub const _5_7_MINUS: YdsGradingScale = YdsGradingScale(51);
    /// 5.7+
    pub const _5_7_PLUS: YdsGradingScale = YdsGradingScale(52);
    /// 5.8-
    pub const _5_8_MINUS: YdsGradingScale = YdsGradingScale(53);
    /// 5.8+
    pub const _5_8_PLUS: YdsGradingScale = YdsGradingScale(54);
    /// 5.9-
    pub const _5_9_MINUS: YdsGradingScale = YdsGradingScale(55);
    /// 5.9+
    pub const _5_9_PLUS: YdsGradingScale = YdsGradingScale(56);
    /// 5.10-
    pub const _5_10_MINUS: YdsGradingScale = YdsGradingScale(57);
    /// 5.10+
    pub const _5_10_PLUS: YdsGradingScale = YdsGradingScale(58);
    /// 5.11-
    pub const _5_11_MINUS: YdsGradingScale = YdsGradingScale(59);
    /// 5.11+
    pub const _5_11_PLUS: YdsGradingScale = YdsGradingScale(60);
    /// 5.12-
    pub const _5_12_MINUS: YdsGradingScale = YdsGradingScale(61);
    /// 5.12+
    pub const _5_12_PLUS: YdsGradingScale = YdsGradingScale(62);
    /// 5.13-
    pub const _5_13_MINUS: YdsGradingScale = YdsGradingScale(63);
    /// 5.13+
    pub const _5_13_PLUS: YdsGradingScale = YdsGradingScale(64);
    /// 5.14-
    pub const _5_14_MINUS: YdsGradingScale = YdsGradingScale(65);
    /// 5.14+
    pub const _5_14_PLUS: YdsGradingScale = YdsGradingScale(66);
    /// 5.15-
    pub const _5_15_MINUS: YdsGradingScale = YdsGradingScale(67);
    /// 5.15+
    pub const _5_15_PLUS: YdsGradingScale = YdsGradingScale(68);

    fn as_str(self) -> Option<&'static str> {
        match self.0 {
            0 => Some("5_1"),
            1 => Some("5_2"),
            2 => Some("5_3"),
            3 => Some("5_4"),
            4 => Some("5_5"),
            5 => Some("5_6"),
            6 => Some("5_7"),
            7 => Some("5_8"),
            8 => Some("5_9"),
            9 => Some("5_10"),
            10 => Some("5_10a"),
            11 => Some("5_10b"),
            12 => Some("5_10c"),
            13 => Some("5_10d"),
            14 => Some("5_11"),
            15 => Some("5_11a"),
            16 => Some("5_11b"),
            17 => Some("5_11c"),
            18 => Some("5_11d"),
            19 => Some("5_12"),
            20 => Some("5_12a"),
            21 => Some("5_12b"),
            22 => Some("5_12c"),
            23 => Some("5_12d"),
            24 => Some("5_13"),
            25 => Some("5_13a"),
            26 => Some("5_13b"),
            27 => Some("5_13c"),
            28 => Some("5_13d"),
            29 => Some("5_14"),
            30 => Some("5_14a"),
            31 => Some("5_14b"),
            32 => Some("5_14c"),
            33 => Some("5_14d"),
            34 => Some("5_15"),
            35 => Some("5_15a"),
            36 => Some("5_15b"),
            37 => Some("5_15c"),
            38 => Some("5_15d"),
            39 => Some("5_1_minus"),
            40 => Some("5_1_plus"),
            41 => Some("5_2_minus"),
            42 => Some("5_2_plus"),
            43 => Some("5_3_minus"),
            44 => Some("5_3_plus"),
            45 => Some("5_4_minus"),
            46 => Some("5_4_plus"),
            47 => Some("5_5_minus"),
            48 => Some("5_5_plus"),
            49 => Some("5_6_minus"),
            50 => Some("5_6_plus"),
            51 => Some("5_7_minus"),
            52 => Some("5_7_plus"),
            53 => Some("5_8_minus"),
            54 => Some("5_8_plus"),
            55 => Some("5_9_minus"),
            56 => Some("5_9_plus"),
            57 => Some("5_10_minus"),
            58 => Some("5_10_plus"),
            59 => Some("5_11_minus"),
            60 => Some("5_11_plus"),
            61 => Some("5_12_minus"),
            62 => Some("5_12_plus"),
            63 => Some("5_13_minus"),
            64 => Some("5_13_plus"),
            65 => Some("5_14_minus"),
            66 => Some("5_14_plus"),
            67 => Some("5_15_minus"),
            68 => Some("5_15_plus"),
            _ => None,
        }
    }
}

impl Default for YdsGradingScale {
    fn default() -> Self {
        Self(u8::MAX)
    }
}

impl fmt::Display for YdsGradingScale {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(s) => write!(f, "{}", s),
            None => write!(f, "YdsGradingScale({})", self.0),
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for YdsGradingScale {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("YdsGradingScale", 2)?;
        if let Some(s) = self.as_str() {
            state.serialize_field("t", s)?;
        }
        state.serialize_field("c", &self.0)?;
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize))]
struct De<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<&'a str>,
    c: u8,
}

#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for YdsGradingScale {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let repr = De::deserialize(deserializer)?;
        let v = Self(repr.c);
        if let Some(t) = repr.t
            && let Some(s) = v.as_str()
            && t != s
        {
            return Err(de::Error::custom("tag and content mismatch"));
        }
        Ok(v)
    }
}
