// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use alloc::vec::Vec;

/// Aad Accel Features message.
#[derive(Debug, Clone)]
pub struct AadAccelFeatures {
    pub timestamp: typedef::DateTime,
    /// Units: s; Time interval length in seconds
    pub time: u16,
    /// Total accelerometer energy in the interval
    pub energy_total: u32,
    /// Count of zero crossings
    pub zero_cross_cnt: u16,
    /// Instance ID of zero crossing algorithm
    pub instance: u8,
    /// Scale: 25; Units: s; Total accelerometer time above threshold in the interval
    pub time_above_threshold: u16,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl AadAccelFeatures {
    /// Value's type: `u32`; ProfileType: `ProfileType::DATE_TIME`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `s`; ProfileType: `ProfileType::UINT16`
    pub const TIME: u8 = 0;
    /// Value's type: `u32`; ProfileType: `ProfileType::UINT32`
    pub const ENERGY_TOTAL: u8 = 1;
    /// Value's type: `u16`; ProfileType: `ProfileType::UINT16`
    pub const ZERO_CROSS_CNT: u8 = 2;
    /// Value's type: `u8`; ProfileType: `ProfileType::UINT8`
    pub const INSTANCE: u8 = 3;
    /// Value's type: `u16`; Scale: `25`; Units: `s`; ProfileType: `ProfileType::UINT16`
    pub const TIME_ABOVE_THRESHOLD: u8 = 4;

    /// Create new AadAccelFeatures with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            time: u16::MAX,
            energy_total: u32::MAX,
            zero_cross_cnt: u16::MAX,
            instance: u8::MAX,
            time_above_threshold: u16::MAX,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `time_above_threshold` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: s
    pub fn time_above_threshold_scaled(&self) -> Option<f64> {
        if self.time_above_threshold == u16::MAX {
            return None;
        }
        Some(self.time_above_threshold as f64 / 25.0 - 0.0)
    }

    /// Set `time_above_threshold` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_time_above_threshold_scaled(&mut self, v: f64) -> &mut Self {
        let unscaled = (v + 0.0) * 25.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.time_above_threshold = u16::MAX;
            return self;
        }
        self.time_above_threshold = unscaled as u16;
        self
    }

    fn count_valid_fields(&self) -> usize {
        (self.timestamp.0 != u32::MAX) as usize
            + (self.time != u16::MAX) as usize
            + (self.energy_total != u32::MAX) as usize
            + (self.zero_cross_cnt != u16::MAX) as usize
            + (self.instance != u8::MAX) as usize
            + (self.time_above_threshold != u16::MAX) as usize
    }
}

impl Default for AadAccelFeatures {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for AadAccelFeatures {
    /// from creates new AadAccelFeatures struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [31, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.time = field.value.as_u16(),
                1 => v.energy_total = field.value.as_u32(),
                2 => v.zero_cross_cnt = field.value.as_u16(),
                3 => v.instance = field.value.as_u8(),
                4 => v.time_above_threshold = field.value.as_u16(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<AadAccelFeatures> for Message {
    fn from(m: AadAccelFeatures) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.timestamp.0 != u32::MAX {
            fields.push(Field {
                num: 253,
                base_type: FitBaseType::UINT32,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.time != u16::MAX {
            fields.push(Field {
                num: 0,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.time),
                is_expanded: false,
            });
        };
        if m.energy_total != u32::MAX {
            fields.push(Field {
                num: 1,
                base_type: FitBaseType::UINT32,
                value: Value::Uint32(m.energy_total),
                is_expanded: false,
            });
        };
        if m.zero_cross_cnt != u16::MAX {
            fields.push(Field {
                num: 2,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.zero_cross_cnt),
                is_expanded: false,
            });
        };
        if m.instance != u8::MAX {
            fields.push(Field {
                num: 3,
                base_type: FitBaseType::UINT8,
                value: Value::Uint8(m.instance),
                is_expanded: false,
            });
        };
        if m.time_above_threshold != u16::MAX {
            fields.push(Field {
                num: 4,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.time_above_threshold),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::AAD_ACCEL_FEATURES,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
