// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

#[derive(Debug, Clone)]
/// AviationAttitude is a AviationAttitude message.
pub struct AviationAttitude {
    /// Units: s; Timestamp message was output
    pub timestamp: typedef::DateTime,
    /// Units: ms; Fractional part of timestamp, added to timestamp
    pub timestamp_ms: u16,
    /// Units: ms; System time associated with sample expressed in ms.
    pub system_time: Vec<u32>,
    /// Scale: 10430.38; Units: radians; Range -PI/2 to +PI/2
    pub pitch: Vec<i16>,
    /// Scale: 10430.38; Units: radians; Range -PI to +PI
    pub roll: Vec<i16>,
    /// Scale: 100; Units: m/s^2; Range -78.4 to +78.4 (-8 Gs to 8 Gs)
    pub accel_lateral: Vec<i16>,
    /// Scale: 100; Units: m/s^2; Range -78.4 to +78.4 (-8 Gs to 8 Gs)
    pub accel_normal: Vec<i16>,
    /// Scale: 1024; Units: radians/second; Range -8.727 to +8.727 (-500 degs/sec to +500 degs/sec)
    pub turn_rate: Vec<i16>,
    pub stage: Vec<typedef::AttitudeStage>,
    /// Units: %; The percent complete of the current attitude stage. Set to 0 for attitude stages 0, 1 and 2 and to 100 for attitude stage 3 by AHRS modules that do not support it. Range - 100
    pub attitude_stage_complete: Vec<u8>,
    /// Scale: 10430.38; Units: radians; Track Angle/Heading Range 0 - 2pi
    pub track: Vec<u16>,
    pub validity: Vec<typedef::AttitudeValidity>,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl AviationAttitude {
    /// Value's type: `u32`; Units: `s`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `ms`
    pub const TIMESTAMP_MS: u8 = 0;
    /// Value's type: `Vec<u32>`; Units: `ms`
    pub const SYSTEM_TIME: u8 = 1;
    /// Value's type: `Vec<i16>`; Scale: `10430.38`; Units: `radians`
    pub const PITCH: u8 = 2;
    /// Value's type: `Vec<i16>`; Scale: `10430.38`; Units: `radians`
    pub const ROLL: u8 = 3;
    /// Value's type: `Vec<i16>`; Scale: `100`; Units: `m/s^2`
    pub const ACCEL_LATERAL: u8 = 4;
    /// Value's type: `Vec<i16>`; Scale: `100`; Units: `m/s^2`
    pub const ACCEL_NORMAL: u8 = 5;
    /// Value's type: `Vec<i16>`; Scale: `1024`; Units: `radians/second`
    pub const TURN_RATE: u8 = 6;
    /// Value's type: `Vec<u8>`
    pub const STAGE: u8 = 7;
    /// Value's type: `Vec<u8>`; Units: `%`
    pub const ATTITUDE_STAGE_COMPLETE: u8 = 8;
    /// Value's type: `Vec<u16>`; Scale: `10430.38`; Units: `radians`
    pub const TRACK: u8 = 9;
    /// Value's type: `Vec<u16>`
    pub const VALIDITY: u8 = 10;

    /// Create new AviationAttitude with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            timestamp_ms: u16::MAX,
            system_time: Vec::new(),
            pitch: Vec::new(),
            roll: Vec::new(),
            accel_lateral: Vec::new(),
            accel_normal: Vec::new(),
            turn_rate: Vec::new(),
            stage: Vec::new(),
            attitude_stage_complete: Vec::new(),
            track: Vec::new(),
            validity: Vec::new(),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `pitch` in its scaled value. It returns `None` when value is invalid.
    pub fn pitch_scaled(&self) -> Option<Vec<f64>> {
        if self.pitch.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.pitch.len());
        for &x in &self.pitch {
            v.push(x as f64 / 10430.38 - 0.0)
        }
        Some(v)
    }

    /// Set `pitch` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_pitch_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.pitch = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 10430.38;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > i16::MAX as f64 {
                self.pitch.push(i16::MAX);
                continue;
            }
            self.pitch.push(unscaled as i16);
        }
        self
    }

    /// Returns `roll` in its scaled value. It returns `None` when value is invalid.
    pub fn roll_scaled(&self) -> Option<Vec<f64>> {
        if self.roll.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.roll.len());
        for &x in &self.roll {
            v.push(x as f64 / 10430.38 - 0.0)
        }
        Some(v)
    }

    /// Set `roll` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_roll_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.roll = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 10430.38;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > i16::MAX as f64 {
                self.roll.push(i16::MAX);
                continue;
            }
            self.roll.push(unscaled as i16);
        }
        self
    }

    /// Returns `accel_lateral` in its scaled value. It returns `None` when value is invalid.
    pub fn accel_lateral_scaled(&self) -> Option<Vec<f64>> {
        if self.accel_lateral.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.accel_lateral.len());
        for &x in &self.accel_lateral {
            v.push(x as f64 / 100.0 - 0.0)
        }
        Some(v)
    }

    /// Set `accel_lateral` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_accel_lateral_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.accel_lateral = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 100.0;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > i16::MAX as f64 {
                self.accel_lateral.push(i16::MAX);
                continue;
            }
            self.accel_lateral.push(unscaled as i16);
        }
        self
    }

    /// Returns `accel_normal` in its scaled value. It returns `None` when value is invalid.
    pub fn accel_normal_scaled(&self) -> Option<Vec<f64>> {
        if self.accel_normal.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.accel_normal.len());
        for &x in &self.accel_normal {
            v.push(x as f64 / 100.0 - 0.0)
        }
        Some(v)
    }

    /// Set `accel_normal` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_accel_normal_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.accel_normal = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 100.0;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > i16::MAX as f64 {
                self.accel_normal.push(i16::MAX);
                continue;
            }
            self.accel_normal.push(unscaled as i16);
        }
        self
    }

    /// Returns `turn_rate` in its scaled value. It returns `None` when value is invalid.
    pub fn turn_rate_scaled(&self) -> Option<Vec<f64>> {
        if self.turn_rate.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.turn_rate.len());
        for &x in &self.turn_rate {
            v.push(x as f64 / 1024.0 - 0.0)
        }
        Some(v)
    }

    /// Set `turn_rate` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_turn_rate_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.turn_rate = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 1024.0;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > i16::MAX as f64 {
                self.turn_rate.push(i16::MAX);
                continue;
            }
            self.turn_rate.push(unscaled as i16);
        }
        self
    }

    /// Returns `track` in its scaled value. It returns `None` when value is invalid.
    pub fn track_scaled(&self) -> Option<Vec<f64>> {
        if self.track.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.track.len());
        for &x in &self.track {
            v.push(x as f64 / 10430.38 - 0.0)
        }
        Some(v)
    }

    /// Set `track` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_track_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.track = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 10430.38;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
                self.track.push(u16::MAX);
                continue;
            }
            self.track.push(unscaled as u16);
        }
        self
    }

    fn count_valid_fields(&self) -> usize {
        (self.timestamp != typedef::DateTime(u32::MAX)) as usize
            + (self.timestamp_ms != u16::MAX) as usize
            + (!self.system_time.is_empty()) as usize
            + (!self.pitch.is_empty()) as usize
            + (!self.roll.is_empty()) as usize
            + (!self.accel_lateral.is_empty()) as usize
            + (!self.accel_normal.is_empty()) as usize
            + (!self.turn_rate.is_empty()) as usize
            + (!self.stage.is_empty()) as usize
            + (!self.attitude_stage_complete.is_empty()) as usize
            + (!self.track.is_empty()) as usize
            + (!self.validity.is_empty()) as usize
    }
}

impl Default for AviationAttitude {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for AviationAttitude {
    /// from creates new AviationAttitude struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [2047, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.timestamp_ms = field.value.as_u16(),
                1 => v.system_time = field.value.to_vec_u32(),
                2 => v.pitch = field.value.to_vec_i16(),
                3 => v.roll = field.value.to_vec_i16(),
                4 => v.accel_lateral = field.value.to_vec_i16(),
                5 => v.accel_normal = field.value.to_vec_i16(),
                6 => v.turn_rate = field.value.to_vec_i16(),
                7 => {
                    v.stage = match &field.value {
                        Value::VecUint8(v) => {
                            let mut vs = Vec::with_capacity(v.len());
                            vs.extend(v.iter().map(|&x| typedef::AttitudeStage(x)));
                            vs
                        }
                        _ => Vec::new(),
                    }
                }
                8 => v.attitude_stage_complete = field.value.to_vec_u8(),
                9 => v.track = field.value.to_vec_u16(),
                10 => {
                    v.validity = match &field.value {
                        Value::VecUint16(v) => {
                            let mut vs = Vec::with_capacity(v.len());
                            vs.extend(v.iter().map(|&x| typedef::AttitudeValidity(x)));
                            vs
                        }
                        _ => Vec::new(),
                    }
                }
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<AviationAttitude> for Message {
    fn from(m: AviationAttitude) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.timestamp != typedef::DateTime(u32::MAX) {
            fields.push(Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.timestamp_ms != u16::MAX {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.timestamp_ms),
                is_expanded: false,
            });
        };
        if !m.system_time.is_empty() {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::UINT32,
                value: Value::VecUint32(m.system_time),
                is_expanded: false,
            });
        };
        if !m.pitch.is_empty() {
            fields.push(Field {
                num: 2,
                profile_type: ProfileType::SINT16,
                value: Value::VecInt16(m.pitch),
                is_expanded: false,
            });
        };
        if !m.roll.is_empty() {
            fields.push(Field {
                num: 3,
                profile_type: ProfileType::SINT16,
                value: Value::VecInt16(m.roll),
                is_expanded: false,
            });
        };
        if !m.accel_lateral.is_empty() {
            fields.push(Field {
                num: 4,
                profile_type: ProfileType::SINT16,
                value: Value::VecInt16(m.accel_lateral),
                is_expanded: false,
            });
        };
        if !m.accel_normal.is_empty() {
            fields.push(Field {
                num: 5,
                profile_type: ProfileType::SINT16,
                value: Value::VecInt16(m.accel_normal),
                is_expanded: false,
            });
        };
        if !m.turn_rate.is_empty() {
            fields.push(Field {
                num: 6,
                profile_type: ProfileType::SINT16,
                value: Value::VecInt16(m.turn_rate),
                is_expanded: false,
            });
        };
        if !m.stage.is_empty() {
            fields.push(Field {
                num: 7,
                profile_type: ProfileType::ATTITUDE_STAGE,
                value: Value::VecUint8({
                    let (ptr, len, capacity) = m.stage.into_raw_parts();
                    unsafe { Vec::from_raw_parts(ptr.cast::<u8>(), len, capacity) }
                }),
                is_expanded: false,
            });
        };
        if !m.attitude_stage_complete.is_empty() {
            fields.push(Field {
                num: 8,
                profile_type: ProfileType::UINT8,
                value: Value::VecUint8(m.attitude_stage_complete),
                is_expanded: false,
            });
        };
        if !m.track.is_empty() {
            fields.push(Field {
                num: 9,
                profile_type: ProfileType::UINT16,
                value: Value::VecUint16(m.track),
                is_expanded: false,
            });
        };
        if !m.validity.is_empty() {
            fields.push(Field {
                num: 10,
                profile_type: ProfileType::ATTITUDE_VALIDITY,
                value: Value::VecUint16({
                    let (ptr, len, capacity) = m.validity.into_raw_parts();
                    unsafe { Vec::from_raw_parts(ptr.cast::<u16>(), len, capacity) }
                }),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::AVIATION_ATTITUDE,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
