// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// CameraEvent is a CameraEvent message.
pub struct CameraEvent {
    /// Units: s; Whole second part of the timestamp.
    pub timestamp: typedef::DateTime,
    /// Units: ms; Millisecond part of the timestamp.
    pub timestamp_ms: u16,
    pub camera_event_type: typedef::CameraEventType,
    pub camera_file_uuid: String,
    pub camera_orientation: typedef::CameraOrientationType,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl CameraEvent {
    /// Value's type: `u32`; Units: `s`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `ms`
    pub const TIMESTAMP_MS: u8 = 0;
    /// Value's type: `u8`
    pub const CAMERA_EVENT_TYPE: u8 = 1;
    /// Value's type: `String`
    pub const CAMERA_FILE_UUID: u8 = 2;
    /// Value's type: `u8`
    pub const CAMERA_ORIENTATION: u8 = 3;

    /// Create new CameraEvent with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            timestamp_ms: u16::MAX,
            camera_event_type: typedef::CameraEventType(u8::MAX),
            camera_file_uuid: String::new(),
            camera_orientation: typedef::CameraOrientationType(u8::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }
}

impl Default for CameraEvent {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for CameraEvent {
    /// from creates new CameraEvent struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 254] = [const { &Value::Invalid }; 254];

        const KNOWN_NUMS: [u64; 4] = [15, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }
        let mut unknown_fields: Vec<Field> = Vec::with_capacity(n as usize);

        for field in &mesg.fields {
            if (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 == 0 {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            timestamp: typedef::DateTime(vals[253].as_u32()),
            timestamp_ms: vals[0].as_u16(),
            camera_event_type: typedef::CameraEventType(vals[1].as_u8()),
            camera_file_uuid: vals[2].as_string(),
            camera_orientation: typedef::CameraOrientationType(vals[3].as_u8()),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<CameraEvent> for Message {
    fn from(m: CameraEvent) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 5];
        let mut len = 0usize;

        if m.timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.timestamp_ms != u16::MAX {
            arr[len] = Field {
                num: 0,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.timestamp_ms),
                is_expanded: false,
            };
            len += 1;
        }
        if m.camera_event_type != typedef::CameraEventType(u8::MAX) {
            arr[len] = Field {
                num: 1,
                profile_type: ProfileType::CAMERA_EVENT_TYPE,
                value: Value::Uint8(m.camera_event_type.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.camera_file_uuid != String::new() {
            arr[len] = Field {
                num: 2,
                profile_type: ProfileType::STRING,
                value: Value::String(m.camera_file_uuid),
                is_expanded: false,
            };
            len += 1;
        }
        if m.camera_orientation != typedef::CameraOrientationType(u8::MAX) {
            arr[len] = Field {
                num: 3,
                profile_type: ProfileType::CAMERA_ORIENTATION_TYPE,
                value: Value::Uint8(m.camera_orientation.0),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::CAMERA_EVENT,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
