// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// FileCapabilities is a FileCapabilities message.
pub struct FileCapabilities {
    pub message_index: typedef::MessageIndex,
    pub r#type: typedef::File,
    pub flags: typedef::FileFlags,
    pub directory: String,
    pub max_count: u16,
    /// Units: bytes
    pub max_size: u32,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl FileCapabilities {
    /// Value's type: `u16`
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u8`
    pub const TYPE: u8 = 0;
    /// Value's type: `u8`
    pub const FLAGS: u8 = 1;
    /// Value's type: `String`
    pub const DIRECTORY: u8 = 2;
    /// Value's type: `u16`
    pub const MAX_COUNT: u8 = 3;
    /// Value's type: `u32`; Units: `bytes`
    pub const MAX_SIZE: u8 = 4;

    /// Create new FileCapabilities with all fields being set to its corresponding invalid value.
    pub fn new() -> Self {
        Self::from(&Message::default())
    }
}

impl Default for FileCapabilities {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for FileCapabilities {
    /// from creates new FileCapabilities struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 255] = [const { &Value::Invalid }; 255];

        const KNOWN_NUMS: [u64; 4] = [31, 0, 0, 4611686018427387904];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }
        let mut unknown_fields: Vec<Field> = Vec::with_capacity(n as usize);

        for field in &mesg.fields {
            if (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 == 0 {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            message_index: typedef::MessageIndex(vals[254].as_u16()),
            r#type: typedef::File(vals[0].as_u8()),
            flags: typedef::FileFlags(vals[1].as_u8z()),
            directory: vals[2].as_string(),
            max_count: vals[3].as_u16(),
            max_size: vals[4].as_u32(),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<FileCapabilities> for Message {
    fn from(m: FileCapabilities) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 6];
        let mut len = 0usize;

        if m.message_index != typedef::MessageIndex(u16::MAX) {
            arr[len] = Field {
                num: 254,
                profile_type: ProfileType::MESSAGE_INDEX,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.r#type != typedef::File(u8::MAX) {
            arr[len] = Field {
                num: 0,
                profile_type: ProfileType::FILE,
                value: Value::Uint8(m.r#type.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.flags != typedef::FileFlags(u8::MIN) {
            arr[len] = Field {
                num: 1,
                profile_type: ProfileType::FILE_FLAGS,
                value: Value::Uint8(m.flags.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.directory != String::new() {
            arr[len] = Field {
                num: 2,
                profile_type: ProfileType::STRING,
                value: Value::String(m.directory),
                is_expanded: false,
            };
            len += 1;
        }
        if m.max_count != u16::MAX {
            arr[len] = Field {
                num: 3,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.max_count),
                is_expanded: false,
            };
            len += 1;
        }
        if m.max_size != u32::MAX {
            arr[len] = Field {
                num: 4,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.max_size),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::FILE_CAPABILITIES,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
