// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use alloc::vec::Vec;
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize, Serializer, ser::SerializeStruct};

/// Hrm Profile message.
#[cfg_attr(feature = "serde", derive(Deserialize), serde(from = "De"))]
#[derive(Debug, Clone)]
pub struct HrmProfile {
    pub message_index: typedef::MessageIndex,
    pub enabled: typedef::Bool,
    /// Base: UINT16Z
    pub hrm_ant_id: u16,
    pub log_hrv: typedef::Bool,
    /// Base: UINT8Z
    pub hrm_ant_id_trans_type: u8,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl HrmProfile {
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::MessageIndex
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u8`; FitBaseType::ENUM; ProfileType::Bool
    pub const ENABLED: u8 = 0;
    /// Value's type: `u16`; FitBaseType::UINT16Z; ProfileType::Uint16z
    pub const HRM_ANT_ID: u8 = 1;
    /// Value's type: `u8`; FitBaseType::ENUM; ProfileType::Bool
    pub const LOG_HRV: u8 = 2;
    /// Value's type: `u8`; FitBaseType::UINT8Z; ProfileType::Uint8z
    pub const HRM_ANT_ID_TRANS_TYPE: u8 = 3;

    /// Create new HrmProfile with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            enabled: typedef::Bool(u8::MAX),
            hrm_ant_id: u16::MIN,
            log_hrv: typedef::Bool(u8::MAX),
            hrm_ant_id_trans_type: u8::MIN,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index.0 != u16::MAX) as usize
            + (self.enabled.0 != u8::MAX) as usize
            + (self.hrm_ant_id != u16::MIN) as usize
            + (self.log_hrv.0 != u8::MAX) as usize
            + (self.hrm_ant_id_trans_type != u8::MIN) as usize
    }
}

impl Default for HrmProfile {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for HrmProfile {
    /// from creates new HrmProfile struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [15, 0, 0, 4611686018427387904];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                0 => v.enabled = typedef::Bool(field.value.as_u8()),
                1 => v.hrm_ant_id = field.value.as_u16z(),
                2 => v.log_hrv = typedef::Bool(field.value.as_u8()),
                3 => v.hrm_ant_id_trans_type = field.value.as_u8z(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<HrmProfile> for Message {
    fn from(m: HrmProfile) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index.0 != u16::MAX {
            fields.push(Field {
                num: 254,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.enabled.0 != u8::MAX {
            fields.push(Field {
                num: 0,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.enabled.0),
                is_expanded: false,
            });
        };
        if m.hrm_ant_id != u16::MIN {
            fields.push(Field {
                num: 1,
                base_type: FitBaseType::UINT16Z,
                value: Value::Uint16(m.hrm_ant_id),
                is_expanded: false,
            });
        };
        if m.log_hrv.0 != u8::MAX {
            fields.push(Field {
                num: 2,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.log_hrv.0),
                is_expanded: false,
            });
        };
        if m.hrm_ant_id_trans_type != u8::MIN {
            fields.push(Field {
                num: 3,
                base_type: FitBaseType::UINT8Z,
                value: Value::Uint8(m.hrm_ant_id_trans_type),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::HRM_PROFILE,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for HrmProfile {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let n = self.count_valid_fields() + 2;
        let mut state = serializer.serialize_struct("HrmProfile", n)?;
        if self.message_index.0 != u16::MAX {
            state.serialize_field("message_index", &self.message_index)?;
        }
        if self.enabled.0 != u8::MAX {
            state.serialize_field("enabled", &self.enabled)?;
        }
        if self.hrm_ant_id != u16::MIN {
            state.serialize_field("hrm_ant_id", &self.hrm_ant_id)?;
        }
        if self.log_hrv.0 != u8::MAX {
            state.serialize_field("log_hrv", &self.log_hrv)?;
        }
        if self.hrm_ant_id_trans_type != u8::MIN {
            state.serialize_field("hrm_ant_id_trans_type", &self.hrm_ant_id_trans_type)?;
        }
        if !self.unknown_fields.is_empty() {
            state.serialize_field("unknown_fields", &self.unknown_fields)?;
        }
        if !self.developer_fields.is_empty() {
            state.serialize_field("developer_fields", &self.developer_fields)?;
        }
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize), serde(default))]
struct De {
    message_index: typedef::MessageIndex,
    enabled: typedef::Bool,
    hrm_ant_id: u16,
    log_hrv: typedef::Bool,
    hrm_ant_id_trans_type: u8,
    unknown_fields: Vec<Field>,
    developer_fields: Vec<DeveloperField>,
}

#[cfg(feature = "serde")]
impl From<De> for HrmProfile {
    fn from(m: De) -> Self {
        Self {
            message_index: m.message_index,
            enabled: m.enabled,
            hrm_ant_id: m.hrm_ant_id,
            log_hrv: m.log_hrv,
            hrm_ant_id_trans_type: m.hrm_ant_id_trans_type,
            unknown_fields: m.unknown_fields,
            developer_fields: m.developer_fields,
        }
    }
}

#[cfg(feature = "serde")]
impl Default for De {
    fn default() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            enabled: typedef::Bool(u8::MAX),
            hrm_ant_id: u16::MIN,
            log_hrv: typedef::Bool(u8::MAX),
            hrm_ant_id_trans_type: u8::MIN,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }
}
