// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

/// Hrv message.
#[derive(Debug, Clone)]
pub struct Hrv {
    /// Scale: 1000; Units: s; Time between beats
    pub time: Vec<u16>,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl Hrv {
    /// Value's type: `Vec<u16>`; Scale: `1000`; Units: `s`; ProfileType: `ProfileType::UINT16`
    pub const TIME: u8 = 0;

    /// Create new Hrv with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            time: Vec::new(),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `time` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: s
    pub fn time_scaled(&self) -> Option<Vec<f64>> {
        if self.time.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.time.len());
        for &x in &self.time {
            v.push(x as f64 / 1000.0 - 0.0)
        }
        Some(v)
    }

    /// Set `time` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_time_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.time = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 1000.0;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
                self.time.push(u16::MAX);
                continue;
            }
            self.time.push(unscaled as u16);
        }
        self
    }

    fn count_valid_fields(&self) -> usize {
        (!self.time.is_empty()) as usize
    }
}

impl Default for Hrv {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for Hrv {
    /// from creates new Hrv struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [1, 0, 0, 0];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                0 => v.time = field.value.to_vec_u16(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<Hrv> for Message {
    fn from(m: Hrv) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if !m.time.is_empty() {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::UINT16,
                value: Value::VecUint16(m.time),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::HRV,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
