// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

#[derive(Debug, Clone)]
/// HsaStepData is a HsaStepData message.
pub struct HsaStepData {
    /// Units: s
    pub timestamp: typedef::DateTime,
    /// Units: s; Processing interval length in seconds. File start: 0xFFFFFFEF File stop: 0xFFFFFFEE
    pub processing_interval: u16,
    /// Units: steps; Total step sum
    pub steps: Vec<u32>,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl HsaStepData {
    /// Value's type: `u32`; Units: `s`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `s`
    pub const PROCESSING_INTERVAL: u8 = 0;
    /// Value's type: `Vec<u32>`; Units: `steps`
    pub const STEPS: u8 = 1;

    /// Create new HsaStepData with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            processing_interval: u16::MAX,
            steps: Vec::new(),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.timestamp != typedef::DateTime(u32::MAX)) as usize
            + (self.processing_interval != u16::MAX) as usize
            + (!self.steps.is_empty()) as usize
    }
}

impl Default for HsaStepData {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for HsaStepData {
    /// from creates new HsaStepData struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [3, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.processing_interval = field.value.as_u16(),
                1 => v.steps = field.value.to_vec_u32(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<HsaStepData> for Message {
    fn from(m: HsaStepData) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.timestamp != typedef::DateTime(u32::MAX) {
            fields.push(Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.processing_interval != u16::MAX {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.processing_interval),
                is_expanded: false,
            });
        };
        if !m.steps.is_empty() {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::UINT32,
                value: Value::VecUint32(m.steps),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::HSA_STEP_DATA,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
