// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, lookup, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// HsaRespirationData is a HsaRespirationData message.
pub struct HsaRespirationData {
    /// Units: s
    pub timestamp: typedef::DateTime,
    /// Units: s; Processing interval length in seconds
    pub processing_interval: u16,
    /// Scale: 100; Units: breaths/min; Breaths / min: [1,100] Invalid: 255 Excess motion: 254 Off wrist: 253 Not available: 252 Blank: 2.4
    pub respiration_rate: Vec<i16>,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl HsaRespirationData {
    /// Value's type: `u32`; Units: `s`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `s`
    pub const PROCESSING_INTERVAL: u8 = 0;
    /// Value's type: `Vec<i16>`; Scale: `100` ; Units: `breaths/min`
    pub const RESPIRATION_RATE: u8 = 1;

    /// Create new HsaRespirationData with all fields being set to its corresponding invalid value.
    pub fn new() -> Self {
        Self::from(&Message::default())
    }

    /// Returns `respiration_rate` in its scaled value. It returns invalid f64 when value is valid.
    pub fn respiration_rate_scaled(&self) -> Vec<f64> {
        if self.respiration_rate == Vec::<i16>::new() {
            return Vec::new();
        }
        let mut v = Vec::with_capacity(self.respiration_rate.len());
        for &x in &self.respiration_rate {
            v.push(x as f64 / 100.0 - 0.0)
        }
        v
    }

    /// Set `respiration_rate` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_respiration_rate_scaled(&mut self, v: &Vec<f64>) -> &mut HsaRespirationData {
        if v.is_empty() {
            self.respiration_rate = Vec::new();
            return self;
        }
        self.respiration_rate = Vec::with_capacity(v.len());
        for &x in v {
            let unscaled = (x + 0.0) * 100.0;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > i16::MAX as f64 {
                self.respiration_rate.push(i16::MAX);
                continue;
            }
            self.respiration_rate.push(unscaled as i16);
        }
        self
    }
}

impl Default for HsaRespirationData {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for HsaRespirationData {
    /// from creates new HsaRespirationData struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 254] = [const { &Value::Invalid }; 254];
        let mut unknown_fields: Vec<Field> = Vec::new();

        for field in &mesg.fields {
            if lookup::field_reference(mesg.num, field.num).is_none() {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            timestamp: typedef::DateTime(vals[253].as_u32()),
            processing_interval: vals[0].as_u16(),
            respiration_rate: vals[1].as_vec_i16(),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<HsaRespirationData> for Message {
    fn from(m: HsaRespirationData) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                base_type: typedef::FitBaseType(0),
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 3];
        let mut len = 0usize;

        if m.timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 253,
                base_type: typedef::FitBaseType::UINT32,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.processing_interval != u16::MAX {
            arr[len] = Field {
                num: 0,
                base_type: typedef::FitBaseType::UINT16,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.processing_interval),
                is_expanded: false,
            };
            len += 1;
        }
        if m.respiration_rate != Vec::<i16>::new() {
            arr[len] = Field {
                num: 1,
                base_type: typedef::FitBaseType::SINT16,
                profile_type: ProfileType::SINT16,
                value: Value::VecInt16(m.respiration_rate),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::HSA_RESPIRATION_DATA,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
