// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use alloc::vec::Vec;

/// Magnetometer Data message.
#[derive(Debug, Clone)]
pub struct MagnetometerData {
    /// Units: s; Whole second part of the timestamp
    pub timestamp: typedef::DateTime,
    /// Units: ms; Millisecond part of the timestamp.
    pub timestamp_ms: u16,
    /// Units: ms; Each time in the array describes the time at which the compass sample with the corresponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in cmps_x and cmps_y and cmps_z
    pub sample_time_offset: Vec<u16>,
    /// Units: counts; These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    pub mag_x: Vec<u16>,
    /// Units: counts; These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    pub mag_y: Vec<u16>,
    /// Units: counts; These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    pub mag_z: Vec<u16>,
    /// Units: G; Calibrated Magnetometer reading
    pub calibrated_mag_x: Vec<f32>,
    /// Units: G; Calibrated Magnetometer reading
    pub calibrated_mag_y: Vec<f32>,
    /// Units: G; Calibrated Magnetometer reading
    pub calibrated_mag_z: Vec<f32>,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl MagnetometerData {
    /// Value's type: `u32`; Units: `s`; ProfileType: `ProfileType::DATE_TIME`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `ms`; ProfileType: `ProfileType::UINT16`
    pub const TIMESTAMP_MS: u8 = 0;
    /// Value's type: `Vec<u16>`; Units: `ms`; ProfileType: `ProfileType::UINT16`
    pub const SAMPLE_TIME_OFFSET: u8 = 1;
    /// Value's type: `Vec<u16>`; Units: `counts`; ProfileType: `ProfileType::UINT16`
    pub const MAG_X: u8 = 2;
    /// Value's type: `Vec<u16>`; Units: `counts`; ProfileType: `ProfileType::UINT16`
    pub const MAG_Y: u8 = 3;
    /// Value's type: `Vec<u16>`; Units: `counts`; ProfileType: `ProfileType::UINT16`
    pub const MAG_Z: u8 = 4;
    /// Value's type: `Vec<f32>`; Units: `G`; ProfileType: `ProfileType::FLOAT32`
    pub const CALIBRATED_MAG_X: u8 = 5;
    /// Value's type: `Vec<f32>`; Units: `G`; ProfileType: `ProfileType::FLOAT32`
    pub const CALIBRATED_MAG_Y: u8 = 6;
    /// Value's type: `Vec<f32>`; Units: `G`; ProfileType: `ProfileType::FLOAT32`
    pub const CALIBRATED_MAG_Z: u8 = 7;

    /// Create new MagnetometerData with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            timestamp_ms: u16::MAX,
            sample_time_offset: Vec::new(),
            mag_x: Vec::new(),
            mag_y: Vec::new(),
            mag_z: Vec::new(),
            calibrated_mag_x: Vec::new(),
            calibrated_mag_y: Vec::new(),
            calibrated_mag_z: Vec::new(),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.timestamp.0 != u32::MAX) as usize
            + (self.timestamp_ms != u16::MAX) as usize
            + (!self.sample_time_offset.is_empty()) as usize
            + (!self.mag_x.is_empty()) as usize
            + (!self.mag_y.is_empty()) as usize
            + (!self.mag_z.is_empty()) as usize
            + (!self.calibrated_mag_x.is_empty()) as usize
            + (!self.calibrated_mag_y.is_empty()) as usize
            + (!self.calibrated_mag_z.is_empty()) as usize
    }
}

impl Default for MagnetometerData {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for MagnetometerData {
    /// from creates new MagnetometerData struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [255, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.timestamp_ms = field.value.as_u16(),
                1 => v.sample_time_offset = field.value.to_vec_u16(),
                2 => v.mag_x = field.value.to_vec_u16(),
                3 => v.mag_y = field.value.to_vec_u16(),
                4 => v.mag_z = field.value.to_vec_u16(),
                5 => v.calibrated_mag_x = field.value.to_vec_f32(),
                6 => v.calibrated_mag_y = field.value.to_vec_f32(),
                7 => v.calibrated_mag_z = field.value.to_vec_f32(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<MagnetometerData> for Message {
    fn from(m: MagnetometerData) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.timestamp.0 != u32::MAX {
            fields.push(Field {
                num: 253,
                base_type: FitBaseType::UINT32,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.timestamp_ms != u16::MAX {
            fields.push(Field {
                num: 0,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.timestamp_ms),
                is_expanded: false,
            });
        };
        if !m.sample_time_offset.is_empty() {
            fields.push(Field {
                num: 1,
                base_type: FitBaseType::UINT16,
                value: Value::VecUint16(m.sample_time_offset),
                is_expanded: false,
            });
        };
        if !m.mag_x.is_empty() {
            fields.push(Field {
                num: 2,
                base_type: FitBaseType::UINT16,
                value: Value::VecUint16(m.mag_x),
                is_expanded: false,
            });
        };
        if !m.mag_y.is_empty() {
            fields.push(Field {
                num: 3,
                base_type: FitBaseType::UINT16,
                value: Value::VecUint16(m.mag_y),
                is_expanded: false,
            });
        };
        if !m.mag_z.is_empty() {
            fields.push(Field {
                num: 4,
                base_type: FitBaseType::UINT16,
                value: Value::VecUint16(m.mag_z),
                is_expanded: false,
            });
        };
        if !m.calibrated_mag_x.is_empty() {
            fields.push(Field {
                num: 5,
                base_type: FitBaseType::FLOAT32,
                value: Value::VecFloat32(m.calibrated_mag_x),
                is_expanded: false,
            });
        };
        if !m.calibrated_mag_y.is_empty() {
            fields.push(Field {
                num: 6,
                base_type: FitBaseType::FLOAT32,
                value: Value::VecFloat32(m.calibrated_mag_y),
                is_expanded: false,
            });
        };
        if !m.calibrated_mag_z.is_empty() {
            fields.push(Field {
                num: 7,
                base_type: FitBaseType::FLOAT32,
                value: Value::VecFloat32(m.calibrated_mag_z),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::MAGNETOMETER_DATA,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
