// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

#[derive(Debug, Clone)]
/// MemoGlob is a MemoGlob message.
pub struct MemoGlob {
    /// Sequence number of memo blocks
    pub part_index: u32,
    /// Deprecated. Use data field.
    pub memo: Vec<u8>,
    /// Message Number of the parent message
    pub mesg_num: typedef::MesgNum,
    /// Index of mesg that this glob is associated with.
    pub parent_index: typedef::MessageIndex,
    /// Field within the parent that this glob is associated with
    pub field_num: u8,
    /// Base: UINT8Z; Block of utf8 bytes. Note, mutltibyte characters may be split across adjoining memo_glob messages.
    pub data: Vec<u8>,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl MemoGlob {
    /// Value's type: `u32`
    pub const PART_INDEX: u8 = 250;
    /// Value's type: `Vec<u8>`
    pub const MEMO: u8 = 0;
    /// Value's type: `u16`
    pub const MESG_NUM: u8 = 1;
    /// Value's type: `u16`
    pub const PARENT_INDEX: u8 = 2;
    /// Value's type: `u8`
    pub const FIELD_NUM: u8 = 3;
    /// Value's type: `Vec<u8>`; Base: UINT8Z
    pub const DATA: u8 = 4;

    /// Create new MemoGlob with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            part_index: u32::MAX,
            memo: Vec::new(),
            mesg_num: typedef::MesgNum(u16::MAX),
            parent_index: typedef::MessageIndex(u16::MAX),
            field_num: u8::MAX,
            data: Vec::new(),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.part_index != u32::MAX) as usize
            + (!self.memo.is_empty()) as usize
            + (self.mesg_num != typedef::MesgNum(u16::MAX)) as usize
            + (self.parent_index != typedef::MessageIndex(u16::MAX)) as usize
            + (self.field_num != u8::MAX) as usize
            + (!self.data.is_empty()) as usize
    }
}

impl Default for MemoGlob {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for MemoGlob {
    /// from creates new MemoGlob struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [31, 0, 0, 288230376151711744];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                250 => v.part_index = field.value.as_u32(),
                0 => v.memo = field.value.to_vec_u8(),
                1 => v.mesg_num = typedef::MesgNum(field.value.as_u16()),
                2 => v.parent_index = typedef::MessageIndex(field.value.as_u16()),
                3 => v.field_num = field.value.as_u8(),
                4 => v.data = field.value.to_vec_u8(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<MemoGlob> for Message {
    fn from(m: MemoGlob) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.part_index != u32::MAX {
            fields.push(Field {
                num: 250,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.part_index),
                is_expanded: false,
            });
        };
        if !m.memo.is_empty() {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::BYTE,
                value: Value::VecUint8(m.memo),
                is_expanded: false,
            });
        };
        if m.mesg_num != typedef::MesgNum(u16::MAX) {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::MESG_NUM,
                value: Value::Uint16(m.mesg_num.0),
                is_expanded: false,
            });
        };
        if m.parent_index != typedef::MessageIndex(u16::MAX) {
            fields.push(Field {
                num: 2,
                profile_type: ProfileType::MESSAGE_INDEX,
                value: Value::Uint16(m.parent_index.0),
                is_expanded: false,
            });
        };
        if m.field_num != u8::MAX {
            fields.push(Field {
                num: 3,
                profile_type: ProfileType::UINT8,
                value: Value::Uint8(m.field_num),
                is_expanded: false,
            });
        };
        if !m.data.is_empty() {
            fields.push(Field {
                num: 4,
                profile_type: ProfileType::UINT8Z,
                value: Value::VecUint8(m.data),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::MEMO_GLOB,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
