// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

/// Nap Event message.
#[derive(Debug, Clone)]
pub struct NapEvent {
    pub message_index: typedef::MessageIndex,
    pub timestamp: typedef::DateTime,
    /// Units: seconds
    pub start_time: typedef::DateTime,
    /// Units: minutes
    pub start_timezone_offset: i16,
    /// Units: seconds
    pub end_time: typedef::DateTime,
    /// Units: minutes
    pub end_timezone_offset: i16,
    pub feedback: typedef::NapPeriodFeedback,
    pub is_deleted: typedef::Bool,
    pub source: typedef::NapSource,
    /// The timestamp representing when this nap event was last updated
    pub update_timestamp: typedef::DateTime,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl NapEvent {
    /// Value's type: `u16`; ProfileType: `ProfileType::MESSAGE_INDEX`
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u32`; ProfileType: `ProfileType::DATE_TIME`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u32`; Units: `seconds`; ProfileType: `ProfileType::DATE_TIME`
    pub const START_TIME: u8 = 0;
    /// Value's type: `i16`; Units: `minutes`; ProfileType: `ProfileType::SINT16`
    pub const START_TIMEZONE_OFFSET: u8 = 1;
    /// Value's type: `u32`; Units: `seconds`; ProfileType: `ProfileType::DATE_TIME`
    pub const END_TIME: u8 = 2;
    /// Value's type: `i16`; Units: `minutes`; ProfileType: `ProfileType::SINT16`
    pub const END_TIMEZONE_OFFSET: u8 = 3;
    /// Value's type: `u8`; ProfileType: `ProfileType::NAP_PERIOD_FEEDBACK`
    pub const FEEDBACK: u8 = 4;
    /// Value's type: `u8`; ProfileType: `ProfileType::BOOL`
    pub const IS_DELETED: u8 = 5;
    /// Value's type: `u8`; ProfileType: `ProfileType::NAP_SOURCE`
    pub const SOURCE: u8 = 6;
    /// Value's type: `u32`; ProfileType: `ProfileType::DATE_TIME`
    pub const UPDATE_TIMESTAMP: u8 = 7;

    /// Create new NapEvent with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            timestamp: typedef::DateTime(u32::MAX),
            start_time: typedef::DateTime(u32::MAX),
            start_timezone_offset: i16::MAX,
            end_time: typedef::DateTime(u32::MAX),
            end_timezone_offset: i16::MAX,
            feedback: typedef::NapPeriodFeedback(u8::MAX),
            is_deleted: typedef::Bool(u8::MAX),
            source: typedef::NapSource(u8::MAX),
            update_timestamp: typedef::DateTime(u32::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index.0 != u16::MAX) as usize
            + (self.timestamp.0 != u32::MAX) as usize
            + (self.start_time.0 != u32::MAX) as usize
            + (self.start_timezone_offset != i16::MAX) as usize
            + (self.end_time.0 != u32::MAX) as usize
            + (self.end_timezone_offset != i16::MAX) as usize
            + (self.feedback.0 != u8::MAX) as usize
            + (self.is_deleted.0 != u8::MAX) as usize
            + (self.source.0 != u8::MAX) as usize
            + (self.update_timestamp.0 != u32::MAX) as usize
    }
}

impl Default for NapEvent {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for NapEvent {
    /// from creates new NapEvent struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [255, 0, 0, 6917529027641081856];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.start_time = typedef::DateTime(field.value.as_u32()),
                1 => v.start_timezone_offset = field.value.as_i16(),
                2 => v.end_time = typedef::DateTime(field.value.as_u32()),
                3 => v.end_timezone_offset = field.value.as_i16(),
                4 => v.feedback = typedef::NapPeriodFeedback(field.value.as_u8()),
                5 => v.is_deleted = typedef::Bool(field.value.as_u8()),
                6 => v.source = typedef::NapSource(field.value.as_u8()),
                7 => v.update_timestamp = typedef::DateTime(field.value.as_u32()),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<NapEvent> for Message {
    fn from(m: NapEvent) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index.0 != u16::MAX {
            fields.push(Field {
                num: 254,
                profile_type: ProfileType::MESSAGE_INDEX,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.timestamp.0 != u32::MAX {
            fields.push(Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.start_time.0 != u32::MAX {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.start_time.0),
                is_expanded: false,
            });
        };
        if m.start_timezone_offset != i16::MAX {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::SINT16,
                value: Value::Int16(m.start_timezone_offset),
                is_expanded: false,
            });
        };
        if m.end_time.0 != u32::MAX {
            fields.push(Field {
                num: 2,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.end_time.0),
                is_expanded: false,
            });
        };
        if m.end_timezone_offset != i16::MAX {
            fields.push(Field {
                num: 3,
                profile_type: ProfileType::SINT16,
                value: Value::Int16(m.end_timezone_offset),
                is_expanded: false,
            });
        };
        if m.feedback.0 != u8::MAX {
            fields.push(Field {
                num: 4,
                profile_type: ProfileType::NAP_PERIOD_FEEDBACK,
                value: Value::Uint8(m.feedback.0),
                is_expanded: false,
            });
        };
        if m.is_deleted.0 != u8::MAX {
            fields.push(Field {
                num: 5,
                profile_type: ProfileType::BOOL,
                value: Value::Uint8(m.is_deleted.0),
                is_expanded: false,
            });
        };
        if m.source.0 != u8::MAX {
            fields.push(Field {
                num: 6,
                profile_type: ProfileType::NAP_SOURCE,
                value: Value::Uint8(m.source.0),
                is_expanded: false,
            });
        };
        if m.update_timestamp.0 != u32::MAX {
            fields.push(Field {
                num: 7,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.update_timestamp.0),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::NAP_EVENT,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
