// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(clippy::manual_range_patterns)]

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use crate::semconv;
use alloc::vec::Vec;
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize, Serializer, ser::SerializeStruct};

fn is_expanded(state: &[u8], num: u8) -> bool {
    match num {
        6 => (state[num as usize >> 3] >> (num & 7)) & 1 == 1,
        _ => false,
    }
}

/// Segment Point message.
#[cfg_attr(feature = "serde", derive(Deserialize), serde(from = "De"))]
#[derive(Debug, Clone)]
pub struct SegmentPoint {
    pub message_index: typedef::MessageIndex,
    /// Units: semicircles
    pub position_lat: i32,
    /// Units: semicircles
    pub position_long: i32,
    /// Scale: 100; Units: m; Accumulated distance along the segment at the described point
    pub distance: u32,
    /// Scale: 5; Offset: 500; Units: m; Accumulated altitude along the segment at the described point
    pub altitude: u16,
    /// Scale: 1000; Units: s; Accumualted time each leader board member required to reach the described point. This value is zero for all leader board members at the starting point of the segment.
    pub leader_time: Vec<u32>,
    /// Scale: 5; Offset: 500; Units: m; Accumulated altitude along the segment at the described point
    pub enhanced_altitude: u32,
    state: [u8; 1], // Used for tracking expanded fields.
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl SegmentPoint {
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::MessageIndex
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `i32`; FitBaseType::SINT32; ProfileType::Sint32; Units: `semicircles`
    pub const POSITION_LAT: u8 = 1;
    /// Value's type: `i32`; FitBaseType::SINT32; ProfileType::Sint32; Units: `semicircles`
    pub const POSITION_LONG: u8 = 2;
    /// Value's type: `u32`; FitBaseType::UINT32; ProfileType::Uint32; Scale: `100`; Units: `m`
    pub const DISTANCE: u8 = 3;
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::Uint16; Scale: `5`; Offset: `500`; Units: `m`
    pub const ALTITUDE: u8 = 4;
    /// Value's type: `Vec<u32>`; FitBaseType::UINT32; ProfileType::Uint32; Scale: `1000`; Units: `s`
    pub const LEADER_TIME: u8 = 5;
    /// Value's type: `u32`; FitBaseType::UINT32; ProfileType::Uint32; Scale: `5`; Offset: `500`; Units: `m`
    pub const ENHANCED_ALTITUDE: u8 = 6;

    /// Create new SegmentPoint with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            position_lat: i32::MAX,
            position_long: i32::MAX,
            distance: u32::MAX,
            altitude: u16::MAX,
            leader_time: Vec::new(),
            enhanced_altitude: u32::MAX,
            state: [0u8; 1],
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `position_lat` in degrees instead of semicircles. It returns `None` when value is invalid.
    pub fn position_lat_degrees(&self) -> Option<f64> {
        semconv::to_degrees(self.position_lat)
    }

    /// Set `position_lat` with a value in degrees instead of semicircles, the value will be converted to semicircles.
    pub fn set_position_lat_degrees(&mut self, v: f64) -> &mut Self {
        self.position_lat = semconv::to_semicircles(v).unwrap_or(i32::MAX);
        self
    }

    /// Returns `position_long` in degrees instead of semicircles. It returns `None` when value is invalid.
    pub fn position_long_degrees(&self) -> Option<f64> {
        semconv::to_degrees(self.position_long)
    }

    /// Set `position_long` with a value in degrees instead of semicircles, the value will be converted to semicircles.
    pub fn set_position_long_degrees(&mut self, v: f64) -> &mut Self {
        self.position_long = semconv::to_semicircles(v).unwrap_or(i32::MAX);
        self
    }

    /// Returns `distance` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: m
    pub fn distance_scaled(&self) -> Option<f64> {
        if self.distance == u32::MAX {
            return None;
        }
        Some(self.distance as f64 / 100.0 - 0.0)
    }

    /// Set `distance` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_distance_scaled(&mut self, v: f64) -> &mut Self {
        let unscaled = (v + 0.0) * 100.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u32::MAX as f64 {
            self.distance = u32::MAX;
            return self;
        }
        self.distance = unscaled as u32;
        self
    }

    /// Returns `altitude` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: m
    pub fn altitude_scaled(&self) -> Option<f64> {
        if self.altitude == u16::MAX {
            return None;
        }
        Some(self.altitude as f64 / 5.0 - 500.0)
    }

    /// Set `altitude` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_altitude_scaled(&mut self, v: f64) -> &mut Self {
        let unscaled = (v + 500.0) * 5.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.altitude = u16::MAX;
            return self;
        }
        self.altitude = unscaled as u16;
        self
    }

    /// Returns `leader_time` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: s
    pub fn leader_time_scaled(&self) -> Option<Vec<f64>> {
        if self.leader_time.is_empty() {
            return None;
        }
        let mut v = Vec::with_capacity(self.leader_time.len());
        for &x in &self.leader_time {
            v.push(x as f64 / 1000.0 - 0.0)
        }
        Some(v)
    }

    /// Set `leader_time` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_leader_time_scaled(&mut self, v: &[f64]) -> &mut Self {
        self.leader_time = Vec::with_capacity(v.len());
        if v.is_empty() {
            return self;
        }
        for &x in v {
            let unscaled = (x + 0.0) * 1000.0;
            if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u32::MAX as f64 {
                self.leader_time.push(u32::MAX);
                continue;
            }
            self.leader_time.push(unscaled as u32);
        }
        self
    }

    /// Returns `enhanced_altitude` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: m
    pub fn enhanced_altitude_scaled(&self) -> Option<f64> {
        if self.enhanced_altitude == u32::MAX {
            return None;
        }
        Some(self.enhanced_altitude as f64 / 5.0 - 500.0)
    }

    /// Set `enhanced_altitude` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_enhanced_altitude_scaled(&mut self, v: f64) -> &mut Self {
        let unscaled = (v + 500.0) * 5.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u32::MAX as f64 {
            self.enhanced_altitude = u32::MAX;
            return self;
        }
        self.enhanced_altitude = unscaled as u32;
        self
    }

    /// Marks whether given field's num is an expanded field (field that being generated through a component expansion).
    pub fn mark_as_expanded(&mut self, num: u8, flag: bool) -> bool {
        match num {
            6 => {
                if flag {
                    self.state[num as usize >> 3] |= 1 << (num & 7)
                } else {
                    self.state[num as usize >> 3] &= !(1 << (num & 7))
                }
                true
            }
            _ => false,
        }
    }

    /// checks whether given field's num is a field generated through a component expansion.
    pub fn is_expanded(&self, num: u8) -> bool {
        is_expanded(&self.state, num)
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index.0 != u16::MAX) as usize
            + (self.position_lat != i32::MAX) as usize
            + (self.position_long != i32::MAX) as usize
            + (self.distance != u32::MAX) as usize
            + (self.altitude != u16::MAX) as usize
            + (!self.leader_time.is_empty()) as usize
            + (self.enhanced_altitude != u32::MAX) as usize
    }
}

impl Default for SegmentPoint {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for SegmentPoint {
    /// from creates new SegmentPoint struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [126, 0, 0, 4611686018427387904];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                1 => v.position_lat = field.value.as_i32(),
                2 => v.position_long = field.value.as_i32(),
                3 => v.distance = field.value.as_u32(),
                4 => v.altitude = field.value.as_u16(),
                5 => v.leader_time = field.value.to_vec_u32(),
                6 => v.enhanced_altitude = field.value.as_u32(),
                _ => {
                    v.unknown_fields.push(field.clone());
                    continue;
                }
            };
            if field.is_expanded && field.num < 7 {
                v.state[field.num as usize >> 3] |= 1 << (field.num & 7)
            }
        }

        v
    }
}

impl From<SegmentPoint> for Message {
    fn from(m: SegmentPoint) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index.0 != u16::MAX {
            fields.push(Field {
                num: 254,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.position_lat != i32::MAX {
            fields.push(Field {
                num: 1,
                base_type: FitBaseType::SINT32,
                value: Value::Int32(m.position_lat),
                is_expanded: false,
            });
        };
        if m.position_long != i32::MAX {
            fields.push(Field {
                num: 2,
                base_type: FitBaseType::SINT32,
                value: Value::Int32(m.position_long),
                is_expanded: false,
            });
        };
        if m.distance != u32::MAX {
            fields.push(Field {
                num: 3,
                base_type: FitBaseType::UINT32,
                value: Value::Uint32(m.distance),
                is_expanded: false,
            });
        };
        if m.altitude != u16::MAX {
            fields.push(Field {
                num: 4,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.altitude),
                is_expanded: false,
            });
        };
        if !m.leader_time.is_empty() {
            fields.push(Field {
                num: 5,
                base_type: FitBaseType::UINT32,
                value: Value::VecUint32(m.leader_time),
                is_expanded: false,
            });
        };
        if m.enhanced_altitude != u32::MAX {
            fields.push(Field {
                num: 6,
                base_type: FitBaseType::UINT32,
                value: Value::Uint32(m.enhanced_altitude),
                is_expanded: is_expanded(&m.state, 6),
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::SEGMENT_POINT,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for SegmentPoint {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let n = self.count_valid_fields() + 2;
        let mut state = serializer.serialize_struct("SegmentPoint", n)?;
        if self.message_index.0 != u16::MAX {
            state.serialize_field("message_index", &self.message_index)?;
        }
        if let Some(v) = self.position_lat_degrees() {
            state.serialize_field("position_lat", &v)?;
        }
        if let Some(v) = self.position_long_degrees() {
            state.serialize_field("position_long", &v)?;
        }
        if let Some(v) = self.distance_scaled() {
            state.serialize_field("distance", &v)?;
        }
        if let Some(v) = self.altitude_scaled() {
            state.serialize_field("altitude", &v)?;
        }
        if let Some(v) = self.leader_time_scaled() {
            state.serialize_field("leader_time", &v)?;
        }
        if let Some(v) = self.enhanced_altitude_scaled() {
            state.serialize_field("enhanced_altitude", &v)?;
        }
        if !self.unknown_fields.is_empty() {
            state.serialize_field("unknown_fields", &self.unknown_fields)?;
        }
        if !self.developer_fields.is_empty() {
            state.serialize_field("developer_fields", &self.developer_fields)?;
        }
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize), serde(default))]
struct De {
    message_index: typedef::MessageIndex,
    /// Degrees.
    position_lat: f64,
    /// Degrees.
    position_long: f64,
    distance: f64,
    altitude: f64,
    leader_time: Vec<f64>,
    enhanced_altitude: f64,
    unknown_fields: Vec<Field>,
    developer_fields: Vec<DeveloperField>,
}

#[cfg(feature = "serde")]
impl From<De> for SegmentPoint {
    fn from(m: De) -> Self {
        Self {
            message_index: m.message_index,
            position_lat: semconv::to_semicircles(m.position_lat).unwrap_or(i32::MAX),
            position_long: semconv::to_semicircles(m.position_long).unwrap_or(i32::MAX),
            distance: {
                let unscaled = (m.distance + 0.0) * 100.0;
                if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u32::MAX as f64 {
                    u32::MAX
                } else {
                    unscaled as u32
                }
            },
            altitude: {
                let unscaled = (m.altitude + 500.0) * 5.0;
                if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
                    u16::MAX
                } else {
                    unscaled as u16
                }
            },
            leader_time: {
                if m.leader_time.is_empty() {
                    Vec::new()
                } else {
                    let mut vals = Vec::with_capacity(m.leader_time.len());
                    for &x in m.leader_time.iter() {
                        let unscaled = (x + 0.0) * 1000.0;
                        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u32::MAX as f64
                        {
                            vals.push(u32::MAX);
                            continue;
                        }
                        vals.push(unscaled as u32);
                    }
                    vals
                }
            },
            enhanced_altitude: {
                let unscaled = (m.enhanced_altitude + 500.0) * 5.0;
                if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u32::MAX as f64 {
                    u32::MAX
                } else {
                    unscaled as u32
                }
            },
            state: [0u8; 1],
            unknown_fields: m.unknown_fields,
            developer_fields: m.developer_fields,
        }
    }
}

#[cfg(feature = "serde")]
impl Default for De {
    fn default() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            position_lat: f64::from_bits(u64::MAX),
            position_long: f64::from_bits(u64::MAX),
            distance: f64::from_bits(u64::MAX),
            altitude: f64::from_bits(u64::MAX),
            leader_time: Vec::new(),
            enhanced_altitude: f64::from_bits(u64::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }
}
