// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, lookup, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// SkinTempOvernight is a SkinTempOvernight message.
pub struct SkinTempOvernight {
    pub timestamp: typedef::DateTime,
    pub local_timestamp: typedef::LocalDateTime,
    /// The average overnight deviation from baseline temperature in degrees C
    pub average_deviation: f32,
    /// The average 7 day overnight deviation from baseline temperature in degrees C
    pub average_7_day_deviation: f32,
    /// Final overnight temperature value
    pub nightly_value: f32,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl SkinTempOvernight {
    /// Value's type: `u32`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u32`
    pub const LOCAL_TIMESTAMP: u8 = 0;
    /// Value's type: `f32`
    pub const AVERAGE_DEVIATION: u8 = 1;
    /// Value's type: `f32`
    pub const AVERAGE_7_DAY_DEVIATION: u8 = 2;
    /// Value's type: `f32`
    pub const NIGHTLY_VALUE: u8 = 4;

    /// Create new SkinTempOvernight with all fields being set to its corresponding invalid value.
    pub fn new() -> Self {
        Self::from(&Message::default())
    }
}

impl Default for SkinTempOvernight {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for SkinTempOvernight {
    /// from creates new SkinTempOvernight struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 254] = [const { &Value::Invalid }; 254];
        let mut unknown_fields: Vec<Field> = Vec::new();

        for field in &mesg.fields {
            if lookup::field_reference(mesg.num, field.num).is_none() {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            timestamp: typedef::DateTime(vals[253].as_u32()),
            local_timestamp: typedef::LocalDateTime(vals[0].as_u32()),
            average_deviation: vals[1].as_f32(),
            average_7_day_deviation: vals[2].as_f32(),
            nightly_value: vals[4].as_f32(),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<SkinTempOvernight> for Message {
    fn from(m: SkinTempOvernight) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                base_type: typedef::FitBaseType(0),
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 5];
        let mut len = 0usize;

        if m.timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 253,
                base_type: typedef::FitBaseType::UINT32,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.local_timestamp != typedef::LocalDateTime(u32::MAX) {
            arr[len] = Field {
                num: 0,
                base_type: typedef::FitBaseType::UINT32,
                profile_type: ProfileType::LOCAL_DATE_TIME,
                value: Value::Uint32(m.local_timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.average_deviation != f32::MAX {
            arr[len] = Field {
                num: 1,
                base_type: typedef::FitBaseType::FLOAT32,
                profile_type: ProfileType::FLOAT32,
                value: Value::Float32(m.average_deviation),
                is_expanded: false,
            };
            len += 1;
        }
        if m.average_7_day_deviation != f32::MAX {
            arr[len] = Field {
                num: 2,
                base_type: typedef::FitBaseType::FLOAT32,
                profile_type: ProfileType::FLOAT32,
                value: Value::Float32(m.average_7_day_deviation),
                is_expanded: false,
            };
            len += 1;
        }
        if m.nightly_value != f32::MAX {
            arr[len] = Field {
                num: 4,
                base_type: typedef::FitBaseType::FLOAT32,
                profile_type: ProfileType::FLOAT32,
                value: Value::Float32(m.nightly_value),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::SKIN_TEMP_OVERNIGHT,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
