// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use alloc::vec::Vec;

/// Sleep Disruption Severity Period message.
#[derive(Debug, Clone)]
pub struct SleepDisruptionSeverityPeriod {
    pub message_index: typedef::MessageIndex,
    pub timestamp: typedef::DateTime,
    pub severity: typedef::SleepDisruptionSeverity,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl SleepDisruptionSeverityPeriod {
    /// Value's type: `u16`; ProfileType: `ProfileType::MESSAGE_INDEX`
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u32`; ProfileType: `ProfileType::DATE_TIME`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u8`; ProfileType: `ProfileType::SLEEP_DISRUPTION_SEVERITY`
    pub const SEVERITY: u8 = 0;

    /// Create new SleepDisruptionSeverityPeriod with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            timestamp: typedef::DateTime(u32::MAX),
            severity: typedef::SleepDisruptionSeverity(u8::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index.0 != u16::MAX) as usize
            + (self.timestamp.0 != u32::MAX) as usize
            + (self.severity.0 != u8::MAX) as usize
    }
}

impl Default for SleepDisruptionSeverityPeriod {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for SleepDisruptionSeverityPeriod {
    /// from creates new SleepDisruptionSeverityPeriod struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [1, 0, 0, 6917529027641081856];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.severity = typedef::SleepDisruptionSeverity(field.value.as_u8()),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<SleepDisruptionSeverityPeriod> for Message {
    fn from(m: SleepDisruptionSeverityPeriod) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index.0 != u16::MAX {
            fields.push(Field {
                num: 254,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.timestamp.0 != u32::MAX {
            fields.push(Field {
                num: 253,
                base_type: FitBaseType::UINT32,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.severity.0 != u8::MAX {
            fields.push(Field {
                num: 0,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.severity.0),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::SLEEP_DISRUPTION_SEVERITY_PERIOD,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
