// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, lookup, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// StressLevel is a StressLevel message.
pub struct StressLevel {
    pub stress_level_value: i16,
    /// Units: s; Time stress score was calculated
    pub stress_level_time: typedef::DateTime,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl StressLevel {
    /// Value's type: `i16`
    pub const STRESS_LEVEL_VALUE: u8 = 0;
    /// Value's type: `u32`; Units: `s`
    pub const STRESS_LEVEL_TIME: u8 = 1;

    /// Create new StressLevel with all fields being set to its corresponding invalid value.
    pub fn new() -> Self {
        Self::from(&Message::default())
    }
}

impl Default for StressLevel {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for StressLevel {
    /// from creates new StressLevel struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 2] = [const { &Value::Invalid }; 2];
        let mut unknown_fields: Vec<Field> = Vec::new();

        for field in &mesg.fields {
            if lookup::field_reference(mesg.num, field.num).is_none() {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            stress_level_value: vals[0].as_i16(),
            stress_level_time: typedef::DateTime(vals[1].as_u32()),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<StressLevel> for Message {
    fn from(m: StressLevel) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                base_type: typedef::FitBaseType(0),
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 2];
        let mut len = 0usize;

        if m.stress_level_value != i16::MAX {
            arr[len] = Field {
                num: 0,
                base_type: typedef::FitBaseType::SINT16,
                profile_type: ProfileType::SINT16,
                value: Value::Int16(m.stress_level_value),
                is_expanded: false,
            };
            len += 1;
        }
        if m.stress_level_time != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 1,
                base_type: typedef::FitBaseType::UINT32,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.stress_level_time.0),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::STRESS_LEVEL,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
