// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// TankUpdate is a TankUpdate message.
pub struct TankUpdate {
    /// Units: s
    pub timestamp: typedef::DateTime,
    /// Base: UINT32Z
    pub sensor: typedef::AntChannelId,
    /// Scale: 100; Units: bar
    pub pressure: u16,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl TankUpdate {
    /// Value's type: `u32`; Units: `s`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u32`; Base: UINT32Z
    pub const SENSOR: u8 = 0;
    /// Value's type: `u16`; Scale: `100`; Units: `bar`
    pub const PRESSURE: u8 = 1;

    /// Create new TankUpdate with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            sensor: typedef::AntChannelId(u32::MIN),
            pressure: u16::MAX,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `pressure` in its scaled value. It returns invalid f64 when value is valid.
    pub fn pressure_scaled(&self) -> f64 {
        if self.pressure == u16::MAX {
            return f64::from_bits(u64::MAX);
        }
        self.pressure as f64 / 100.0 - 0.0
    }

    /// Set `pressure` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_pressure_scaled(&mut self, v: f64) -> &mut TankUpdate {
        let unscaled = (v + 0.0) * 100.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.pressure = u16::MAX;
            return self;
        }
        self.pressure = unscaled as u16;
        self
    }
}

impl Default for TankUpdate {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for TankUpdate {
    /// from creates new TankUpdate struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 254] = [const { &Value::Invalid }; 254];

        const KNOWN_NUMS: [u64; 4] = [3, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }
        let mut unknown_fields: Vec<Field> = Vec::with_capacity(n as usize);

        for field in &mesg.fields {
            if (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 == 0 {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            timestamp: typedef::DateTime(vals[253].as_u32()),
            sensor: typedef::AntChannelId(vals[0].as_u32z()),
            pressure: vals[1].as_u16(),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<TankUpdate> for Message {
    fn from(m: TankUpdate) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 3];
        let mut len = 0usize;

        if m.timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.sensor != typedef::AntChannelId(u32::MIN) {
            arr[len] = Field {
                num: 0,
                profile_type: ProfileType::ANT_CHANNEL_ID,
                value: Value::Uint32(m.sensor.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.pressure != u16::MAX {
            arr[len] = Field {
                num: 1,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.pressure),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::TANK_UPDATE,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
