// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// TimestampCorrelation is a TimestampCorrelation message.
pub struct TimestampCorrelation {
    /// Units: s; Whole second part of UTC timestamp at the time the system timestamp was recorded.
    pub timestamp: typedef::DateTime,
    /// Scale: 32768; Units: s; Fractional part of the UTC timestamp at the time the system timestamp was recorded.
    pub fractional_timestamp: u16,
    /// Units: s; Whole second part of the system timestamp
    pub system_timestamp: typedef::DateTime,
    /// Scale: 32768; Units: s; Fractional part of the system timestamp
    pub fractional_system_timestamp: u16,
    /// Units: s; timestamp epoch expressed in local time used to convert timestamps to local time
    pub local_timestamp: typedef::LocalDateTime,
    /// Units: ms; Millisecond part of the UTC timestamp at the time the system timestamp was recorded.
    pub timestamp_ms: u16,
    /// Units: ms; Millisecond part of the system timestamp
    pub system_timestamp_ms: u16,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl TimestampCorrelation {
    /// Value's type: `u32`; Units: `s`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Scale: `32768`; Units: `s`
    pub const FRACTIONAL_TIMESTAMP: u8 = 0;
    /// Value's type: `u32`; Units: `s`
    pub const SYSTEM_TIMESTAMP: u8 = 1;
    /// Value's type: `u16`; Scale: `32768`; Units: `s`
    pub const FRACTIONAL_SYSTEM_TIMESTAMP: u8 = 2;
    /// Value's type: `u32`; Units: `s`
    pub const LOCAL_TIMESTAMP: u8 = 3;
    /// Value's type: `u16`; Units: `ms`
    pub const TIMESTAMP_MS: u8 = 4;
    /// Value's type: `u16`; Units: `ms`
    pub const SYSTEM_TIMESTAMP_MS: u8 = 5;

    /// Create new TimestampCorrelation with all fields being set to its corresponding invalid value.
    pub fn new() -> Self {
        Self::from(&Message::default())
    }

    /// Returns `fractional_timestamp` in its scaled value. It returns invalid f64 when value is valid.
    pub fn fractional_timestamp_scaled(&self) -> f64 {
        if self.fractional_timestamp == u16::MAX {
            return f64::from_bits(u64::MAX);
        }
        self.fractional_timestamp as f64 / 32768.0 - 0.0
    }

    /// Set `fractional_timestamp` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_fractional_timestamp_scaled(&mut self, v: f64) -> &mut TimestampCorrelation {
        let unscaled = (v + 0.0) * 32768.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.fractional_timestamp = u16::MAX;
            return self;
        }
        self.fractional_timestamp = unscaled as u16;
        self
    }

    /// Returns `fractional_system_timestamp` in its scaled value. It returns invalid f64 when value is valid.
    pub fn fractional_system_timestamp_scaled(&self) -> f64 {
        if self.fractional_system_timestamp == u16::MAX {
            return f64::from_bits(u64::MAX);
        }
        self.fractional_system_timestamp as f64 / 32768.0 - 0.0
    }

    /// Set `fractional_system_timestamp` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_fractional_system_timestamp_scaled(&mut self, v: f64) -> &mut TimestampCorrelation {
        let unscaled = (v + 0.0) * 32768.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.fractional_system_timestamp = u16::MAX;
            return self;
        }
        self.fractional_system_timestamp = unscaled as u16;
        self
    }
}

impl Default for TimestampCorrelation {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for TimestampCorrelation {
    /// from creates new TimestampCorrelation struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 254] = [const { &Value::Invalid }; 254];

        const KNOWN_NUMS: [u64; 4] = [63, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }
        let mut unknown_fields: Vec<Field> = Vec::with_capacity(n as usize);

        for field in &mesg.fields {
            if (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 == 0 {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            timestamp: typedef::DateTime(vals[253].as_u32()),
            fractional_timestamp: vals[0].as_u16(),
            system_timestamp: typedef::DateTime(vals[1].as_u32()),
            fractional_system_timestamp: vals[2].as_u16(),
            local_timestamp: typedef::LocalDateTime(vals[3].as_u32()),
            timestamp_ms: vals[4].as_u16(),
            system_timestamp_ms: vals[5].as_u16(),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<TimestampCorrelation> for Message {
    fn from(m: TimestampCorrelation) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 7];
        let mut len = 0usize;

        if m.timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.fractional_timestamp != u16::MAX {
            arr[len] = Field {
                num: 0,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.fractional_timestamp),
                is_expanded: false,
            };
            len += 1;
        }
        if m.system_timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 1,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.system_timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.fractional_system_timestamp != u16::MAX {
            arr[len] = Field {
                num: 2,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.fractional_system_timestamp),
                is_expanded: false,
            };
            len += 1;
        }
        if m.local_timestamp != typedef::LocalDateTime(u32::MAX) {
            arr[len] = Field {
                num: 3,
                profile_type: ProfileType::LOCAL_DATE_TIME,
                value: Value::Uint32(m.local_timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.timestamp_ms != u16::MAX {
            arr[len] = Field {
                num: 4,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.timestamp_ms),
                is_expanded: false,
            };
            len += 1;
        }
        if m.system_timestamp_ms != u16::MAX {
            arr[len] = Field {
                num: 5,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.system_timestamp_ms),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::TIMESTAMP_CORRELATION,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
