// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

/// Totals message.
#[derive(Debug, Clone)]
pub struct Totals {
    pub message_index: typedef::MessageIndex,
    /// Units: s
    pub timestamp: typedef::DateTime,
    /// Units: s; Excludes pauses
    pub timer_time: u32,
    /// Units: m
    pub distance: u32,
    /// Units: kcal
    pub calories: u32,
    pub sport: typedef::Sport,
    /// Units: s; Includes pauses
    pub elapsed_time: u32,
    pub sessions: u16,
    /// Units: s
    pub active_time: u32,
    pub sport_index: u8,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl Totals {
    /// Value's type: `u16`; ProfileType: `ProfileType::MESSAGE_INDEX`
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u32`; Units: `s`; ProfileType: `ProfileType::DATE_TIME`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u32`; Units: `s`; ProfileType: `ProfileType::UINT32`
    pub const TIMER_TIME: u8 = 0;
    /// Value's type: `u32`; Units: `m`; ProfileType: `ProfileType::UINT32`
    pub const DISTANCE: u8 = 1;
    /// Value's type: `u32`; Units: `kcal`; ProfileType: `ProfileType::UINT32`
    pub const CALORIES: u8 = 2;
    /// Value's type: `u8`; ProfileType: `ProfileType::SPORT`
    pub const SPORT: u8 = 3;
    /// Value's type: `u32`; Units: `s`; ProfileType: `ProfileType::UINT32`
    pub const ELAPSED_TIME: u8 = 4;
    /// Value's type: `u16`; ProfileType: `ProfileType::UINT16`
    pub const SESSIONS: u8 = 5;
    /// Value's type: `u32`; Units: `s`; ProfileType: `ProfileType::UINT32`
    pub const ACTIVE_TIME: u8 = 6;
    /// Value's type: `u8`; ProfileType: `ProfileType::UINT8`
    pub const SPORT_INDEX: u8 = 9;

    /// Create new Totals with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            timestamp: typedef::DateTime(u32::MAX),
            timer_time: u32::MAX,
            distance: u32::MAX,
            calories: u32::MAX,
            sport: typedef::Sport(u8::MAX),
            elapsed_time: u32::MAX,
            sessions: u16::MAX,
            active_time: u32::MAX,
            sport_index: u8::MAX,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index != typedef::MessageIndex(u16::MAX)) as usize
            + (self.timestamp != typedef::DateTime(u32::MAX)) as usize
            + (self.timer_time != u32::MAX) as usize
            + (self.distance != u32::MAX) as usize
            + (self.calories != u32::MAX) as usize
            + (self.sport != typedef::Sport(u8::MAX)) as usize
            + (self.elapsed_time != u32::MAX) as usize
            + (self.sessions != u16::MAX) as usize
            + (self.active_time != u32::MAX) as usize
            + (self.sport_index != u8::MAX) as usize
    }
}

impl Default for Totals {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for Totals {
    /// from creates new Totals struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [639, 0, 0, 6917529027641081856];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.timer_time = field.value.as_u32(),
                1 => v.distance = field.value.as_u32(),
                2 => v.calories = field.value.as_u32(),
                3 => v.sport = typedef::Sport(field.value.as_u8()),
                4 => v.elapsed_time = field.value.as_u32(),
                5 => v.sessions = field.value.as_u16(),
                6 => v.active_time = field.value.as_u32(),
                9 => v.sport_index = field.value.as_u8(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<Totals> for Message {
    fn from(m: Totals) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index != typedef::MessageIndex(u16::MAX) {
            fields.push(Field {
                num: 254,
                profile_type: ProfileType::MESSAGE_INDEX,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.timestamp != typedef::DateTime(u32::MAX) {
            fields.push(Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.timer_time != u32::MAX {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.timer_time),
                is_expanded: false,
            });
        };
        if m.distance != u32::MAX {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.distance),
                is_expanded: false,
            });
        };
        if m.calories != u32::MAX {
            fields.push(Field {
                num: 2,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.calories),
                is_expanded: false,
            });
        };
        if m.sport != typedef::Sport(u8::MAX) {
            fields.push(Field {
                num: 3,
                profile_type: ProfileType::SPORT,
                value: Value::Uint8(m.sport.0),
                is_expanded: false,
            });
        };
        if m.elapsed_time != u32::MAX {
            fields.push(Field {
                num: 4,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.elapsed_time),
                is_expanded: false,
            });
        };
        if m.sessions != u16::MAX {
            fields.push(Field {
                num: 5,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.sessions),
                is_expanded: false,
            });
        };
        if m.active_time != u32::MAX {
            fields.push(Field {
                num: 6,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.active_time),
                is_expanded: false,
            });
        };
        if m.sport_index != u8::MAX {
            fields.push(Field {
                num: 9,
                profile_type: ProfileType::UINT8,
                value: Value::Uint8(m.sport_index),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::TOTALS,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
