// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::vec::Vec;

/// Video Frame message.
#[derive(Debug, Clone)]
pub struct VideoFrame {
    /// Units: s; Whole second part of the timestamp
    pub timestamp: typedef::DateTime,
    /// Units: ms; Millisecond part of the timestamp.
    pub timestamp_ms: u16,
    /// Number of the frame that the timestamp and timestamp_ms correlate to
    pub frame_number: u32,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl VideoFrame {
    /// Value's type: `u32`; Units: `s`; ProfileType: `ProfileType::DATE_TIME`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u16`; Units: `ms`; ProfileType: `ProfileType::UINT16`
    pub const TIMESTAMP_MS: u8 = 0;
    /// Value's type: `u32`; ProfileType: `ProfileType::UINT32`
    pub const FRAME_NUMBER: u8 = 1;

    /// Create new VideoFrame with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            timestamp_ms: u16::MAX,
            frame_number: u32::MAX,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.timestamp != typedef::DateTime(u32::MAX)) as usize
            + (self.timestamp_ms != u16::MAX) as usize
            + (self.frame_number != u32::MAX) as usize
    }
}

impl Default for VideoFrame {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for VideoFrame {
    /// from creates new VideoFrame struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [3, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.timestamp_ms = field.value.as_u16(),
                1 => v.frame_number = field.value.as_u32(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<VideoFrame> for Message {
    fn from(m: VideoFrame) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.timestamp != typedef::DateTime(u32::MAX) {
            fields.push(Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.timestamp_ms != u16::MAX {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.timestamp_ms),
                is_expanded: false,
            });
        };
        if m.frame_number != u32::MAX {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.frame_number),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::VIDEO_FRAME,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
