// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, lookup, typedef};
use crate::proto::*;

#[derive(Debug, Clone)]
/// Video is a Video message.
pub struct Video {
    pub url: String,
    pub hosting_provider: String,
    /// Units: ms; Playback time of video
    pub duration: u32,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl Video {
    /// Value's type: `String`
    pub const URL: u8 = 0;
    /// Value's type: `String`
    pub const HOSTING_PROVIDER: u8 = 1;
    /// Value's type: `u32`; Units: `ms`
    pub const DURATION: u8 = 2;

    /// Create new Video with all fields being set to its corresponding invalid value.
    pub fn new() -> Self {
        Self::from(&Message::default())
    }
}

impl Default for Video {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for Video {
    /// from creates new Video struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 3] = [const { &Value::Invalid }; 3];
        let mut unknown_fields: Vec<Field> = Vec::new();

        for field in &mesg.fields {
            if lookup::field_reference(mesg.num, field.num).is_none() {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            url: vals[0].as_string(),
            hosting_provider: vals[1].as_string(),
            duration: vals[2].as_u32(),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<Video> for Message {
    fn from(m: Video) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 3];
        let mut len = 0usize;

        if m.url != String::new() {
            arr[len] = Field {
                num: 0,
                profile_type: ProfileType::STRING,
                value: Value::String(m.url),
                is_expanded: false,
            };
            len += 1;
        }
        if m.hosting_provider != String::new() {
            arr[len] = Field {
                num: 1,
                profile_type: ProfileType::STRING,
                value: Value::String(m.hosting_provider),
                is_expanded: false,
            };
            len += 1;
        }
        if m.duration != u32::MAX {
            arr[len] = Field {
                num: 2,
                profile_type: ProfileType::UINT32,
                value: Value::Uint32(m.duration),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::VIDEO,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
