// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use alloc::vec::Vec;

/// Watchface Settings message.
#[derive(Debug, Clone)]
pub struct WatchfaceSettings {
    pub message_index: typedef::MessageIndex,
    pub mode: typedef::WatchfaceMode,
    pub layout: u8,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl WatchfaceSettings {
    /// Value's type: `u16`; ProfileType: `ProfileType::MESSAGE_INDEX`
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u8`; ProfileType: `ProfileType::WATCHFACE_MODE`
    pub const MODE: u8 = 0;
    /// Value's type: `u8`; ProfileType: `ProfileType::BYTE`
    pub const LAYOUT: u8 = 1;

    /// Create new WatchfaceSettings with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            mode: typedef::WatchfaceMode(u8::MAX),
            layout: u8::MAX,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index.0 != u16::MAX) as usize
            + (self.mode.0 != u8::MAX) as usize
            + (self.layout != u8::MAX) as usize
    }
}

impl Default for WatchfaceSettings {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for WatchfaceSettings {
    /// from creates new WatchfaceSettings struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [3, 0, 0, 4611686018427387904];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                0 => v.mode = typedef::WatchfaceMode(field.value.as_u8()),
                1 => v.layout = field.value.as_u8(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<WatchfaceSettings> for Message {
    fn from(m: WatchfaceSettings) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index.0 != u16::MAX {
            fields.push(Field {
                num: 254,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.mode.0 != u8::MAX {
            fields.push(Field {
                num: 0,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.mode.0),
                is_expanded: false,
            });
        };
        if m.layout != u8::MAX {
            fields.push(Field {
                num: 1,
                base_type: FitBaseType::BYTE,
                value: Value::Uint8(m.layout),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::WATCHFACE_SETTINGS,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
