// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use crate::semconv;
use alloc::borrow::ToOwned;
use alloc::string::String;
use alloc::vec::Vec;

#[derive(Debug, Clone)]
/// WeatherConditions is a WeatherConditions message.
pub struct WeatherConditions {
    /// time of update for current conditions, else forecast time
    pub timestamp: typedef::DateTime,
    /// Current or forecast
    pub weather_report: typedef::WeatherReport,
    /// Units: C
    pub temperature: i8,
    /// Corresponds to GSC Response weatherIcon field
    pub condition: typedef::WeatherStatus,
    /// Units: degrees
    pub wind_direction: u16,
    /// Scale: 1000; Units: m/s
    pub wind_speed: u16,
    /// range 0-100
    pub precipitation_probability: u8,
    /// Units: C; Heat Index if GCS heatIdx above or equal to 90F or wind chill if GCS windChill below or equal to 32F
    pub temperature_feels_like: i8,
    pub relative_humidity: u8,
    /// string corresponding to GCS response location string
    pub location: String,
    pub observed_at_time: typedef::DateTime,
    /// Units: semicircles
    pub observed_location_lat: i32,
    /// Units: semicircles
    pub observed_location_long: i32,
    pub day_of_week: typedef::DayOfWeek,
    /// Units: C
    pub high_temperature: i8,
    /// Units: C
    pub low_temperature: i8,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl WeatherConditions {
    /// Value's type: `u32`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `u8`
    pub const WEATHER_REPORT: u8 = 0;
    /// Value's type: `i8`; Units: `C`
    pub const TEMPERATURE: u8 = 1;
    /// Value's type: `u8`
    pub const CONDITION: u8 = 2;
    /// Value's type: `u16`; Units: `degrees`
    pub const WIND_DIRECTION: u8 = 3;
    /// Value's type: `u16`; Scale: `1000`; Units: `m/s`
    pub const WIND_SPEED: u8 = 4;
    /// Value's type: `u8`
    pub const PRECIPITATION_PROBABILITY: u8 = 5;
    /// Value's type: `i8`; Units: `C`
    pub const TEMPERATURE_FEELS_LIKE: u8 = 6;
    /// Value's type: `u8`
    pub const RELATIVE_HUMIDITY: u8 = 7;
    /// Value's type: `String`
    pub const LOCATION: u8 = 8;
    /// Value's type: `u32`
    pub const OBSERVED_AT_TIME: u8 = 9;
    /// Value's type: `i32`; Units: `semicircles`
    pub const OBSERVED_LOCATION_LAT: u8 = 10;
    /// Value's type: `i32`; Units: `semicircles`
    pub const OBSERVED_LOCATION_LONG: u8 = 11;
    /// Value's type: `u8`
    pub const DAY_OF_WEEK: u8 = 12;
    /// Value's type: `i8`; Units: `C`
    pub const HIGH_TEMPERATURE: u8 = 13;
    /// Value's type: `i8`; Units: `C`
    pub const LOW_TEMPERATURE: u8 = 14;

    /// Create new WeatherConditions with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            weather_report: typedef::WeatherReport(u8::MAX),
            temperature: i8::MAX,
            condition: typedef::WeatherStatus(u8::MAX),
            wind_direction: u16::MAX,
            wind_speed: u16::MAX,
            precipitation_probability: u8::MAX,
            temperature_feels_like: i8::MAX,
            relative_humidity: u8::MAX,
            location: String::new(),
            observed_at_time: typedef::DateTime(u32::MAX),
            observed_location_lat: i32::MAX,
            observed_location_long: i32::MAX,
            day_of_week: typedef::DayOfWeek(u8::MAX),
            high_temperature: i8::MAX,
            low_temperature: i8::MAX,
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `observed_location_lat` in degrees instead of semicircles. It returns `None` when value is invalid.
    pub fn observed_location_lat_degrees(&self) -> Option<f64> {
        semconv::to_degrees(self.observed_location_lat)
    }

    /// Set `observed_location_lat` with a value in degrees instead of semicircles, the value will be converted to semicircles.
    pub fn set_observed_location_lat_degrees(&mut self, v: f64) -> &mut Self {
        self.observed_location_lat = semconv::to_semicircles(v).unwrap_or(i32::MAX);
        self
    }

    /// Returns `observed_location_long` in degrees instead of semicircles. It returns `None` when value is invalid.
    pub fn observed_location_long_degrees(&self) -> Option<f64> {
        semconv::to_degrees(self.observed_location_long)
    }

    /// Set `observed_location_long` with a value in degrees instead of semicircles, the value will be converted to semicircles.
    pub fn set_observed_location_long_degrees(&mut self, v: f64) -> &mut Self {
        self.observed_location_long = semconv::to_semicircles(v).unwrap_or(i32::MAX);
        self
    }

    /// Returns `wind_speed` in its scaled value. It returns `None` when value is invalid.
    pub fn wind_speed_scaled(&self) -> Option<f64> {
        if self.wind_speed == u16::MAX {
            return None;
        }
        Some(self.wind_speed as f64 / 1000.0 - 0.0)
    }

    /// Set `wind_speed` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_wind_speed_scaled(&mut self, v: f64) -> &mut Self {
        let unscaled = (v + 0.0) * 1000.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.wind_speed = u16::MAX;
            return self;
        }
        self.wind_speed = unscaled as u16;
        self
    }

    fn count_valid_fields(&self) -> usize {
        (self.timestamp != typedef::DateTime(u32::MAX)) as usize
            + (self.weather_report != typedef::WeatherReport(u8::MAX)) as usize
            + (self.temperature != i8::MAX) as usize
            + (self.condition != typedef::WeatherStatus(u8::MAX)) as usize
            + (self.wind_direction != u16::MAX) as usize
            + (self.wind_speed != u16::MAX) as usize
            + (self.precipitation_probability != u8::MAX) as usize
            + (self.temperature_feels_like != i8::MAX) as usize
            + (self.relative_humidity != u8::MAX) as usize
            + (!self.location.is_empty()) as usize
            + (self.observed_at_time != typedef::DateTime(u32::MAX)) as usize
            + (self.observed_location_lat != i32::MAX) as usize
            + (self.observed_location_long != i32::MAX) as usize
            + (self.day_of_week != typedef::DayOfWeek(u8::MAX)) as usize
            + (self.high_temperature != i8::MAX) as usize
            + (self.low_temperature != i8::MAX) as usize
    }
}

impl Default for WeatherConditions {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for WeatherConditions {
    /// from creates new WeatherConditions struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [32767, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                253 => v.timestamp = typedef::DateTime(field.value.as_u32()),
                0 => v.weather_report = typedef::WeatherReport(field.value.as_u8()),
                1 => v.temperature = field.value.as_i8(),
                2 => v.condition = typedef::WeatherStatus(field.value.as_u8()),
                3 => v.wind_direction = field.value.as_u16(),
                4 => v.wind_speed = field.value.as_u16(),
                5 => v.precipitation_probability = field.value.as_u8(),
                6 => v.temperature_feels_like = field.value.as_i8(),
                7 => v.relative_humidity = field.value.as_u8(),
                8 => v.location = field.value.as_str().to_owned(),
                9 => v.observed_at_time = typedef::DateTime(field.value.as_u32()),
                10 => v.observed_location_lat = field.value.as_i32(),
                11 => v.observed_location_long = field.value.as_i32(),
                12 => v.day_of_week = typedef::DayOfWeek(field.value.as_u8()),
                13 => v.high_temperature = field.value.as_i8(),
                14 => v.low_temperature = field.value.as_i8(),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<WeatherConditions> for Message {
    fn from(m: WeatherConditions) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.timestamp != typedef::DateTime(u32::MAX) {
            fields.push(Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            });
        };
        if m.weather_report != typedef::WeatherReport(u8::MAX) {
            fields.push(Field {
                num: 0,
                profile_type: ProfileType::WEATHER_REPORT,
                value: Value::Uint8(m.weather_report.0),
                is_expanded: false,
            });
        };
        if m.temperature != i8::MAX {
            fields.push(Field {
                num: 1,
                profile_type: ProfileType::SINT8,
                value: Value::Int8(m.temperature),
                is_expanded: false,
            });
        };
        if m.condition != typedef::WeatherStatus(u8::MAX) {
            fields.push(Field {
                num: 2,
                profile_type: ProfileType::WEATHER_STATUS,
                value: Value::Uint8(m.condition.0),
                is_expanded: false,
            });
        };
        if m.wind_direction != u16::MAX {
            fields.push(Field {
                num: 3,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.wind_direction),
                is_expanded: false,
            });
        };
        if m.wind_speed != u16::MAX {
            fields.push(Field {
                num: 4,
                profile_type: ProfileType::UINT16,
                value: Value::Uint16(m.wind_speed),
                is_expanded: false,
            });
        };
        if m.precipitation_probability != u8::MAX {
            fields.push(Field {
                num: 5,
                profile_type: ProfileType::UINT8,
                value: Value::Uint8(m.precipitation_probability),
                is_expanded: false,
            });
        };
        if m.temperature_feels_like != i8::MAX {
            fields.push(Field {
                num: 6,
                profile_type: ProfileType::SINT8,
                value: Value::Int8(m.temperature_feels_like),
                is_expanded: false,
            });
        };
        if m.relative_humidity != u8::MAX {
            fields.push(Field {
                num: 7,
                profile_type: ProfileType::UINT8,
                value: Value::Uint8(m.relative_humidity),
                is_expanded: false,
            });
        };
        if !m.location.is_empty() {
            fields.push(Field {
                num: 8,
                profile_type: ProfileType::STRING,
                value: Value::String(m.location),
                is_expanded: false,
            });
        };
        if m.observed_at_time != typedef::DateTime(u32::MAX) {
            fields.push(Field {
                num: 9,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.observed_at_time.0),
                is_expanded: false,
            });
        };
        if m.observed_location_lat != i32::MAX {
            fields.push(Field {
                num: 10,
                profile_type: ProfileType::SINT32,
                value: Value::Int32(m.observed_location_lat),
                is_expanded: false,
            });
        };
        if m.observed_location_long != i32::MAX {
            fields.push(Field {
                num: 11,
                profile_type: ProfileType::SINT32,
                value: Value::Int32(m.observed_location_long),
                is_expanded: false,
            });
        };
        if m.day_of_week != typedef::DayOfWeek(u8::MAX) {
            fields.push(Field {
                num: 12,
                profile_type: ProfileType::DAY_OF_WEEK,
                value: Value::Uint8(m.day_of_week.0),
                is_expanded: false,
            });
        };
        if m.high_temperature != i8::MAX {
            fields.push(Field {
                num: 13,
                profile_type: ProfileType::SINT8,
                value: Value::Int8(m.high_temperature),
                is_expanded: false,
            });
        };
        if m.low_temperature != i8::MAX {
            fields.push(Field {
                num: 14,
                profile_type: ProfileType::SINT8,
                value: Value::Int8(m.low_temperature),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::WEATHER_CONDITIONS,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}
