// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(unused, clippy::comparison_to_empty, clippy::manual_range_patterns)]

use crate::profile::{ProfileType, typedef};
use crate::proto::*;
use alloc::string::String;
use alloc::vec::Vec;

#[derive(Debug, Clone)]
/// WeatherAlert is a WeatherAlert message.
pub struct WeatherAlert {
    pub timestamp: typedef::DateTime,
    /// Unique identifier from GCS report ID string, length is 12
    pub report_id: String,
    /// Time alert was issued
    pub issue_time: typedef::DateTime,
    /// Time alert expires
    pub expire_time: typedef::DateTime,
    /// Warning, Watch, Advisory, Statement
    pub severity: typedef::WeatherSeverity,
    /// Tornado, Severe Thunderstorm, etc.
    pub r#type: typedef::WeatherSevereType,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl WeatherAlert {
    /// Value's type: `u32`
    pub const TIMESTAMP: u8 = 253;
    /// Value's type: `String`
    pub const REPORT_ID: u8 = 0;
    /// Value's type: `u32`
    pub const ISSUE_TIME: u8 = 1;
    /// Value's type: `u32`
    pub const EXPIRE_TIME: u8 = 2;
    /// Value's type: `u8`
    pub const SEVERITY: u8 = 3;
    /// Value's type: `u8`
    pub const TYPE: u8 = 4;

    /// Create new WeatherAlert with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            timestamp: typedef::DateTime(u32::MAX),
            report_id: String::new(),
            issue_time: typedef::DateTime(u32::MAX),
            expire_time: typedef::DateTime(u32::MAX),
            severity: typedef::WeatherSeverity(u8::MAX),
            r#type: typedef::WeatherSevereType(u8::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }
}

impl Default for WeatherAlert {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for WeatherAlert {
    /// from creates new WeatherAlert struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        let mut vals: [&Value; 254] = [const { &Value::Invalid }; 254];

        const KNOWN_NUMS: [u64; 4] = [31, 0, 0, 2305843009213693952];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }
        let mut unknown_fields: Vec<Field> = Vec::with_capacity(n as usize);

        for field in &mesg.fields {
            if (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 == 0 {
                unknown_fields.push(field.clone());
                continue;
            }
            vals[field.num as usize] = &field.value;
        }

        Self {
            timestamp: typedef::DateTime(vals[253].as_u32()),
            report_id: vals[0].as_string(),
            issue_time: typedef::DateTime(vals[1].as_u32()),
            expire_time: typedef::DateTime(vals[2].as_u32()),
            severity: typedef::WeatherSeverity(vals[3].as_u8()),
            r#type: typedef::WeatherSevereType(vals[4].as_u8()),
            unknown_fields,
            developer_fields: mesg.developer_fields.clone(),
        }
    }
}

impl From<WeatherAlert> for Message {
    fn from(m: WeatherAlert) -> Self {
        let mut arr = [const {
            Field {
                num: 0,
                profile_type: ProfileType(0),
                value: Value::Invalid,
                is_expanded: false,
            }
        }; 6];
        let mut len = 0usize;

        if m.timestamp != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 253,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.timestamp.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.report_id != String::new() {
            arr[len] = Field {
                num: 0,
                profile_type: ProfileType::STRING,
                value: Value::String(m.report_id),
                is_expanded: false,
            };
            len += 1;
        }
        if m.issue_time != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 1,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.issue_time.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.expire_time != typedef::DateTime(u32::MAX) {
            arr[len] = Field {
                num: 2,
                profile_type: ProfileType::DATE_TIME,
                value: Value::Uint32(m.expire_time.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.severity != typedef::WeatherSeverity(u8::MAX) {
            arr[len] = Field {
                num: 3,
                profile_type: ProfileType::WEATHER_SEVERITY,
                value: Value::Uint8(m.severity.0),
                is_expanded: false,
            };
            len += 1;
        }
        if m.r#type != typedef::WeatherSevereType(u8::MAX) {
            arr[len] = Field {
                num: 4,
                profile_type: ProfileType::WEATHER_SEVERE_TYPE,
                value: Value::Uint8(m.r#type.0),
                is_expanded: false,
            };
            len += 1;
        }

        Message {
            header: 0,
            num: typedef::MesgNum::WEATHER_ALERT,
            fields: {
                let mut fields: Vec<Field> = Vec::with_capacity(len + m.unknown_fields.len());
                fields.extend_from_slice(&arr[..len]);
                fields.extend_from_slice(&m.unknown_fields);
                fields
            },
            developer_fields: m.developer_fields,
        }
    }
}
