// Code generated by fitgen/main.go. DO NOT EDIT.

// Copyright 2025 The RustyFIT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use crate::profile::typedef::{self, FitBaseType};
use crate::proto::*;
use alloc::vec::Vec;
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize, Serializer, ser::SerializeStruct};

/// Workout Session message.
#[cfg_attr(feature = "serde", derive(Deserialize), serde(from = "De"))]
#[derive(Debug, Clone)]
pub struct WorkoutSession {
    pub message_index: typedef::MessageIndex,
    pub sport: typedef::Sport,
    pub sub_sport: typedef::SubSport,
    pub num_valid_steps: u16,
    pub first_step_index: u16,
    /// Scale: 100; Units: m
    pub pool_length: u16,
    pub pool_length_unit: typedef::DisplayMeasure,
    /// unknown_fields are fields that are exist but they are not defined in Profile.xlsx
    pub unknown_fields: Vec<Field>,
    /// developer_fields are custom data fields (Added since protocol version 2.0)
    pub developer_fields: Vec<DeveloperField>,
}

impl WorkoutSession {
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::MessageIndex
    pub const MESSAGE_INDEX: u8 = 254;
    /// Value's type: `u8`; FitBaseType::ENUM; ProfileType::Sport
    pub const SPORT: u8 = 0;
    /// Value's type: `u8`; FitBaseType::ENUM; ProfileType::SubSport
    pub const SUB_SPORT: u8 = 1;
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::Uint16
    pub const NUM_VALID_STEPS: u8 = 2;
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::Uint16
    pub const FIRST_STEP_INDEX: u8 = 3;
    /// Value's type: `u16`; FitBaseType::UINT16; ProfileType::Uint16; Scale: `100`; Units: `m`
    pub const POOL_LENGTH: u8 = 4;
    /// Value's type: `u8`; FitBaseType::ENUM; ProfileType::DisplayMeasure
    pub const POOL_LENGTH_UNIT: u8 = 5;

    /// Create new WorkoutSession with all fields being set to its corresponding invalid value.
    pub const fn new() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            sport: typedef::Sport(u8::MAX),
            sub_sport: typedef::SubSport(u8::MAX),
            num_valid_steps: u16::MAX,
            first_step_index: u16::MAX,
            pool_length: u16::MAX,
            pool_length_unit: typedef::DisplayMeasure(u8::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }

    /// Returns `pool_length` in its scaled value. It returns `None` when value is invalid.
    ///
    /// Units: m
    pub fn pool_length_scaled(&self) -> Option<f64> {
        if self.pool_length == u16::MAX {
            return None;
        }
        Some(self.pool_length as f64 / 100.0 - 0.0)
    }

    /// Set `pool_length` with scaled value, it will automatically be converted to its corresponding integer value.
    pub fn set_pool_length_scaled(&mut self, v: f64) -> &mut Self {
        let unscaled = (v + 0.0) * 100.0;
        if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
            self.pool_length = u16::MAX;
            return self;
        }
        self.pool_length = unscaled as u16;
        self
    }

    fn count_valid_fields(&self) -> usize {
        (self.message_index.0 != u16::MAX) as usize
            + (self.sport.0 != u8::MAX) as usize
            + (self.sub_sport.0 != u8::MAX) as usize
            + (self.num_valid_steps != u16::MAX) as usize
            + (self.first_step_index != u16::MAX) as usize
            + (self.pool_length != u16::MAX) as usize
            + (self.pool_length_unit.0 != u8::MAX) as usize
    }
}

impl Default for WorkoutSession {
    fn default() -> Self {
        Self::new()
    }
}

impl From<&Message> for WorkoutSession {
    /// from creates new WorkoutSession struct based on given mesg.
    fn from(mesg: &Message) -> Self {
        const KNOWN_NUMS: [u64; 4] = [63, 0, 0, 4611686018427387904];
        let mut n = 0u64;
        for field in &mesg.fields {
            n += (KNOWN_NUMS[field.num as usize >> 6] >> (field.num & 63)) & 1 ^ 1
        }

        let mut v = Self::new();
        v.unknown_fields = Vec::<Field>::with_capacity(n as usize);
        v.developer_fields = mesg.developer_fields.clone();

        for field in &mesg.fields {
            match field.num {
                254 => v.message_index = typedef::MessageIndex(field.value.as_u16()),
                0 => v.sport = typedef::Sport(field.value.as_u8()),
                1 => v.sub_sport = typedef::SubSport(field.value.as_u8()),
                2 => v.num_valid_steps = field.value.as_u16(),
                3 => v.first_step_index = field.value.as_u16(),
                4 => v.pool_length = field.value.as_u16(),
                5 => v.pool_length_unit = typedef::DisplayMeasure(field.value.as_u8()),
                _ => v.unknown_fields.push(field.clone()),
            };
        }

        v
    }
}

impl From<WorkoutSession> for Message {
    fn from(m: WorkoutSession) -> Self {
        let mut fields =
            Vec::<Field>::with_capacity(m.count_valid_fields() + m.unknown_fields.len());

        if m.message_index.0 != u16::MAX {
            fields.push(Field {
                num: 254,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.message_index.0),
                is_expanded: false,
            });
        };
        if m.sport.0 != u8::MAX {
            fields.push(Field {
                num: 0,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.sport.0),
                is_expanded: false,
            });
        };
        if m.sub_sport.0 != u8::MAX {
            fields.push(Field {
                num: 1,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.sub_sport.0),
                is_expanded: false,
            });
        };
        if m.num_valid_steps != u16::MAX {
            fields.push(Field {
                num: 2,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.num_valid_steps),
                is_expanded: false,
            });
        };
        if m.first_step_index != u16::MAX {
            fields.push(Field {
                num: 3,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.first_step_index),
                is_expanded: false,
            });
        };
        if m.pool_length != u16::MAX {
            fields.push(Field {
                num: 4,
                base_type: FitBaseType::UINT16,
                value: Value::Uint16(m.pool_length),
                is_expanded: false,
            });
        };
        if m.pool_length_unit.0 != u8::MAX {
            fields.push(Field {
                num: 5,
                base_type: FitBaseType::ENUM,
                value: Value::Uint8(m.pool_length_unit.0),
                is_expanded: false,
            });
        };

        fields.extend_from_slice(&m.unknown_fields);

        Self {
            header: 0,
            num: typedef::MesgNum::WORKOUT_SESSION,
            fields,
            developer_fields: m.developer_fields,
        }
    }
}

#[cfg(feature = "serde")]
impl Serialize for WorkoutSession {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let n = self.count_valid_fields() + 2;
        let mut state = serializer.serialize_struct("WorkoutSession", n)?;
        if self.message_index.0 != u16::MAX {
            state.serialize_field("message_index", &self.message_index)?;
        }
        if self.sport.0 != u8::MAX {
            state.serialize_field("sport", &self.sport)?;
        }
        if self.sub_sport.0 != u8::MAX {
            state.serialize_field("sub_sport", &self.sub_sport)?;
        }
        if self.num_valid_steps != u16::MAX {
            state.serialize_field("num_valid_steps", &self.num_valid_steps)?;
        }
        if self.first_step_index != u16::MAX {
            state.serialize_field("first_step_index", &self.first_step_index)?;
        }
        if let Some(v) = self.pool_length_scaled() {
            state.serialize_field("pool_length", &v)?;
        }
        if self.pool_length_unit.0 != u8::MAX {
            state.serialize_field("pool_length_unit", &self.pool_length_unit)?;
        }
        if !self.unknown_fields.is_empty() {
            state.serialize_field("unknown_fields", &self.unknown_fields)?;
        }
        if !self.developer_fields.is_empty() {
            state.serialize_field("developer_fields", &self.developer_fields)?;
        }
        state.end()
    }
}

#[cfg(feature = "serde")]
#[cfg_attr(feature = "serde", derive(Deserialize), serde(default))]
struct De {
    message_index: typedef::MessageIndex,
    sport: typedef::Sport,
    sub_sport: typedef::SubSport,
    num_valid_steps: u16,
    first_step_index: u16,
    pool_length: f64,
    pool_length_unit: typedef::DisplayMeasure,
    unknown_fields: Vec<Field>,
    developer_fields: Vec<DeveloperField>,
}

#[cfg(feature = "serde")]
impl From<De> for WorkoutSession {
    fn from(m: De) -> Self {
        Self {
            message_index: m.message_index,
            sport: m.sport,
            sub_sport: m.sub_sport,
            num_valid_steps: m.num_valid_steps,
            first_step_index: m.first_step_index,
            pool_length: {
                let unscaled = (m.pool_length + 0.0) * 100.0;
                if unscaled.is_nan() || unscaled.is_infinite() || unscaled > u16::MAX as f64 {
                    u16::MAX
                } else {
                    unscaled as u16
                }
            },
            pool_length_unit: m.pool_length_unit,
            unknown_fields: m.unknown_fields,
            developer_fields: m.developer_fields,
        }
    }
}

#[cfg(feature = "serde")]
impl Default for De {
    fn default() -> Self {
        Self {
            message_index: typedef::MessageIndex(u16::MAX),
            sport: typedef::Sport(u8::MAX),
            sub_sport: typedef::SubSport(u8::MAX),
            num_valid_steps: u16::MAX,
            first_step_index: u16::MAX,
            pool_length: f64::from_bits(u64::MAX),
            pool_length_unit: typedef::DisplayMeasure(u8::MAX),
            unknown_fields: Vec::new(),
            developer_fields: Vec::new(),
        }
    }
}
