[package]
name = "rustyfit"
version = "0.10.1"
description = """
The #![no_std] Rust implementation of The Flexible and Interoperable Data Transfer (FIT) 
Protocol for decoding and encoding Garmin FIT files, supporting FIT Protocol V2.
"""
readme = "../README.md"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
include.workspace = true
categories = [
    "encoding",
    "parsing",
    "parser-implementations",
    "embedded",
    "no-std",
]
keywords = [
    "no_std",
    "encoding",
    "fit",
    "garmin",
]

[dependencies]
embedded-io = { version = "0.7.1" }
serde = { version = "1.0.228", default-features = false, features = ["derive", "alloc"], optional = true }

[dev-dependencies]
criterion = { version = "0.8.2" }
embedded-io-adapters = { version = "0.7.0", features = ["std"] }
serde_json = { version = "1.0.150", default-features = false, features = ["alloc"] }

[features]
serde = ["dep:serde"]

[[bench]]
name = "bench_main"
harness = false

[[bench]]
name = "decoder"
harness = false

[[bench]]
name = "encoder"
harness = false

[[bench]]
name = "mesgdef"
harness = false
