[package]
name = "rustyfit"
version = "0.1.0"
edition = "2024"
description = "This project hosts the Rust implementation for The Flexible and Interoperable Data Transfer (FIT) Protocol"
authors = ["Hikmatulloh Hari Mukti <muktihaz@gmail.com>"]
readme = "../README.md"
license = "BSD 3-Clause"
include = ["Cargo.toml", "src/**", "README.md", "LICENSE"]
categories = ["encoding", "decoder", "encoder", "fit", "protocol"]
repository = "github.com/muktihari/rustyfit"

[dev-dependencies]
criterion = { version = "0.5.1" }

[[bench]]
name = "bench_main"
harness = false
