[package]
edition = "2024"
rust-version = "1.85"
name = "rustyfit"
version = "0.6.1"
description = """
The #![no_std] Rust implementation of The Flexible and Interoperable Data Transfer (FIT) 
Protocol for decoding and encoding Garmin FIT files, supporting FIT Protocol V2.
"""
authors = ["Hikmatulloh Hari Mukti <muktihaz@gmail.com>"]
repository = "https://github.com/muktihari/rustyfit"
readme = "../README.md"
license = "BSD-3-Clause"
include = [
    "Cargo.toml", 
    "src/**",
    "LICENSE-BSD-3-CLAUSE",
]
categories = [
    "encoding",
    "parsing",
    "parser-implementations",
    "embedded",
    "no-std",
]
keywords = [
    "no_std",
    "encoding",
    "fit",
    "garmin",
]

[dependencies]
embedded-io = { version = "0.7.1" }

[dev-dependencies]
criterion = { version = "0.8.2" }
embedded-io-adapters = { version = "0.7.0", features = ["std"] }

[[bench]]
name = "bench_main"
harness = false

[[bench]]
name = "decoder"
harness = false

[[bench]]
name = "encoder"
harness = false

[[bench]]
name = "mesgdef"
harness = false
